In [1]:
# ==========================================
# 1. Import Libraries
# ==========================================

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt

# NLP
import re
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Evaluation
from sklearn.metrics import silhouette_score


# Download NLP resources (first run only)
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file

df = pd.read_csv("6a_results_barSizes.csv")

# Display first rows
df.head()

       Record Name  Width    Height  Area (Width x Height)
0             a549  365.0  0.006387               2.331183
1           abnorm  365.0  0.005670               2.069498
2           alanin  365.0  0.005515               2.012827
3  aminotransferas  365.0  0.005523               2.015722
4       antiprolif  365.0  0.005169               1.886614

In [3]:
# Remove duplicate rows

df = df.drop_duplicates()

# Fill missing values

df = df.fillna("")

df.head()

       Record Name  Width    Height  Area (Width x Height)
0             a549  365.0  0.006387               2.331183
1           abnorm  365.0  0.005670               2.069498
2           alanin  365.0  0.005515               2.012827
3  aminotransferas  365.0  0.005523               2.015722
4       antiprolif  365.0  0.005169               1.886614

In [4]:
df.columns

Index(['Record Name', 'Width', 'Height', 'Area (Width x Height)'], dtype='str')

In [6]:
df.head()

       Record Name  Width    Height  Area (Width x Height)
0             a549  365.0  0.006387               2.331183
1           abnorm  365.0  0.005670               2.069498
2           alanin  365.0  0.005515               2.012827
3  aminotransferas  365.0  0.005523               2.015722
4       antiprolif  365.0  0.005169               1.886614

In [7]:
df.head()

       Record Name  Width    Height  Area (Width x Height)
0             a549  365.0  0.006387               2.331183
1           abnorm  365.0  0.005670               2.069498
2           alanin  365.0  0.005515               2.012827
3  aminotransferas  365.0  0.005523               2.015722
4       antiprolif  365.0  0.005169               1.886614

In [10]:
print(dir())

['In', 'KMeans', 'Out', 'PCA', 'StandardScaler', 'TfidfVectorizer', '_', '_1', '_2', '_3', '_4', '_6', '_7', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__session__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'clean_text', 'df', 'exit', 'get_ipython', 'nltk', 'np', 'open', 'pd', 'plt', 'quit', 're', 'silhouette_score', 'stop_words', 'stopwords']

In [13]:
%whos

Variable           Type                    Data/Info
----------------------------------------------------
KMeans             ABCMeta                 <class 'sklearn.cluster._kmeans.KMeans'>
PCA                ABCMeta                 <class 'sklearn.decomposition._pca.PCA'>
StandardScaler     type                    <class 'sklearn.preproces<...>ng._data.StandardScaler'>
TfidfVectorizer    type                    <class 'sklearn.feature_e<...>on.text.TfidfVectorizer'>
clean_text         function                <function clean_text at 0x12a501760>
df                 DataFrame               Shape: (139, 4)
nltk               module                  <module 'nltk' from '/Use<...>ckages/nltk/__init__.py'>
np                 module                  <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pd                 module                  <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
plt                module                  <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
re                 module                  <module 're' from '/Users<...>thon3.12/re/__init__.py'>
silhouette_score   function                <function silhouette_score at 0x128a96340>
stop_words         set                     {"doesn't", "don't", 's',<...>hat'll", 'during', 'did'}
stopwords          WordListCorpusReader    <WordListCorpusReader in <...>_data/corpora/stopwords'>

In [14]:
df.to_csv(
    "6a_results_barSizes_clustered.csv",
    index=False
)

print("Saved successfully")

Saved successfully