In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt

# NLP
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Download NLP resources
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("Aids Data.csv")

# Display first rows
df.head()

                   Indicator    Unit  Subgroup  Time Period  Data Value
0  Deaths averted due to ART  Number  estimate         2010    762485.0
1  Deaths averted due to ART  Number  estimate         2011    840903.0
2  Deaths averted due to ART  Number  estimate         2012    973645.0
3  Deaths averted due to ART  Number  estimate         2013   1090040.0
4  Deaths averted due to ART  Number  estimate         2014   1162780.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2316 entries, 0 to 2315
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Indicator    2316 non-null   str
 1   Unit         2316 non-null   str
 2   Subgroup     2316 non-null   str
 3   Time Period  2316 non-null   int64
 4   Data Value   2316 non-null   float64
dtypes: float64(1), int64(1), str(3)
memory usage: 213.7 KB

In [4]:
df.isnull().sum()

Indicator      0
Unit           0
Subgroup       0
Time Period    0
Data Value     0
dtype: int64

In [5]:
df.select_dtypes(include=['object']).columns

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_94896/549554427.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=['object']).columns

Index(['Indicator', 'Unit', 'Subgroup'], dtype='str')

In [6]:
df.head()

                   Indicator    Unit  Subgroup  Time Period  Data Value
0  Deaths averted due to ART  Number  estimate         2010    762485.0
1  Deaths averted due to ART  Number  estimate         2011    840903.0
2  Deaths averted due to ART  Number  estimate         2012    973645.0
3  Deaths averted due to ART  Number  estimate         2013   1090040.0
4  Deaths averted due to ART  Number  estimate         2014   1162780.0

In [8]:
print(df.head())
print(df.columns)
print(df.info())

                   Indicator    Unit  Subgroup  Time Period  Data Value
0  Deaths averted due to ART  Number  estimate         2010    762485.0
1  Deaths averted due to ART  Number  estimate         2011    840903.0
2  Deaths averted due to ART  Number  estimate         2012    973645.0
3  Deaths averted due to ART  Number  estimate         2013   1090040.0
4  Deaths averted due to ART  Number  estimate         2014   1162780.0
Index(['Indicator', 'Unit', 'Subgroup', 'Time Period', 'Data Value'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 2316 entries, 0 to 2315
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Indicator    2316 non-null   str
 1   Unit         2316 non-null   str
 2   Subgroup     2316 non-null   str
 3   Time Period  2316 non-null   int64
 4   Data Value   2316 non-null   float64
dtypes: float64(1), int64(1), str(3)
memory usage: 213.7 KB
None

In [9]:
df.head()

                   Indicator    Unit  Subgroup  Time Period  Data Value
0  Deaths averted due to ART  Number  estimate         2010    762485.0
1  Deaths averted due to ART  Number  estimate         2011    840903.0
2  Deaths averted due to ART  Number  estimate         2012    973645.0
3  Deaths averted due to ART  Number  estimate         2013   1090040.0
4  Deaths averted due to ART  Number  estimate         2014   1162780.0

In [11]:
df.to_csv(
    "Aids_Data_KMeans_Result.csv",
    index=False
)