In [1]:
!pip install pandas scikit-learn nltk matplotlib seaborn

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
import re

Requirement already satisfied: pandas in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.0.4)
Requirement already satisfied: scikit-learn in ./miniconda3/envs/coding/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: nltk in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.9.2)
Requirement already satisfied: matplotlib in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.11.0)
Requirement already satisfied: seaborn in ./miniconda3/envs/coding/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (2025.10.23)
Requirement already satisfied: tqdm in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (4.67.1)
Requirement already satisfied: contourpy>=1.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("stats_processed_all_bouts.csv")

df.head()

                                                          red_fighter_name;blue_fighter_name;event_date;red_fighter_result;blue_fighter_result;fight_outcome;method;round;time;time_format;bout_type;event_name;event_location;red_fighter_KD;blue_fighter_KD;red_fighter_sig_str_pct;blue_fighter_sig_str_pct;red_fighter_total_str_pct;blue_fighter_total_str_pct;red_fighter_TD_pct;blue_fighter_TD_pct;red_fighter_sub_att;blue_fighter_sub_att;red_fighter_rev;blue_fighter_rev;red_fighter_ctrl;blue_fighter_ctrl;red_fighter_sig_str_head_acc_pct;blue_fighter_sig_str_head_acc_pct;red_fighter_sig_str_body_acc_pct;blue_fighter_sig_str_body_acc_pct;red_fighter_sig_str_leg_acc_pct;blue_fighter_sig_str_leg_acc_pct;red_fighter_sig_str_distance_acc_pct;blue_fighter_sig_str_distance_acc_pct;red_fighter_sig_str_clinch_acc_pct;blue_fighter_sig_str_clinch_acc_pct;red_fighter_sig_str_ground_acc_pct;blue_fighter_sig_str_ground_acc_pct;red_fighter_sig_str_head_tar_pct;blue_fighter_sig_str_head_tar_pct;red_fighter_sig_str_body_tar_pct;blue_fighter_sig_str_body_tar_pct;red_fighter_sig_str_leg_tar_pct;blue_fighter_sig_str_leg_tar_pct;red_fighter_sig_str_distance_pos_pct;blue_fighter_sig_str_distance_pos_pct;red_fighter_sig_str_clinch_pos_pct;blue_fighter_sig_str_clinch_pos_pct;red_fighter_sig_str_ground_pos_pct;blue_fighter_sig_str_ground_pos_pct;red_fighter_height;red_fighter_reach;red_fighter_stance;red_fighter_slpm_cs;red_fighter_str_acc_cs;red_fighter_sapm_cs;red_fighter_str_def_cs;red_fighter_td_avg_cs;red_fighter_td_acc_cs;red_fighter_td_def_cs;red_fighter_sub_avg_cs;blue_fighter_height;blue_fighter_reach;blue_fighter_stance;blue_fighter_slpm_cs;blue_fighter_str_acc_cs;blue_fighter_sapm_cs;blue_fighter_str_def_cs;blue_fighter_td_avg_cs;blue_fighter_td_acc_cs;blue_fighter_td_def_cs;blue_fighter_sub_avg_cs;winner
JOSH EMMETT;KEVIN VALLEJOS;14/03/2026;L;W;blue_... Nevada   USA;0.0;2.0;25.0;65.0;25.0;63.24;0.0;0.0;0.0;...
AMANDA LEMOS;GILLIAN ROBERTSON;14/03/2026;L;W;b... Nevada   USA;0.0;0.0;57.0;46.0;60.71;79.01;100.0;42.0;...
ION CUTELABA;OUMAR SY;14/03/2026;W;L;red_win;Su... Nevada   USA;0.0;0.0;70.0;45.0;81.63;45.45;50.0;0.0;1....
MARWAN RAHIKI;HARRY HARDWICK;14/03/2026;W;L;red... Nevada   USA;0.0;0.0;54.0;43.0;54.39;46.34;0.0;0.0;0.0...
ANDRE FILI;JOSE DELGADO;14/03/2026;L;W;blue_win... Nevada   USA;0.0;0.0;43.0;55.0;45.45;57.54;66.0;33.0;0...

In [3]:
df.columns

Index(['red_fighter_name;blue_fighter_name;event_date;red_fighter_result;blue_fighter_result;fight_outcome;method;round;time;time_format;bout_type;event_name;event_location;red_fighter_KD;blue_fighter_KD;red_fighter_sig_str_pct;blue_fighter_sig_str_pct;red_fighter_total_str_pct;blue_fighter_total_str_pct;red_fighter_TD_pct;blue_fighter_TD_pct;red_fighter_sub_att;blue_fighter_sub_att;red_fighter_rev;blue_fighter_rev;red_fighter_ctrl;blue_fighter_ctrl;red_fighter_sig_str_head_acc_pct;blue_fighter_sig_str_head_acc_pct;red_fighter_sig_str_body_acc_pct;blue_fighter_sig_str_body_acc_pct;red_fighter_sig_str_leg_acc_pct;blue_fighter_sig_str_leg_acc_pct;red_fighter_sig_str_distance_acc_pct;blue_fighter_sig_str_distance_acc_pct;red_fighter_sig_str_clinch_acc_pct;blue_fighter_sig_str_clinch_acc_pct;red_fighter_sig_str_ground_acc_pct;blue_fighter_sig_str_ground_acc_pct;red_fighter_sig_str_head_tar_pct;blue_fighter_sig_str_head_tar_pct;red_fighter_sig_str_body_tar_pct;blue_fighter_sig_str_body_tar_pct;red_fighter_sig_str_leg_tar_pct;blue_fighter_sig_str_leg_tar_pct;red_fighter_sig_str_distance_pos_pct;blue_fighter_sig_str_distance_pos_pct;red_fighter_sig_str_clinch_pos_pct;blue_fighter_sig_str_clinch_pos_pct;red_fighter_sig_str_ground_pos_pct;blue_fighter_sig_str_ground_pos_pct;red_fighter_height;red_fighter_reach;red_fighter_stance;red_fighter_slpm_cs;red_fighter_str_acc_cs;red_fighter_sapm_cs;red_fighter_str_def_cs;red_fighter_td_avg_cs;red_fighter_td_acc_cs;red_fighter_td_def_cs;red_fighter_sub_avg_cs;blue_fighter_height;blue_fighter_reach;blue_fighter_stance;blue_fighter_slpm_cs;blue_fighter_str_acc_cs;blue_fighter_sapm_cs;blue_fighter_str_def_cs;blue_fighter_td_avg_cs;blue_fighter_td_acc_cs;blue_fighter_td_def_cs;blue_fighter_sub_avg_cs;winner'], dtype='str')

In [5]:
df.head()

                                                          red_fighter_name;blue_fighter_name;event_date;red_fighter_result;blue_fighter_result;fight_outcome;method;round;time;time_format;bout_type;event_name;event_location;red_fighter_KD;blue_fighter_KD;red_fighter_sig_str_pct;blue_fighter_sig_str_pct;red_fighter_total_str_pct;blue_fighter_total_str_pct;red_fighter_TD_pct;blue_fighter_TD_pct;red_fighter_sub_att;blue_fighter_sub_att;red_fighter_rev;blue_fighter_rev;red_fighter_ctrl;blue_fighter_ctrl;red_fighter_sig_str_head_acc_pct;blue_fighter_sig_str_head_acc_pct;red_fighter_sig_str_body_acc_pct;blue_fighter_sig_str_body_acc_pct;red_fighter_sig_str_leg_acc_pct;blue_fighter_sig_str_leg_acc_pct;red_fighter_sig_str_distance_acc_pct;blue_fighter_sig_str_distance_acc_pct;red_fighter_sig_str_clinch_acc_pct;blue_fighter_sig_str_clinch_acc_pct;red_fighter_sig_str_ground_acc_pct;blue_fighter_sig_str_ground_acc_pct;red_fighter_sig_str_head_tar_pct;blue_fighter_sig_str_head_tar_pct;red_fighter_sig_str_body_tar_pct;blue_fighter_sig_str_body_tar_pct;red_fighter_sig_str_leg_tar_pct;blue_fighter_sig_str_leg_tar_pct;red_fighter_sig_str_distance_pos_pct;blue_fighter_sig_str_distance_pos_pct;red_fighter_sig_str_clinch_pos_pct;blue_fighter_sig_str_clinch_pos_pct;red_fighter_sig_str_ground_pos_pct;blue_fighter_sig_str_ground_pos_pct;red_fighter_height;red_fighter_reach;red_fighter_stance;red_fighter_slpm_cs;red_fighter_str_acc_cs;red_fighter_sapm_cs;red_fighter_str_def_cs;red_fighter_td_avg_cs;red_fighter_td_acc_cs;red_fighter_td_def_cs;red_fighter_sub_avg_cs;blue_fighter_height;blue_fighter_reach;blue_fighter_stance;blue_fighter_slpm_cs;blue_fighter_str_acc_cs;blue_fighter_sapm_cs;blue_fighter_str_def_cs;blue_fighter_td_avg_cs;blue_fighter_td_acc_cs;blue_fighter_td_def_cs;blue_fighter_sub_avg_cs;winner
JOSH EMMETT;KEVIN VALLEJOS;14/03/2026;L;W;blue_... Nevada   USA;0.0;2.0;25.0;65.0;25.0;63.24;0.0;0.0;0.0;...
AMANDA LEMOS;GILLIAN ROBERTSON;14/03/2026;L;W;b... Nevada   USA;0.0;0.0;57.0;46.0;60.71;79.01;100.0;42.0;...
ION CUTELABA;OUMAR SY;14/03/2026;W;L;red_win;Su... Nevada   USA;0.0;0.0;70.0;45.0;81.63;45.45;50.0;0.0;1....
MARWAN RAHIKI;HARRY HARDWICK;14/03/2026;W;L;red... Nevada   USA;0.0;0.0;54.0;43.0;54.39;46.34;0.0;0.0;0.0...
ANDRE FILI;JOSE DELGADO;14/03/2026;L;W;blue_win... Nevada   USA;0.0;0.0;43.0;55.0;45.45;57.54;66.0;33.0;0...

In [8]:
print(df.columns)

Index(['red_fighter_name;blue_fighter_name;event_date;red_fighter_result;blue_fighter_result;fight_outcome;method;round;time;time_format;bout_type;event_name;event_location;red_fighter_KD;blue_fighter_KD;red_fighter_sig_str_pct;blue_fighter_sig_str_pct;red_fighter_total_str_pct;blue_fighter_total_str_pct;red_fighter_TD_pct;blue_fighter_TD_pct;red_fighter_sub_att;blue_fighter_sub_att;red_fighter_rev;blue_fighter_rev;red_fighter_ctrl;blue_fighter_ctrl;red_fighter_sig_str_head_acc_pct;blue_fighter_sig_str_head_acc_pct;red_fighter_sig_str_body_acc_pct;blue_fighter_sig_str_body_acc_pct;red_fighter_sig_str_leg_acc_pct;blue_fighter_sig_str_leg_acc_pct;red_fighter_sig_str_distance_acc_pct;blue_fighter_sig_str_distance_acc_pct;red_fighter_sig_str_clinch_acc_pct;blue_fighter_sig_str_clinch_acc_pct;red_fighter_sig_str_ground_acc_pct;blue_fighter_sig_str_ground_acc_pct;red_fighter_sig_str_head_tar_pct;blue_fighter_sig_str_head_tar_pct;red_fighter_sig_str_body_tar_pct;blue_fighter_sig_str_body_tar_pct;red_fighter_sig_str_leg_tar_pct;blue_fighter_sig_str_leg_tar_pct;red_fighter_sig_str_distance_pos_pct;blue_fighter_sig_str_distance_pos_pct;red_fighter_sig_str_clinch_pos_pct;blue_fighter_sig_str_clinch_pos_pct;red_fighter_sig_str_ground_pos_pct;blue_fighter_sig_str_ground_pos_pct;red_fighter_height;red_fighter_reach;red_fighter_stance;red_fighter_slpm_cs;red_fighter_str_acc_cs;red_fighter_sapm_cs;red_fighter_str_def_cs;red_fighter_td_avg_cs;red_fighter_td_acc_cs;red_fighter_td_def_cs;red_fighter_sub_avg_cs;blue_fighter_height;blue_fighter_reach;blue_fighter_stance;blue_fighter_slpm_cs;blue_fighter_str_acc_cs;blue_fighter_sapm_cs;blue_fighter_str_def_cs;blue_fighter_td_avg_cs;blue_fighter_td_acc_cs;blue_fighter_td_def_cs;blue_fighter_sub_avg_cs;winner'], dtype='str')

In [10]:
df.head()

                                                          red_fighter_name;blue_fighter_name;event_date;red_fighter_result;blue_fighter_result;fight_outcome;method;round;time;time_format;bout_type;event_name;event_location;red_fighter_KD;blue_fighter_KD;red_fighter_sig_str_pct;blue_fighter_sig_str_pct;red_fighter_total_str_pct;blue_fighter_total_str_pct;red_fighter_TD_pct;blue_fighter_TD_pct;red_fighter_sub_att;blue_fighter_sub_att;red_fighter_rev;blue_fighter_rev;red_fighter_ctrl;blue_fighter_ctrl;red_fighter_sig_str_head_acc_pct;blue_fighter_sig_str_head_acc_pct;red_fighter_sig_str_body_acc_pct;blue_fighter_sig_str_body_acc_pct;red_fighter_sig_str_leg_acc_pct;blue_fighter_sig_str_leg_acc_pct;red_fighter_sig_str_distance_acc_pct;blue_fighter_sig_str_distance_acc_pct;red_fighter_sig_str_clinch_acc_pct;blue_fighter_sig_str_clinch_acc_pct;red_fighter_sig_str_ground_acc_pct;blue_fighter_sig_str_ground_acc_pct;red_fighter_sig_str_head_tar_pct;blue_fighter_sig_str_head_tar_pct;red_fighter_sig_str_body_tar_pct;blue_fighter_sig_str_body_tar_pct;red_fighter_sig_str_leg_tar_pct;blue_fighter_sig_str_leg_tar_pct;red_fighter_sig_str_distance_pos_pct;blue_fighter_sig_str_distance_pos_pct;red_fighter_sig_str_clinch_pos_pct;blue_fighter_sig_str_clinch_pos_pct;red_fighter_sig_str_ground_pos_pct;blue_fighter_sig_str_ground_pos_pct;red_fighter_height;red_fighter_reach;red_fighter_stance;red_fighter_slpm_cs;red_fighter_str_acc_cs;red_fighter_sapm_cs;red_fighter_str_def_cs;red_fighter_td_avg_cs;red_fighter_td_acc_cs;red_fighter_td_def_cs;red_fighter_sub_avg_cs;blue_fighter_height;blue_fighter_reach;blue_fighter_stance;blue_fighter_slpm_cs;blue_fighter_str_acc_cs;blue_fighter_sapm_cs;blue_fighter_str_def_cs;blue_fighter_td_avg_cs;blue_fighter_td_acc_cs;blue_fighter_td_def_cs;blue_fighter_sub_avg_cs;winner
JOSH EMMETT;KEVIN VALLEJOS;14/03/2026;L;W;blue_... Nevada   USA;0.0;2.0;25.0;65.0;25.0;63.24;0.0;0.0;0.0;...
AMANDA LEMOS;GILLIAN ROBERTSON;14/03/2026;L;W;b... Nevada   USA;0.0;0.0;57.0;46.0;60.71;79.01;100.0;42.0;...
ION CUTELABA;OUMAR SY;14/03/2026;W;L;red_win;Su... Nevada   USA;0.0;0.0;70.0;45.0;81.63;45.45;50.0;0.0;1....
MARWAN RAHIKI;HARRY HARDWICK;14/03/2026;W;L;red... Nevada   USA;0.0;0.0;54.0;43.0;54.39;46.34;0.0;0.0;0.0...
ANDRE FILI;JOSE DELGADO;14/03/2026;L;W;blue_win... Nevada   USA;0.0;0.0;43.0;55.0;45.45;57.54;66.0;33.0;0...

In [11]:
df.head()

                                                          red_fighter_name;blue_fighter_name;event_date;red_fighter_result;blue_fighter_result;fight_outcome;method;round;time;time_format;bout_type;event_name;event_location;red_fighter_KD;blue_fighter_KD;red_fighter_sig_str_pct;blue_fighter_sig_str_pct;red_fighter_total_str_pct;blue_fighter_total_str_pct;red_fighter_TD_pct;blue_fighter_TD_pct;red_fighter_sub_att;blue_fighter_sub_att;red_fighter_rev;blue_fighter_rev;red_fighter_ctrl;blue_fighter_ctrl;red_fighter_sig_str_head_acc_pct;blue_fighter_sig_str_head_acc_pct;red_fighter_sig_str_body_acc_pct;blue_fighter_sig_str_body_acc_pct;red_fighter_sig_str_leg_acc_pct;blue_fighter_sig_str_leg_acc_pct;red_fighter_sig_str_distance_acc_pct;blue_fighter_sig_str_distance_acc_pct;red_fighter_sig_str_clinch_acc_pct;blue_fighter_sig_str_clinch_acc_pct;red_fighter_sig_str_ground_acc_pct;blue_fighter_sig_str_ground_acc_pct;red_fighter_sig_str_head_tar_pct;blue_fighter_sig_str_head_tar_pct;red_fighter_sig_str_body_tar_pct;blue_fighter_sig_str_body_tar_pct;red_fighter_sig_str_leg_tar_pct;blue_fighter_sig_str_leg_tar_pct;red_fighter_sig_str_distance_pos_pct;blue_fighter_sig_str_distance_pos_pct;red_fighter_sig_str_clinch_pos_pct;blue_fighter_sig_str_clinch_pos_pct;red_fighter_sig_str_ground_pos_pct;blue_fighter_sig_str_ground_pos_pct;red_fighter_height;red_fighter_reach;red_fighter_stance;red_fighter_slpm_cs;red_fighter_str_acc_cs;red_fighter_sapm_cs;red_fighter_str_def_cs;red_fighter_td_avg_cs;red_fighter_td_acc_cs;red_fighter_td_def_cs;red_fighter_sub_avg_cs;blue_fighter_height;blue_fighter_reach;blue_fighter_stance;blue_fighter_slpm_cs;blue_fighter_str_acc_cs;blue_fighter_sapm_cs;blue_fighter_str_def_cs;blue_fighter_td_avg_cs;blue_fighter_td_acc_cs;blue_fighter_td_def_cs;blue_fighter_sub_avg_cs;winner
JOSH EMMETT;KEVIN VALLEJOS;14/03/2026;L;W;blue_... Nevada   USA;0.0;2.0;25.0;65.0;25.0;63.24;0.0;0.0;0.0;...
AMANDA LEMOS;GILLIAN ROBERTSON;14/03/2026;L;W;b... Nevada   USA;0.0;0.0;57.0;46.0;60.71;79.01;100.0;42.0;...
ION CUTELABA;OUMAR SY;14/03/2026;W;L;red_win;Su... Nevada   USA;0.0;0.0;70.0;45.0;81.63;45.45;50.0;0.0;1....
MARWAN RAHIKI;HARRY HARDWICK;14/03/2026;W;L;red... Nevada   USA;0.0;0.0;54.0;43.0;54.39;46.34;0.0;0.0;0.0...
ANDRE FILI;JOSE DELGADO;14/03/2026;L;W;blue_win... Nevada   USA;0.0;0.0;43.0;55.0;45.45;57.54;66.0;33.0;0...

In [13]:
print(df.columns)

Index(['red_fighter_name;blue_fighter_name;event_date;red_fighter_result;blue_fighter_result;fight_outcome;method;round;time;time_format;bout_type;event_name;event_location;red_fighter_KD;blue_fighter_KD;red_fighter_sig_str_pct;blue_fighter_sig_str_pct;red_fighter_total_str_pct;blue_fighter_total_str_pct;red_fighter_TD_pct;blue_fighter_TD_pct;red_fighter_sub_att;blue_fighter_sub_att;red_fighter_rev;blue_fighter_rev;red_fighter_ctrl;blue_fighter_ctrl;red_fighter_sig_str_head_acc_pct;blue_fighter_sig_str_head_acc_pct;red_fighter_sig_str_body_acc_pct;blue_fighter_sig_str_body_acc_pct;red_fighter_sig_str_leg_acc_pct;blue_fighter_sig_str_leg_acc_pct;red_fighter_sig_str_distance_acc_pct;blue_fighter_sig_str_distance_acc_pct;red_fighter_sig_str_clinch_acc_pct;blue_fighter_sig_str_clinch_acc_pct;red_fighter_sig_str_ground_acc_pct;blue_fighter_sig_str_ground_acc_pct;red_fighter_sig_str_head_tar_pct;blue_fighter_sig_str_head_tar_pct;red_fighter_sig_str_body_tar_pct;blue_fighter_sig_str_body_tar_pct;red_fighter_sig_str_leg_tar_pct;blue_fighter_sig_str_leg_tar_pct;red_fighter_sig_str_distance_pos_pct;blue_fighter_sig_str_distance_pos_pct;red_fighter_sig_str_clinch_pos_pct;blue_fighter_sig_str_clinch_pos_pct;red_fighter_sig_str_ground_pos_pct;blue_fighter_sig_str_ground_pos_pct;red_fighter_height;red_fighter_reach;red_fighter_stance;red_fighter_slpm_cs;red_fighter_str_acc_cs;red_fighter_sapm_cs;red_fighter_str_def_cs;red_fighter_td_avg_cs;red_fighter_td_acc_cs;red_fighter_td_def_cs;red_fighter_sub_avg_cs;blue_fighter_height;blue_fighter_reach;blue_fighter_stance;blue_fighter_slpm_cs;blue_fighter_str_acc_cs;blue_fighter_sapm_cs;blue_fighter_str_def_cs;blue_fighter_td_avg_cs;blue_fighter_td_acc_cs;blue_fighter_td_def_cs;blue_fighter_sub_avg_cs;winner'], dtype='str')

In [17]:

print(df.columns.tolist())

['red_fighter_name;blue_fighter_name;event_date;red_fighter_result;blue_fighter_result;fight_outcome;method;round;time;time_format;bout_type;event_name;event_location;red_fighter_KD;blue_fighter_KD;red_fighter_sig_str_pct;blue_fighter_sig_str_pct;red_fighter_total_str_pct;blue_fighter_total_str_pct;red_fighter_TD_pct;blue_fighter_TD_pct;red_fighter_sub_att;blue_fighter_sub_att;red_fighter_rev;blue_fighter_rev;red_fighter_ctrl;blue_fighter_ctrl;red_fighter_sig_str_head_acc_pct;blue_fighter_sig_str_head_acc_pct;red_fighter_sig_str_body_acc_pct;blue_fighter_sig_str_body_acc_pct;red_fighter_sig_str_leg_acc_pct;blue_fighter_sig_str_leg_acc_pct;red_fighter_sig_str_distance_acc_pct;blue_fighter_sig_str_distance_acc_pct;red_fighter_sig_str_clinch_acc_pct;blue_fighter_sig_str_clinch_acc_pct;red_fighter_sig_str_ground_acc_pct;blue_fighter_sig_str_ground_acc_pct;red_fighter_sig_str_head_tar_pct;blue_fighter_sig_str_head_tar_pct;red_fighter_sig_str_body_tar_pct;blue_fighter_sig_str_body_tar_pct;red_fighter_sig_str_leg_tar_pct;blue_fighter_sig_str_leg_tar_pct;red_fighter_sig_str_distance_pos_pct;blue_fighter_sig_str_distance_pos_pct;red_fighter_sig_str_clinch_pos_pct;blue_fighter_sig_str_clinch_pos_pct;red_fighter_sig_str_ground_pos_pct;blue_fighter_sig_str_ground_pos_pct;red_fighter_height;red_fighter_reach;red_fighter_stance;red_fighter_slpm_cs;red_fighter_str_acc_cs;red_fighter_sapm_cs;red_fighter_str_def_cs;red_fighter_td_avg_cs;red_fighter_td_acc_cs;red_fighter_td_def_cs;red_fighter_sub_avg_cs;blue_fighter_height;blue_fighter_reach;blue_fighter_stance;blue_fighter_slpm_cs;blue_fighter_str_acc_cs;blue_fighter_sapm_cs;blue_fighter_str_def_cs;blue_fighter_td_avg_cs;blue_fighter_td_acc_cs;blue_fighter_td_def_cs;blue_fighter_sub_avg_cs;winner']