In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

# Machine learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Visualisation
import matplotlib.pyplot as plt

# Download NLP resources (run once)
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("Antibiotics.csv")

# Display first rows
df.head()

                     Bacteria   Penicillin   Streptomycin   Neomycin      Gram
0  Mycobacterium tuberculosis        800.0            5.0       2.00  negative
1   Salmonella schottmuelleri         10.0            0.8       0.09  negative
2            Proteus vulgaris          3.0            0.1       0.10  negative
3       Klebsiella pneumoniae        850.0            1.2       1.00  negative
4            Brucella abortus          1.0            2.0       0.02  negative

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Bacteria       16 non-null     str
 1    Penicillin    16 non-null     float64
 2    Streptomycin  16 non-null     float64
 3    Neomycin      16 non-null     float64
 4    Gram          16 non-null     str
dtypes: float64(3), str(2)
memory usage: 1.2 KB

In [4]:
df.columns

Index(['Bacteria', ' Penicillin', ' Streptomycin', ' Neomycin', ' Gram'], dtype='str')

In [6]:
df.head()

                     Bacteria   Penicillin   Streptomycin   Neomycin      Gram
0  Mycobacterium tuberculosis        800.0            5.0       2.00  negative
1   Salmonella schottmuelleri         10.0            0.8       0.09  negative
2            Proteus vulgaris          3.0            0.1       0.10  negative
3       Klebsiella pneumoniae        850.0            1.2       1.00  negative
4            Brucella abortus          1.0            2.0       0.02  negative

In [8]:
print(df.columns)
print(df.head())

Index(['Bacteria', ' Penicillin', ' Streptomycin', ' Neomycin', ' Gram'], dtype='str')
                     Bacteria   Penicillin   Streptomycin   Neomycin      Gram
0  Mycobacterium tuberculosis        800.0            5.0       2.00  negative
1   Salmonella schottmuelleri         10.0            0.8       0.09  negative
2            Proteus vulgaris          3.0            0.1       0.10  negative
3       Klebsiella pneumoniae        850.0            1.2       1.00  negative
4            Brucella abortus          1.0            2.0       0.02  negative

In [10]:
df.head()

                     Bacteria   Penicillin   Streptomycin   Neomycin      Gram
0  Mycobacterium tuberculosis        800.0            5.0       2.00  negative
1   Salmonella schottmuelleri         10.0            0.8       0.09  negative
2            Proteus vulgaris          3.0            0.1       0.10  negative
3       Klebsiella pneumoniae        850.0            1.2       1.00  negative
4            Brucella abortus          1.0            2.0       0.02  negative

In [13]:
print(df.columns)

Index(['Bacteria', ' Penicillin', ' Streptomycin', ' Neomycin', ' Gram'], dtype='str')

In [14]:
df.to_csv(
    "Antibiotics_clustered.csv",
    index=False
)