In [1]:
# Install if needed
# !pip install pandas numpy scikit-learn nltk matplotlib seaborn wordcloud

import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
# Load dataset
df = pd.read_csv("asian.csv")

# Display first rows
df.head()

,id,recipeName,rating,totalTimeInSeconds,course,cuisine,ingredients
0,6-Ingredient-Chinese-Chicken-1370750,6-Ingredient Chinese Chicken,4,1500.0,[Main Dishes],"[Chinese, Asian]","[minced ginger, garlic chili sauce, hoisin sau..."
1,Orange-Flavored-Chicken-_Panda-Express-Copy-Ca...,Orange Flavored Chicken (Panda Express Copy Cat),3,3000.0,[Main Dishes],[Asian],"[boneless skinless chicken breasts, egg whites..."
2,Sesame-Beef-1371164,Sesame Beef,4,1200.0,[Main Dishes],[Asian],"[sesame oil, garlic, flank steak, red bell pep..."
3,Vietnamese-Vermicelli-Bowl-1374692,Vietnamese Vermicelli Bowl,4,3300.0,[Main Dishes],[Asian],"[chicken, lemongrass, onions, garlic cloves, k..."
4,Easy-Pork-Fried-Rice-1365600,Easy Pork Fried Rice,4,1800.0,[],[Asian],"[eggs, smoked ham, shallots, carrots, long-gra..."

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  605 non-null    str
 1   recipeName          605 non-null    str
 2   rating              605 non-null    int64
 3   totalTimeInSeconds  598 non-null    float64
 4   course              515 non-null    str
 5   cuisine             605 non-null    str
 6   ingredients         605 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 167.5 KB

In [6]:
print(df.columns.tolist())

['id', 'recipeName', 'rating', 'totalTimeInSeconds', 'course', 'cuisine', 'ingredients']

In [7]:
df.head()

,id,recipeName,rating,totalTimeInSeconds,course,cuisine,ingredients
0,6-Ingredient-Chinese-Chicken-1370750,6-Ingredient Chinese Chicken,4,1500.0,[Main Dishes],"[Chinese, Asian]","[minced ginger, garlic chili sauce, hoisin sau..."
1,Orange-Flavored-Chicken-_Panda-Express-Copy-Ca...,Orange Flavored Chicken (Panda Express Copy Cat),3,3000.0,[Main Dishes],[Asian],"[boneless skinless chicken breasts, egg whites..."
2,Sesame-Beef-1371164,Sesame Beef,4,1200.0,[Main Dishes],[Asian],"[sesame oil, garlic, flank steak, red bell pep..."
3,Vietnamese-Vermicelli-Bowl-1374692,Vietnamese Vermicelli Bowl,4,3300.0,[Main Dishes],[Asian],"[chicken, lemongrass, onions, garlic cloves, k..."
4,Easy-Pork-Fried-Rice-1365600,Easy Pork Fried Rice,4,1800.0,[],[Asian],"[eggs, smoked ham, shallots, carrots, long-gra..."

In [8]:
df.to_csv(
    "asian_clustered.csv",
    index=False
)