In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Dimensionality reduction
from sklearn.decomposition import PCA

import warnings
warnings.filterwarnings("ignore")

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file

df = pd.read_csv("auto_imports.csv")

# Display first rows
df.head()

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   3            200 non-null    int64
 1   ?            200 non-null    str
 2   alfa-romero  200 non-null    str
 3   gas          200 non-null    str
 4   std          200 non-null    str
 5   two          200 non-null    str
 6   convertible  200 non-null    str
 7   rwd          200 non-null    str
 8   front        200 non-null    str
 9   88.60        200 non-null    float64
 10  168.80       200 non-null    float64
 11  64.10        200 non-null    float64
 12  48.80        200 non-null    float64
 13  2548         200 non-null    int64
 14  dohc         200 non-null    str
 15  four         200 non-null    str
 16  130          200 non-null    int64
 17  mpfi         200 non-null    str
 18  3.47         200 non-null    str
 19  2.68         200 non-null    str
 20  9.00         200 non-null    float64
 21  111          200 non-null    str
 22  5000         200 non-null    str
 23  21           200 non-null    int64
 24  27           200 non-null    int64
 25  13495        200 non-null    int64
dtypes: float64(5), int64(6), str(15)
memory usage: 52.2 KB

In [5]:


df.head()

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [6]:
text_columns = df.select_dtypes(include=['object']).columns

text_columns

Index(['?', 'alfa-romero', 'gas', 'std', 'two', 'convertible', 'rwd', 'front',
       'dohc', 'four', 'mpfi', '3.47', '2.68', '111', '5000'],
      dtype='str')

In [8]:
df.head()

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [9]:
numeric_features = df.select_dtypes(
    include=np.number
)

numeric_features.head()

   3  88.60  168.80  64.10  48.80  2548  130  9.00  21  27  13495
0  3   88.6   168.8   64.1   48.8  2548  130   9.0  21  27  16500
1  1   94.5   171.2   65.5   52.4  2823  152   9.0  19  26  16500
2  2   99.8   176.6   66.2   54.3  2337  109  10.0  24  30  13950
3  2   99.4   176.6   66.4   54.3  2824  136   8.0  18  22  17450
4  2   99.8   177.3   66.3   53.1  2507  136   8.5  19  25  15250

In [10]:
df.to_csv(
    "auto_imports_clustered.csv",
    index=False
)