In [1]:
import pandas as pd
import numpy as np

import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("babel_extractors.csv")

# View structure
df.head()

,**/setup/setup_wizard/data/uom_data.json,erpnext.gettext.extractors.uom_data.extract
0,**/setup/doctype/incoterm/incoterms.csv,erpnext.gettext.extractors.incoterms.extract
1,**/setup/setup_wizard/data/*.txt,erpnext.gettext.extractors.lines_from_txt_file...
2,**.tsx,frappe.gettext.extractors.html_template.extract
3,**.ts,frappe.gettext.extractors.html_template.extract

In [4]:
print(df.columns.tolist())

['**/setup/setup_wizard/data/uom_data.json', 'erpnext.gettext.extractors.uom_data.extract']

In [6]:
df.head()

,**/setup/setup_wizard/data/uom_data.json,erpnext.gettext.extractors.uom_data.extract
0,**/setup/doctype/incoterm/incoterms.csv,erpnext.gettext.extractors.incoterms.extract
1,**/setup/setup_wizard/data/*.txt,erpnext.gettext.extractors.lines_from_txt_file...
2,**.tsx,frappe.gettext.extractors.html_template.extract
3,**.ts,frappe.gettext.extractors.html_template.extract

In [7]:
df.head()

,**/setup/setup_wizard/data/uom_data.json,erpnext.gettext.extractors.uom_data.extract
0,**/setup/doctype/incoterm/incoterms.csv,erpnext.gettext.extractors.incoterms.extract
1,**/setup/setup_wizard/data/*.txt,erpnext.gettext.extractors.lines_from_txt_file...
2,**.tsx,frappe.gettext.extractors.html_template.extract
3,**.ts,frappe.gettext.extractors.html_template.extract

In [8]:
df.to_csv("babel_clustered_output.csv", index=False)