In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
import csv

df = pd.read_csv(
    "Beatone.csv",
    quoting=csv.QUOTE_NONE,
    on_bad_lines="skip"
)

In [5]:
df.select_dtypes(include="object")

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_59140/755674511.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object")

                                                          site  ...  web
"BeAtOne"          ''              ''               'SW11 1HW'  ...   ''
                                   ''                'W1J 6ER'  ...  NaN
59 Berkeley Square  London          London            W1J 6ER'  ...  NaN
"BeAtOne"          ''              ''                'NW1 7JH'  ...   ''
                                   ''                'SW4 7AA'  ...   ''
                                   ''               'WC2E 7DA'  ...   ''
                                   ''               'KT19 8AG'  ...   ''
                                   ''               'EC1M 6JN'  ...   ''
                                   ''                 'W6 7AF'  ...   ''
                                   ''                'W1G 0EH'  ...   ''
                                   ''                'W1D 7LA'  ...   ''
                                   ''               'SW15 1SQ'  ...   ''
                                   ''                'W1F 9RA'  ...   ''
                                   ''               'TW10 6UH'  ...   ''
                                   ''               'WC2B 5HF'  ...   ''
                                   ''               'EC1V 9NQ'  ...   ''
                                   ''                'TW1 3LJ'  ...   ''
                                   ''                'CM2 0LR'  ...   ''
                                   ''                'NR2 4SF'  ...   ''
                                   ''                 'B1 2JB'  ...  NaN
"The Water's Edge   Brindley Place  Birmingham   West Midlands  ...  NaN
"BeAtOne"          ''              ''                'LN2 1HW'  ...   ''
                                   ''                 'B2 4BJ'  ...   ''
                                   ''                'NG1 2EX'  ...   ''
                                   ''                 'L1 4AU'  ...   ''
                                   ''                 'M3 2ER'  ...   ''
                                   ''                'BN1 1EG'  ...   ''
                                   ''                'MK9 2FB'  ...   ''
                                   ''                'RG1 2JR'  ...   ''
                                   ''                'BH2 6HE'  ...   ''
                                   ''                'BS8 1QQ'  ...   ''
                                   ''                'LS1 6EA'  ...   ''
                                   ''                'LS1 5RW'  ...   ''
                                   ''                'LS2 3AD'  ...   ''
                                   ''               'CF10 1FE'  ...   ''

[35 rows x 9 columns]

In [7]:
pd.get_dummies(df)

                                                site  lat  ...  email  web
"BeAtOne"          ''              ''             23    4  ...      0    0
                                   ''             31    5  ...      1    1
59 Berkeley Square  London          London         0    3  ...      1    1
"BeAtOne"          ''              ''             21   10  ...      0    0
                                   ''             25   13  ...      0    0
                                   ''             34   14  ...      0    0
                                   ''             11   15  ...      0    0
                                   ''              9   16  ...      0    0
                                   ''             32   17  ...      0    0
                                   ''             30   26  ...      0    0
                                   ''             28   27  ...      0    0
                                   ''             24   28  ...      0    0
                                   ''             29   30  ...      0    0
                                   ''             27   31  ...      0    0
                                   ''             33   32  ...      0    0
                                   ''             10   33  ...      0    0
                                   ''             26   34  ...      0    0
                                   ''              8   12  ...      0    0
                                   ''             20    1  ...      0    0
                                   ''              2    6  ...      1    1
"The Water's Edge   Brindley Place  Birmingham     1    2  ...      1    1
"BeAtOne"          ''              ''             13    0  ...      0    0
                                   ''              3   24  ...      0    0
                                   ''             19   25  ...      0    0
                                   ''             12   21  ...      0    0
                                   ''             17   22  ...      0    0
                                   ''              5    8  ...      0    0
                                   ''             18   23  ...      0    0
                                   ''             22   29  ...      0    0
                                   ''              4    7  ...      0    0
                                   ''              6    9  ...      0    0
                                   ''             15   18  ...      0    0
                                   ''             14   19  ...      0    0
                                   ''             16   20  ...      0    0
                                   ''              7   11  ...      0    0

[35 rows x 9 columns]

In [9]:
print(df.columns)

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [11]:
df.columns = df.columns.str.strip()

In [13]:
print(df.columns)

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [15]:
df.columns
df.head()

                                    site  lat  lng  ...  phone  email  web
"BeAtOne"          ''      ''         23    4   29  ...      0      0    0
                           ''         31    5   31  ...      1      1    1
59 Berkeley Square  London  London     0    3    2  ...      1      1    1
"BeAtOne"          ''      ''         21   10   23  ...      0      0    0
                           ''         25   13   19  ...      0      0    0

[5 rows x 9 columns]

In [18]:
df.head()

                                    site  lat  lng  ...  phone  email  web
"BeAtOne"          ''      ''         23    4   29  ...      0      0    0
                           ''         31    5   31  ...      1      1    1
59 Berkeley Square  London  London     0    3    2  ...      1      1    1
"BeAtOne"          ''      ''         21   10   23  ...      0      0    0
                           ''         25   13   19  ...      0      0    0

[5 rows x 9 columns]

In [22]:
print(df.head())

                                    site  lat  lng  ...  phone  email  web
"BeAtOne"          ''      ''         23    4   29  ...      0      0    0
                           ''         31    5   31  ...      1      1    1
59 Berkeley Square  London  London     0    3    2  ...      1      1    1
"BeAtOne"          ''      ''         21   10   23  ...      0      0    0
                           ''         25   13   19  ...      0      0    0

[5 rows x 9 columns]

In [23]:
print(df.columns)

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')