In [1]:
# If needed (run once)
# !pip install pandas scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("BLAS.csv")

# View data
df.head()

   Size  with_BLAS  without_BLAS
0   100       0.01      0.010000
1   400       0.40      0.440000
2   500       1.04      1.150000
3   800       6.39      6.710000
4  1000      12.63     12.950001

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(14, 3)
<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Size          14 non-null     int64
 1   with_BLAS     14 non-null     float64
 2   without_BLAS  14 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 468.0 bytes
None
              Size   with_BLAS  without_BLAS
count    14.000000   14.000000     14.000000
mean   1671.428571  160.311429    167.019287
std    1049.123129  216.563114    223.906653
min     100.000000    0.010000      0.010000
25%     850.000000    7.950000      8.270000
50%    1650.000000   69.920002     72.075003
75%    2425.000000  235.414993    242.282512
max    3500.000000  747.000000    760.000000
Size            0
with_BLAS       0
without_BLAS    0
dtype: int64

In [9]:
df.update(df.select_dtypes(include=np.number).fillna(df.median()))
df.update(df.select_dtypes(include='object').fillna(df.mode().iloc[0]))

In [10]:
label_encoders = {}

for col in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [12]:
df.head()

   Size  with_BLAS  without_BLAS
0   100       0.01      0.010000
1   400       0.40      0.440000
2   500       1.04      1.150000
3   800       6.39      6.710000
4  1000      12.63     12.950001

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Size          14 non-null     int64
 1   with_BLAS     14 non-null     float64
 2   without_BLAS  14 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 468.0 bytes

In [15]:
df.columns

Index(['Size', 'with_BLAS', 'without_BLAS'], dtype='str')

In [17]:
print(df.columns)

Index(['Size', 'with_BLAS', 'without_BLAS'], dtype='str')

In [19]:
df.head()
df.columns

Index(['Size', 'with_BLAS', 'without_BLAS'], dtype='str')

In [21]:
df.columns
df.head()

   Size  with_BLAS  without_BLAS
0   100       0.01      0.010000
1   400       0.40      0.440000
2   500       1.04      1.150000
3   800       6.39      6.710000
4  1000      12.63     12.950001

In [22]:
print(df.columns)

Index(['Size', 'with_BLAS', 'without_BLAS'], dtype='str')

In [25]:
print(rf_model)

RandomForestClassifier(max_depth=5, random_state=42)