In [1]:
# Import libraries
import pandas as pd
import numpy as np

# NLP libraries
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

# Visualization (optional)
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("blockbuster-top_ten_movies_per_year_DFE.csv")

# Display first rows
df.head()

,audience_freshness,poster_url,rt_audience_score,rt_freshness,rt_score,2015_inflation,adjusted,genres,Genre_1,Genre_2,Genre_3,imdb_rating,length,rank_in_year,rating,release_date,studio,title,worldwide_gross,year
0,92.0,http://resizing.flixster.com/gxRJwetP1eNIrPR6x...,4.3,89.0,7.5,-0.26%,"$712,903,691.09",Sci-Fi\nAdventure\nAction,Sci-Fi,Adventure,Action,7.8,136.0,7.0,PG-13,4-Apr-14,Marvel Studios,Captain America: The Winter Soldier,"$714,766,572.00",2014.0
1,89.0,http://resizing.flixster.com/gDtbA1iPxTYEjBZeS...,4.2,90.0,7.9,-0.26%,"$706,988,165.89",Sci-Fi\nDrama\nAction,Sci-Fi,Drama,Action,7.7,130.0,9.0,PG-13,11-Jul-14,20th Century Fox,Dawn of the Planet of the Apes,"$708,835,589.00",2014.0
2,93.0,http://resizing.flixster.com/YrF_OeTQx3bXNsMLI...,4.4,91.0,7.7,-0.26%,"$772,158,880.00",Sci-Fi\nAdventure\nAction,Sci-Fi,Adventure,Action,8.1,121.0,3.0,PG-13,1-Aug-14,Marvel Studios,Guardians of the Galaxy,"$774,176,600.00",2014.0
3,86.0,http://resizing.flixster.com/l9yjA-72sZMYECeOj...,4.2,72.0,7.0,-0.26%,"$671,220,455.10",Sci-Fi\nAdventure,Sci-Fi,Adventure,NaN,8.7,169.0,10.0,PG-13,7-Nov-14,Paramount Pictures / Warner Bros.,Interstellar,"$672,974,414.00",2014.0
4,71.0,http://resizing.flixster.com/YukULOFULUesVZccN...,3.8,49.0,5.7,-0.26%,"$756,677,675.77",Family\nAdventure\nAction,Family,Adventure,Action,7.1,97.0,4.0,PG,30-May-14,Walt Disney Pictures,Maleficent,"$758,654,942.00",2014.0

In [2]:
# Dataset information
df.info()

# Check column names
print(df.columns)

# Statistical summary
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   audience_freshness  398 non-null    float64
 1   poster_url          398 non-null    str
 2   rt_audience_score   398 non-null    float64
 3   rt_freshness        398 non-null    float64
 4   rt_score            398 non-null    float64
 5   2015_inflation      398 non-null    str
 6   adjusted            398 non-null    str
 7   genres              398 non-null    str
 8   Genre_1             398 non-null    str
 9   Genre_2             369 non-null    str
 10  Genre_3             269 non-null    str
 11  imdb_rating         398 non-null    float64
 12  length              398 non-null    float64
 13  rank_in_year        398 non-null    float64
 14  rating              398 non-null    str
 15  release_date        398 non-null    str
 16  studio              398 non-null    str
 17  title               398 non-null    str
 18  worldwide_gross     398 non-null    str
 19  year                398 non-null    float64
dtypes: float64(8), str(12)
memory usage: 159.0 KB
Index(['audience_freshness', 'poster_url', 'rt_audience_score', 'rt_freshness',
       'rt_score', '2015_inflation', 'adjusted', 'genres', 'Genre_1',
       'Genre_2', 'Genre_3', 'imdb_rating', 'length', 'rank_in_year', 'rating',
       'release_date', 'studio', 'title', 'worldwide_gross', 'year'],
      dtype='str')

,audience_freshness,rt_audience_score,rt_freshness,rt_score,imdb_rating,length,rank_in_year,year
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,72.268844,3.478894,69.381910,6.502764,7.053266,119.253769,5.530151,1994.665829
std,15.726587,0.391222,23.186895,1.451107,0.834777,22.973721,2.866966,11.467241
min,24.000000,1.700000,0.000000,0.000000,4.400000,27.000000,1.000000,1975.000000
25%,61.000000,3.200000,54.000000,5.700000,6.500000,102.250000,3.000000,1985.000000
50%,75.000000,3.500000,75.500000,6.600000,7.000000,117.000000,6.000000,1995.000000
75%,85.000000,3.700000,88.000000,7.500000,7.675000,131.750000,8.000000,2004.750000
max,100.000000,4.500000,100.000000,9.100000,9.000000,201.000000,10.000000,2014.000000

In [3]:
# Check missing values
df.isnull().sum()

# Fill missing text values
df = df.fillna("")

In [4]:
# Select numeric columns
numeric_cols = df.select_dtypes(include=np.number)

# Calculate means
mean_values = numeric_cols.mean()

print(mean_values)

Series([], dtype: float64)

In [5]:
nltk.download("punkt")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [7]:
df.head()

,audience_freshness,poster_url,rt_audience_score,rt_freshness,rt_score,2015_inflation,adjusted,genres,Genre_1,Genre_2,Genre_3,imdb_rating,length,rank_in_year,rating,release_date,studio,title,worldwide_gross,year
0,92.0,http://resizing.flixster.com/gxRJwetP1eNIrPR6x...,4.3,89.0,7.5,-0.26%,"$712,903,691.09",Sci-Fi\nAdventure\nAction,Sci-Fi,Adventure,Action,7.8,136.0,7.0,PG-13,4-Apr-14,Marvel Studios,Captain America: The Winter Soldier,"$714,766,572.00",2014.0
1,89.0,http://resizing.flixster.com/gDtbA1iPxTYEjBZeS...,4.2,90.0,7.9,-0.26%,"$706,988,165.89",Sci-Fi\nDrama\nAction,Sci-Fi,Drama,Action,7.7,130.0,9.0,PG-13,11-Jul-14,20th Century Fox,Dawn of the Planet of the Apes,"$708,835,589.00",2014.0
2,93.0,http://resizing.flixster.com/YrF_OeTQx3bXNsMLI...,4.4,91.0,7.7,-0.26%,"$772,158,880.00",Sci-Fi\nAdventure\nAction,Sci-Fi,Adventure,Action,8.1,121.0,3.0,PG-13,1-Aug-14,Marvel Studios,Guardians of the Galaxy,"$774,176,600.00",2014.0
3,86.0,http://resizing.flixster.com/l9yjA-72sZMYECeOj...,4.2,72.0,7.0,-0.26%,"$671,220,455.10",Sci-Fi\nAdventure,Sci-Fi,Adventure,,8.7,169.0,10.0,PG-13,7-Nov-14,Paramount Pictures / Warner Bros.,Interstellar,"$672,974,414.00",2014.0
4,71.0,http://resizing.flixster.com/YukULOFULUesVZccN...,3.8,49.0,5.7,-0.26%,"$756,677,675.77",Family\nAdventure\nAction,Family,Adventure,Action,7.1,97.0,4.0,PG,30-May-14,Walt Disney Pictures,Maleficent,"$758,654,942.00",2014.0

In [9]:
df.columns

Index(['audience_freshness', 'poster_url', 'rt_audience_score', 'rt_freshness',
       'rt_score', '2015_inflation', 'adjusted', 'genres', 'Genre_1',
       'Genre_2', 'Genre_3', 'imdb_rating', 'length', 'rank_in_year', 'rating',
       'release_date', 'studio', 'title', 'worldwide_gross', 'year'],
      dtype='str')

In [10]:
year_average = df.groupby("year")[numeric_cols.columns].mean()

year_average.head()

Empty DataFrame
Columns: []
Index: [1975.0, 1976.0, 1977.0, 1978.0, 1979.0]