In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# K-Means
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Visualization
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Download stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("challenger.csv")

# Display first rows
df.head()

   o_ring_ct  distress_ct  temperature  pressure  launch_id
0          6            0           66        50          1
1          6            1           70        50          2
2          6            0           69        50          3
3          6            0           68        50          4
4          6            0           67        50          5

In [4]:
df.select_dtypes(include=['object']).columns

Index([], dtype='str')

In [6]:
df.head()

   o_ring_ct  distress_ct  temperature  pressure  launch_id
0          6            0           66        50          1
1          6            1           70        50          2
2          6            0           69        50          3
3          6            0           68        50          4
4          6            0           67        50          5

In [8]:
print(df.columns.tolist())
print(df.head())

['o_ring_ct', 'distress_ct', 'temperature', 'pressure', 'launch_id']
   o_ring_ct  distress_ct  temperature  pressure  launch_id
0          6            0           66        50          1
1          6            1           70        50          2
2          6            0           69        50          3
3          6            0           68        50          4
4          6            0           67        50          5

In [10]:
print(df.columns.tolist())

['o_ring_ct', 'distress_ct', 'temperature', 'pressure', 'launch_id']

In [11]:

df.head()

   o_ring_ct  distress_ct  temperature  pressure  launch_id
0          6            0           66        50          1
1          6            1           70        50          2
2          6            0           69        50          3
3          6            0           68        50          4
4          6            0           67        50          5

In [12]:
df.to_csv(
    "challenger_clustered.csv",
    index=False
)

print("Saved successfully")

Saved successfully