In [1]:
# =========================
# 1. Imports
# =========================
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# =========================
# 2. Load dataset
# =========================
df = pd.read_csv("cheesecake.csv")

# Preview
df.head()

,id,recipeName,rating,totalTimeInSeconds,course,cuisine,ingredients,dish
0,Pumpkin-Cheesecake-1375760,Pumpkin Cheesecake,4,6300.0,[Desserts],NaN,"[graham cracker crumbs, butter, sugar, cream c...",cheesecake
1,Lemon-Cheesecake-1375450,Lemon Cheesecake,3,22800.0,[Desserts],NaN,"[graham cracker crumbs, sugar, butter, Philade...",cheesecake
2,Fluffy-Cheesecake-1370555,Fluffy Cheesecake,4,9600.0,[Desserts],NaN,"[graham cracker crumbs, sugar, salted butter, ...",cheesecake
3,Pumpkin-Cookie-Butter-Cheesecake-1374346,Pumpkin Cookie Butter Cheesecake,4,4800.0,[Desserts],NaN,"[crust, cookies, brown sugar, melted butter, c...",cheesecake
4,Pumpkin-Cheesecake-1367107,Pumpkin Cheesecake,4,4500.0,[Desserts],NaN,"[graham cracker crumbs, brown sugar, ground ci...",cheesecake

In [3]:
# =========================
# 3. Check columns
# =========================
df.columns

Index(['id', 'recipeName', 'rating', 'totalTimeInSeconds', 'course', 'cuisine',
       'ingredients', 'dish'],
      dtype='str')

In [5]:
df = df.dropna()

In [7]:
df.columns = df.columns.str.strip().str.lower()

In [9]:
print(df.columns)   # must contain text column
print(df.head())

Index(['id', 'recipename', 'rating', 'totaltimeinseconds', 'course', 'cuisine',
       'ingredients', 'dish'],
      dtype='str')
                                        id                     recipename  \
108            Sopapilla-cheesecake-365506           Sopapilla Cheesecake
162           Sour-Cream-Cheesecake-461491          Sour Cream Cheesecake
186     Italian-Ricotta-Cheesecake-1360834     Italian Ricotta Cheesecake
192  Strawberry-Cheesecake-Eclairs-1366176  Strawberry Cheesecake Eclairs
245   Cookies-and-Cream-Cheesecakes-489985  Cookies and Cream Cheesecakes

     rating  totaltimeinseconds      course         cuisine  \
108       5              3600.0  [Desserts]       [Mexican]
162       4             43200.0  [Desserts]      [American]
186       3              4500.0  [Desserts]       [Italian]
192       4              5400.0  [Desserts]        [French]
245       4              2520.0  [Desserts]  [Kid-Friendly]

                                           ingredients        dish
108  [rolls, cream cheese, eggs, sugar, vanilla, ci...  cheesecake
162  [graham cracker crumbs, butter, sugar, eggs, c...  cheesecake
186  [unsalted butter, ricotta, sugar, large eggs, ...  cheesecake
192  [unsalted butter, granulated sugar, salt, all-...  cheesecake
245  [OREO® Cookies, cream cheese, granulated sugar...  cheesecake

In [11]:

df.head()

,id,recipename,rating,totaltimeinseconds,course,cuisine,ingredients,dish
108,Sopapilla-cheesecake-365506,Sopapilla Cheesecake,5,3600.0,[Desserts],[Mexican],"[rolls, cream cheese, eggs, sugar, vanilla, ci...",cheesecake
162,Sour-Cream-Cheesecake-461491,Sour Cream Cheesecake,4,43200.0,[Desserts],[American],"[graham cracker crumbs, butter, sugar, eggs, c...",cheesecake
186,Italian-Ricotta-Cheesecake-1360834,Italian Ricotta Cheesecake,3,4500.0,[Desserts],[Italian],"[unsalted butter, ricotta, sugar, large eggs, ...",cheesecake
192,Strawberry-Cheesecake-Eclairs-1366176,Strawberry Cheesecake Eclairs,4,5400.0,[Desserts],[French],"[unsalted butter, granulated sugar, salt, all-...",cheesecake
245,Cookies-and-Cream-Cheesecakes-489985,Cookies and Cream Cheesecakes,4,2520.0,[Desserts],[Kid-Friendly],"[OREO® Cookies, cream cheese, granulated sugar...",cheesecake

In [15]:
df.head()

,id,recipename,rating,totaltimeinseconds,course,cuisine,ingredients,dish
108,Sopapilla-cheesecake-365506,Sopapilla Cheesecake,5,3600.0,[Desserts],[Mexican],"[rolls, cream cheese, eggs, sugar, vanilla, ci...",cheesecake
162,Sour-Cream-Cheesecake-461491,Sour Cream Cheesecake,4,43200.0,[Desserts],[American],"[graham cracker crumbs, butter, sugar, eggs, c...",cheesecake
186,Italian-Ricotta-Cheesecake-1360834,Italian Ricotta Cheesecake,3,4500.0,[Desserts],[Italian],"[unsalted butter, ricotta, sugar, large eggs, ...",cheesecake
192,Strawberry-Cheesecake-Eclairs-1366176,Strawberry Cheesecake Eclairs,4,5400.0,[Desserts],[French],"[unsalted butter, granulated sugar, salt, all-...",cheesecake
245,Cookies-and-Cream-Cheesecakes-489985,Cookies and Cream Cheesecakes,4,2520.0,[Desserts],[Kid-Friendly],"[OREO® Cookies, cream cheese, granulated sugar...",cheesecake

In [17]:
print("X exists:", "X" in globals())
print("cluster column:", "cluster" in df.columns)

X exists: False
cluster column: False

In [18]:

df.to_csv("cheesecake_clustered.csv", index=False)