In [1]:
# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# =========================
# 2. Load Dataset
# =========================
df = pd.read_csv("Coca-Cola_stock_info.csv")

# Preview data
df.head()

                   Key                                              Value
0                  zip                                              30313
1               sector                                 Consumer Defensive
2    fullTimeEmployees                                              80300
3  longBusinessSummary  The Coca-Cola Company, a beverage company, man...
4                 city                                            Atlanta

In [3]:
# =========================
# 3. Data Preprocessing
# =========================

# Check missing values
print(df.isnull().sum())

# Drop missing rows (or you can use imputation)
df = df.dropna()

# Ensure column names are clean
df.columns = [col.strip() for col in df.columns]

df.head()

Key       0
Value    30
dtype: int64

                   Key                                              Value
0                  zip                                              30313
1               sector                                 Consumer Defensive
2    fullTimeEmployees                                              80300
3  longBusinessSummary  The Coca-Cola Company, a beverage company, man...
4                 city                                            Atlanta

In [17]:
df.head()

                   Key                                              Value
0                  zip                                              30313
1               sector                                 Consumer Defensive
2    fullTimeEmployees                                              80300
3  longBusinessSummary  The Coca-Cola Company, a beverage company, man...
4                 city                                            Atlanta

In [18]:
'y_test' in globals()

False

In [21]:
print(df.head())
print(df.head())

                   Key                                              Value
0                  zip                                              30313
1               sector                                 Consumer Defensive
2    fullTimeEmployees                                              80300
3  longBusinessSummary  The Coca-Cola Company, a beverage company, man...
4                 city                                            Atlanta
                   Key                                              Value
0                  zip                                              30313
1               sector                                 Consumer Defensive
2    fullTimeEmployees                                              80300
3  longBusinessSummary  The Coca-Cola Company, a beverage company, man...
4                 city                                            Atlanta

In [24]:
df.head()
df.columns

Index(['Key', 'Value'], dtype='str')