In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Visualization
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Download NLP resources
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("Consumer Complaints.csv")

# Display first rows
df.head()

                 Company  Bank account or service  Credit card  Mortgage
0        Bank of America                 0.166372     0.108174  0.191198
1  Wells Fargo & Company                 0.157200     0.043568  0.134481
2   JPMorgan Chase & Co.                 0.113752     0.117526  0.085409
3               Citibank                 0.035935     0.185351  0.040499
4            Capital One                 0.029145     0.153062  0.004443

In [3]:
df.columns

Index(['Company', 'Bank account or service', 'Credit card', 'Mortgage'], dtype='str')

In [5]:
print(df.columns)

Index(['Company', 'Bank account or service', 'Credit card', 'Mortgage'], dtype='str')

In [7]:
df.head()

                 Company  Bank account or service  Credit card  Mortgage
0        Bank of America                 0.166372     0.108174  0.191198
1  Wells Fargo & Company                 0.157200     0.043568  0.134481
2   JPMorgan Chase & Co.                 0.113752     0.117526  0.085409
3               Citibank                 0.035935     0.185351  0.040499
4            Capital One                 0.029145     0.153062  0.004443

In [8]:
print(df.columns.tolist())

['Company', 'Bank account or service', 'Credit card', 'Mortgage']

In [9]:
df.head()

                 Company  Bank account or service  Credit card  Mortgage
0        Bank of America                 0.166372     0.108174  0.191198
1  Wells Fargo & Company                 0.157200     0.043568  0.134481
2   JPMorgan Chase & Co.                 0.113752     0.117526  0.085409
3               Citibank                 0.035935     0.185351  0.040499
4            Capital One                 0.029145     0.153062  0.004443

In [10]:
df.columns

Index(['Company', 'Bank account or service', 'Credit card', 'Mortgage'], dtype='str')

In [13]:
dir()

['In',
 'KMeans',
 'Out',
 'PCA',
 'TfidfVectorizer',
 'WordNetLemmatizer',
 '_',
 '_1',
 '_10',
 '_2',
 '_3',
 '_7',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'clean_text',
 'df',
 'exit',
 'get_ipython',
 'lemmatizer',
 'nltk',
 'np',
 'open',
 'pd',
 'plt',
 'quit',
 're',
 'silhouette_score',
 'stop_words',
 'stopwords',
 'text_column']

In [14]:
results.to_csv(
    "Consumer_Complaints_KMeans_Clusters.csv",
    index=False
)

print("File saved successfully")

NameError: name 'results' is not defined