In [1]:
# Cell 1: Import libraries

import pandas as pd
import numpy as np

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler

# K-Means
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Visualisation
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [2]:
# Cell 2: Load dataset

df = pd.read_csv("date-started-by-county.csv")

# View data
df.head()

          County     started
0          Glenn  2023-10-01
1         Orange  2023-10-01
2      Riverside  2023-10-01
3      San Diego  2023-10-01
4  San Francisco  2023-10-01

In [3]:
# Cell 3: Inspect dataset

print(df.shape)
print(df.columns)

df.info()

(58, 2)
Index(['County', 'started'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   County   58 non-null     str
 1   started  58 non-null     str
dtypes: str(2)
memory usage: 2.0 KB

In [4]:
# Cell 4: Handle missing values

df = df.dropna()

# Check missing values
df.isnull().sum()

County     0
started    0
dtype: int64

In [6]:
df.head()

          County     started
0          Glenn  2023-10-01
1         Orange  2023-10-01
2      Riverside  2023-10-01
3      San Diego  2023-10-01
4  San Francisco  2023-10-01

In [7]:
# Cell 11: Save clustered dataset

df.to_csv(
    "county_kmeans_clusters.csv",
    index=False
)