In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Date_Corrections.csv")

# Preview
df.head()

                       Title NewAirDate
0  Let He Who Is Without Sin  11-Nov-96
1                     Basics  20-May-96
2                  Flashback  09-Nov-96
3                  The Chute  18-Sep-96
4              False Profits  02-Oct-96

In [3]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       22 non-null     str
 1   NewAirDate  22 non-null     str
dtypes: str(2)
memory usage: 928.0 bytes

Title         0
NewAirDate    0
dtype: int64

In [5]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['Title', 'NewAirDate'], dtype='str')

In [8]:
print(df.columns)

Index(['Title', 'NewAirDate'], dtype='str')

In [10]:
print(df.columns)

Index(['Title', 'NewAirDate'], dtype='str')

In [12]:
X = df.values

In [16]:
X = df.drop(columns=['Title'])

In [21]:
print(X.dtypes)

NewAirDate    str
dtype: object

In [23]:
print(df.columns)

Index(['Title', 'NewAirDate'], dtype='str')

In [25]:
df.head()
df.columns

Index(['Title', 'NewAirDate'], dtype='str')

In [28]:
df.head()
df.columns

Index(['Title', 'NewAirDate'], dtype='str')

In [32]:
df.columns
df.head()

                       Title NewAirDate
0  Let He Who Is Without Sin  11-Nov-96
1                     Basics  20-May-96
2                  Flashback  09-Nov-96
3                  The Chute  18-Sep-96
4              False Profits  02-Oct-96