In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("all_events_anonymized.csv")

df.head()

  humanitarian_id  client_id   visitdate visitplace
0             NaN     3913.0  2012-07-11   contract
1             NaN    12001.0  2012-09-04   contract
2             NaN     4422.0  2012-09-24   contract
3             NaN     4360.0  2012-10-01   contract
4             NaN     5270.0  2012-10-17   contract

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(127990, 4)
<class 'pandas.DataFrame'>
RangeIndex: 127990 entries, 0 to 127989
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   humanitarian_id  124193 non-null  str
 1   client_id        83286 non-null   float64
 2   visitdate        127988 non-null  str
 3   visitplace       127990 non-null  str
dtypes: float64(1), str(3)
memory usage: 7.4 MB
None
humanitarian_id     3797
client_id          44704
visitdate              2
visitplace             0
dtype: int64

In [5]:
print(df.columns.tolist())

['humanitarian_id', 'client_id', 'visitdate', 'visitplace']

In [7]:
print(df.columns.tolist())
print(df.head())

['humanitarian_id', 'client_id', 'visitdate', 'visitplace']
  humanitarian_id  client_id   visitdate visitplace
0             NaN     3913.0  2012-07-11   contract
1             NaN    12001.0  2012-09-04   contract
2             NaN     4422.0  2012-09-24   contract
3             NaN     4360.0  2012-10-01   contract
4             NaN     5270.0  2012-10-17   contract

In [9]:
print(df.columns.tolist())
print(df.head())

['humanitarian_id', 'client_id', 'visitdate', 'visitplace']
  humanitarian_id  client_id   visitdate visitplace
0             NaN     3913.0  2012-07-11   contract
1             NaN    12001.0  2012-09-04   contract
2             NaN     4422.0  2012-09-24   contract
3             NaN     4360.0  2012-10-01   contract
4             NaN     5270.0  2012-10-17   contract

In [13]:
print(df.head())

  humanitarian_id  client_id   visitdate visitplace
0             NaN     3913.0  2012-07-11   contract
1             NaN    12001.0  2012-09-04   contract
2             NaN     4422.0  2012-09-24   contract
3             NaN     4360.0  2012-10-01   contract
4             NaN     5270.0  2012-10-17   contract

In [15]:
df.head()

  humanitarian_id  client_id   visitdate visitplace
0             NaN     3913.0  2012-07-11   contract
1             NaN    12001.0  2012-09-04   contract
2             NaN     4422.0  2012-09-24   contract
3             NaN     4360.0  2012-10-01   contract
4             NaN     5270.0  2012-10-17   contract