In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("df_game_details_clean.csv")

df.head()

,Unnamed: 0,Title,Link,Categories,Publishers,Developers
0,0,A Plague Tale: Innocence,https://www.microsoft.com/en-us/store/p/a-plag...,"Action & adventure, Role playing",Focus Home Interactive,Focus Home Interactive
1,1,Age of Empires Definitive Edition,https://www.microsoft.com/en-us/store/p/age-of...,Strategy,Xbox Game Studios,Xbox Game Studios
2,2,Age of Empires II: Definitive Edition,https://www.microsoft.com/en-us/store/p/age-of...,Strategy,Xbox Game Studios,Xbox Game Studios
3,3,Age of Empires III: Definitive Edition,https://www.microsoft.com/en-us/store/p/age-of...,Strategy,Xbox Game Studios,Xbox Game Studios
4,4,Age of Wonders: Planetfall,https://www.microsoft.com/en-us/store/p/age-of...,"Simulation, Strategy",Paradox Interactive,Triumph Studios

In [4]:
text_col = "game_details"

if text_col in df.columns:
    df[text_col] = df[text_col].fillna("").astype(str)
    display(df[[text_col]].head())
else:
    print(f"Column '{text_col}' not found.")
    print("Available columns:", df.columns.tolist())

Column 'game_details' not found.
Available columns: ['Unnamed: 0', 'Title', 'Link', 'Categories', 'Publishers', 'Developers']

In [7]:
print(df.head())

   Unnamed: 0                                   Title  \
0           0                A Plague Tale: Innocence
1           1       Age of Empires Definitive Edition
2           2   Age of Empires II: Definitive Edition
3           3  Age of Empires III: Definitive Edition
4           4              Age of Wonders: Planetfall

                                                Link  \
0  https://www.microsoft.com/en-us/store/p/a-plag...
1  https://www.microsoft.com/en-us/store/p/age-of...
2  https://www.microsoft.com/en-us/store/p/age-of...
3  https://www.microsoft.com/en-us/store/p/age-of...
4  https://www.microsoft.com/en-us/store/p/age-of...

                         Categories              Publishers  \
0  Action & adventure, Role playing  Focus Home Interactive
1                          Strategy       Xbox Game Studios
2                          Strategy       Xbox Game Studios
3                          Strategy       Xbox Game Studios
4              Simulation, Strategy     Paradox Interactive

               Developers
0  Focus Home Interactive
1       Xbox Game Studios
2       Xbox Game Studios
3       Xbox Game Studios
4         Triumph Studios

In [9]:
text_col = "game_details"  # only if it actually exists

In [10]:

df.head()

,Unnamed: 0,Title,Link,Categories,Publishers,Developers
0,0,A Plague Tale: Innocence,https://www.microsoft.com/en-us/store/p/a-plag...,"Action & adventure, Role playing",Focus Home Interactive,Focus Home Interactive
1,1,Age of Empires Definitive Edition,https://www.microsoft.com/en-us/store/p/age-of...,Strategy,Xbox Game Studios,Xbox Game Studios
2,2,Age of Empires II: Definitive Edition,https://www.microsoft.com/en-us/store/p/age-of...,Strategy,Xbox Game Studios,Xbox Game Studios
3,3,Age of Empires III: Definitive Edition,https://www.microsoft.com/en-us/store/p/age-of...,Strategy,Xbox Game Studios,Xbox Game Studios
4,4,Age of Wonders: Planetfall,https://www.microsoft.com/en-us/store/p/age-of...,"Simulation, Strategy",Paradox Interactive,Triumph Studios

In [11]:
df.to_csv("df_game_details_clustered.csv", index=False)