In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import re

In [2]:
df = pd.read_csv("dialoganimations.2da.csv")
df.head()

  name  looping  fireforget  dialog  overlay  cu_pb_range
0  NaN        0           0       0        0          0.0
1  NaN        0           0       0        0          0.0
2  NaN        0           0       0        0          0.0
3  NaN        0           0       0        0          0.0
4  NaN        0           0       0        0          0.0

In [3]:
print(df.info())
print(df.columns)

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         31 non-null     str
 1   looping      227 non-null    int64
 2   fireforget   227 non-null    int64
 3   dialog       227 non-null    int64
 4   overlay      227 non-null    int64
 5   cu_pb_range  227 non-null    float64
dtypes: float64(1), int64(4), str(1)
memory usage: 11.1 KB
None
Index(['name', 'looping', 'fireforget', 'dialog', 'overlay', 'cu_pb_range'], dtype='str')

In [5]:

df.head()

  name  looping  fireforget  dialog  overlay  cu_pb_range
0  NaN        0           0       0        0          0.0
1  NaN        0           0       0        0          0.0
2  NaN        0           0       0        0          0.0
3  NaN        0           0       0        0          0.0
4  NaN        0           0       0        0          0.0

In [6]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [9]:
df.head()

  name  looping  fireforget  dialog  overlay  cu_pb_range
0  NaN        0           0       0        0          0.0
1  NaN        0           0       0        0          0.0
2  NaN        0           0       0        0          0.0
3  NaN        0           0       0        0          0.0
4  NaN        0           0       0        0          0.0

In [10]:
df.head()

  name  looping  fireforget  dialog  overlay  cu_pb_range
0  NaN        0           0       0        0          0.0
1  NaN        0           0       0        0          0.0
2  NaN        0           0       0        0          0.0
3  NaN        0           0       0        0          0.0
4  NaN        0           0       0        0          0.0

In [13]:
df.columns

Index(['name', 'looping', 'fireforget', 'dialog', 'overlay', 'cu_pb_range'], dtype='str')