In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Text vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

# K-means clustering
from sklearn.cluster import KMeans

# Evaluation and visualization
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

# Download NLP resources
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("dwguide.csv")

# Display first rows
df.head()

,episodenbr,title,weekday,broadcastdate,broadcasthour,duration,views,share,AI,chart,cast,crew,summary
0,601,The King's Demons: Part Two,Wed,16 Mar 1983,6:47pm,00:24:27,7.20m,NaN,63.0,66,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Terence Dudley""},{""r...",The Master and the Doctor fight for control ov...
1,602,The Five Doctors,Fri,25 Nov 1983,7:20pm,01:30:23,7.70m,NaN,75.0,54,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Terrance Dicks""},{""r...",NaN
2,603,Warriors of the Deep: Part One,Thu,5 Jan 1984,6:41pm,00:24:48,7.60m,NaN,65.0,51,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Johnny Byrne""},{""rol...",Seabase 4 is on alert as a strange craft appro...
3,604,Warriors of the Deep: Part Two,Fri,6 Jan 1984,6:41pm,00:24:04,7.50m,NaN,64.0,52,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Johnny Byrne""},{""rol...",The Silurians and Sea Devils send in the Myrka...
4,605,Warriors of the Deep: Part Three,Thu,12 Jan 1984,6:41pm,00:24:02,7.30m,NaN,62.0,74,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Johnny Byrne""},{""rol...",As Vorshak's crew are cut down by Sauvix's Sea...

In [4]:
print(df.columns)

Index(['episodenbr', 'title', 'weekday', 'broadcastdate', 'broadcasthour',
       'duration', 'views', 'share', 'AI', 'chart', 'cast', 'crew', 'summary'],
      dtype='str')

In [6]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [7]:
df.head()

,episodenbr,title,weekday,broadcastdate,broadcasthour,duration,views,share,AI,chart,cast,crew,summary
0,601,The King's Demons: Part Two,Wed,16 Mar 1983,6:47pm,00:24:27,7.20m,NaN,63.0,66,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Terence Dudley""},{""r...",The Master and the Doctor fight for control ov...
1,602,The Five Doctors,Fri,25 Nov 1983,7:20pm,01:30:23,7.70m,NaN,75.0,54,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Terrance Dicks""},{""r...",NaN
2,603,Warriors of the Deep: Part One,Thu,5 Jan 1984,6:41pm,00:24:48,7.60m,NaN,65.0,51,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Johnny Byrne""},{""rol...",Seabase 4 is on alert as a strange craft appro...
3,604,Warriors of the Deep: Part Two,Fri,6 Jan 1984,6:41pm,00:24:04,7.50m,NaN,64.0,52,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Johnny Byrne""},{""rol...",The Silurians and Sea Devils send in the Myrka...
4,605,Warriors of the Deep: Part Three,Thu,12 Jan 1984,6:41pm,00:24:02,7.30m,NaN,62.0,74,"[{""role"":""The Doctor"",""name"":""Peter Davison""},...","[{""role"":""Writer"",""name"":""Johnny Byrne""},{""rol...",As Vorshak's crew are cut down by Sauvix's Sea...

In [10]:
df.columns

Index(['episodenbr', 'title', 'weekday', 'broadcastdate', 'broadcasthour',
       'duration', 'views', 'share', 'AI', 'chart', 'cast', 'crew', 'summary'],
      dtype='str')

In [11]:
df.to_csv(
    "dwguide_kmeans_results.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!