In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

In [2]:
# Load dataset
df = pd.read_csv("elec.csv")

# Show first rows
df.head()

     period  nswprice  nswdemand  vicprice  vicdemand  transfer  class
0  0.000000  0.056443   0.439155  0.003467   0.422915  0.414912      1
1  0.021277  0.051699   0.415055  0.003467   0.422915  0.414912      1
2  0.042553  0.051489   0.385004  0.003467   0.422915  0.414912      1
3  0.063830  0.045485   0.314639  0.003467   0.422915  0.414912      1
4  0.085106  0.042482   0.251116  0.003467   0.422915  0.414912      0

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 45312 entries, 0 to 45311
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   period     45312 non-null  float64
 1   nswprice   45312 non-null  float64
 2   nswdemand  45312 non-null  float64
 3   vicprice   45312 non-null  float64
 4   vicdemand  45312 non-null  float64
 5   transfer   45312 non-null  float64
 6   class      45312 non-null  int64
dtypes: float64(6), int64(1)
memory usage: 2.4 MB

period       0
nswprice     0
nswdemand    0
vicprice     0
vicdemand    0
transfer     0
class        0
dtype: int64

In [4]:
# Simple strategy: drop missing rows (or use imputation if needed)
df = df.dropna()

In [6]:
df.columns = df.columns.str.strip()dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt))

In [8]:
df.head()

     period  nswprice  nswdemand  vicprice  vicdemand  transfer  class
0  0.000000  0.056443   0.439155  0.003467   0.422915  0.414912      1
1  0.021277  0.051699   0.415055  0.003467   0.422915  0.414912      1
2  0.042553  0.051489   0.385004  0.003467   0.422915  0.414912      1
3  0.063830  0.045485   0.314639  0.003467   0.422915  0.414912      1
4  0.085106  0.042482   0.251116  0.003467   0.422915  0.414912      0