In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("presidentialElections.csv")

df.head()

        state  demVote  year  south
0     Alabama    84.76  1932   True
1     Arizona    67.03  1932  False
2    Arkansas    86.27  1932   True
3  California    58.41  1932  False
4    Colorado    54.81  1932  False

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

(1097, 4)
<class 'pandas.DataFrame'>
RangeIndex: 1097 entries, 0 to 1096
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   state    1097 non-null   str
 1   demVote  1097 non-null   float64
 2   year     1097 non-null   int64
 3   south    1097 non-null   bool
dtypes: bool(1), float64(1), int64(1), str(1)
memory usage: 35.9 KB
None
           demVote         year
count  1097.000000  1097.000000
mean     48.359398  1974.581586
std      12.651882    25.258101
min      10.090000  1932.000000
25%      40.180000  1952.000000
50%      47.090000  1976.000000
75%      54.410000  1996.000000
max      98.570000  2016.000000

In [4]:
df = df.dropna()  # or use fillna depending on dataset

In [5]:
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

In [7]:
print(df.columns)

Index(['state', 'demVote', 'year', 'south'], dtype='str')

In [9]:
df.head()

        state  demVote  year  south
0     Alabama    84.76  1932   True
1     Arizona    67.03  1932  False
2    Arkansas    86.27  1932   True
3  California    58.41  1932  False
4    Colorado    54.81  1932  False

In [12]:
df.columns

Index(['state', 'demVote', 'year', 'south'], dtype='str')

In [14]:
df.head()

        state  demVote  year  south
0     Alabama    84.76  1932   True
1     Arizona    67.03  1932  False
2    Arkansas    86.27  1932   True
3  California    58.41  1932  False
4    Colorado    54.81  1932  False

In [16]:
print("X_train exists:", "X_train" in globals())
print("y_test exists:", "y_test" in globals())
print("dt_pred exists:", "dt_pred" in globals())
print("rf_pred exists:", "rf_pred" in globals())

X_train exists: False
y_test exists: False
dt_pred exists: False
rf_pred exists: False