In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load CSV file

df = pd.read_csv("Emissions Data.csv")

# Display first rows
df.head()

   Year  Country      Continent   Emission
0  2008    Aruba  South America  24.750133
1  2009    Aruba  South America  24.876706
2  2010    Aruba  South America  24.182702
3  2011    Aruba  South America  23.922412
4  2008  Andorra         Europe   6.296125

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 788 entries, 0 to 787
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Year       788 non-null    int64
 1   Country    788 non-null    str
 2   Continent  788 non-null    str
 3   Emission   788 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 36.9 KB

In [4]:

df.head()

   Year  Country      Continent   Emission
0  2008    Aruba  South America  24.750133
1  2009    Aruba  South America  24.876706
2  2010    Aruba  South America  24.182702
3  2011    Aruba  South America  23.922412
4  2008  Andorra         Europe   6.296125

In [5]:
df.columns

Index(['Year', 'Country', 'Continent', 'Emission'], dtype='str')

In [6]:
df.combine

<bound method DataFrame.combine of      Year   Country      Continent   Emission
0    2008     Aruba  South America  24.750133
1    2009     Aruba  South America  24.876706
2    2010     Aruba  South America  24.182702
3    2011     Aruba  South America  23.922412
4    2008   Andorra         Europe   6.296125
..    ...       ...            ...        ...
783  2011    Zambia         Africa   0.212450
784  2008  Zimbabwe         Africa   0.569255
785  2009  Zimbabwe         Africa   0.600521
786  2010  Zimbabwe         Africa   0.646073
787  2011  Zimbabwe         Africa   0.691698

[788 rows x 4 columns]>

In [7]:
df.compare

<bound method DataFrame.compare of      Year   Country      Continent   Emission
0    2008     Aruba  South America  24.750133
1    2009     Aruba  South America  24.876706
2    2010     Aruba  South America  24.182702
3    2011     Aruba  South America  23.922412
4    2008   Andorra         Europe   6.296125
..    ...       ...            ...        ...
783  2011    Zambia         Africa   0.212450
784  2008  Zimbabwe         Africa   0.569255
785  2009  Zimbabwe         Africa   0.600521
786  2010  Zimbabwe         Africa   0.646073
787  2011  Zimbabwe         Africa   0.691698

[788 rows x 4 columns]>

In [8]:
df.to_csv(
    "Emission_Data_KMeans_Results.csv",
    index=False
)

print("File saved successfully")

File saved successfully