In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Employee data.csv")

df.head()

    id  gender       bdate  educ  ... salbegin  jobtime  prevexp  minority
0  1.0    Male  1952-02-03    15  ...  27000.0     98.0    144.0        No
1  2.0    Male  1958-05-23    16  ...  18750.0     98.0     36.0        No
2  3.0  Female  1929-07-26    12  ...  12000.0     98.0    381.0        No
3  4.0  Female  1947-04-15     8  ...  13200.0     98.0    190.0        No
4  5.0    Male  1955-02-09    15  ...  21000.0     98.0    138.0        No

[5 rows x 10 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(474, 10)
<class 'pandas.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        474 non-null    float64
 1   gender    474 non-null    str
 2   bdate     473 non-null    str
 3   educ      474 non-null    int64
 4   jobcat    474 non-null    str
 5   salary    474 non-null    float64
 6   salbegin  474 non-null    float64
 7   jobtime   474 non-null    float64
 8   prevexp   474 non-null    str
 9   minority  474 non-null    str
dtypes: float64(4), int64(1), str(5)
memory usage: 50.8 KB
None
id          0
gender      0
bdate       1
educ        0
jobcat      0
salary      0
salbegin    0
jobtime     0
prevexp     0
minority    0
dtype: int64

In [5]:
print(df.isna().sum())

id          0
gender      0
bdate       1
educ        0
jobcat      0
salary      0
salbegin    0
jobtime     0
prevexp     0
minority    0
dtype: int64

In [6]:
df.head()

    id  gender       bdate  educ  ... salbegin  jobtime  prevexp  minority
0  1.0    Male  1952-02-03    15  ...  27000.0     98.0    144.0        No
1  2.0    Male  1958-05-23    16  ...  18750.0     98.0     36.0        No
2  3.0  Female  1929-07-26    12  ...  12000.0     98.0    381.0        No
3  4.0  Female  1947-04-15     8  ...  13200.0     98.0    190.0        No
4  5.0    Male  1955-02-09    15  ...  21000.0     98.0    138.0        No

[5 rows x 10 columns]

In [8]:
df.head()
print(df.columns)

Index(['id', 'gender', 'bdate', 'educ', 'jobcat', 'salary', 'salbegin',
       'jobtime', 'prevexp', 'minority'],
      dtype='str')

In [11]:
print(df.columns.tolist())

['id', 'gender', 'bdate', 'educ', 'jobcat', 'salary', 'salbegin', 'jobtime', 'prevexp', 'minority']

In [13]:
df.columns
df.head()

    id  gender       bdate  educ  ... salbegin  jobtime  prevexp  minority
0  1.0    Male  1952-02-03    15  ...  27000.0     98.0    144.0        No
1  2.0    Male  1958-05-23    16  ...  18750.0     98.0     36.0        No
2  3.0  Female  1929-07-26    12  ...  12000.0     98.0    381.0        No
3  4.0  Female  1947-04-15     8  ...  13200.0     98.0    190.0        No
4  5.0    Male  1955-02-09    15  ...  21000.0     98.0    138.0        No

[5 rows x 10 columns]

In [15]:
df.head()

    id  gender       bdate  educ  ... salbegin  jobtime  prevexp  minority
0  1.0    Male  1952-02-03    15  ...  27000.0     98.0    144.0        No
1  2.0    Male  1958-05-23    16  ...  18750.0     98.0     36.0        No
2  3.0  Female  1929-07-26    12  ...  12000.0     98.0    381.0        No
3  4.0  Female  1947-04-15     8  ...  13200.0     98.0    190.0        No
4  5.0    Male  1955-02-09    15  ...  21000.0     98.0    138.0        No

[5 rows x 10 columns]