In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("england-metropolitan-counties.csv")
df.head()

  ons_code   gss_code  ... district_population  region_gss_code
0       2A  E11000001  ...             2573200        E12000002
1       2B  E11000002  ...             1365000        E12000002
2       2C  E11000003  ...             1290000        E12000003
3       2D  E11000004  ...             1089400        E12000001
4       2E  E11000005  ...             2591300        E12000005

[5 rows x 6 columns]

In [3]:
print(df.columns)

Index(['ons_code', 'gss_code', 'district_name', 'borough_count',
       'district_population', 'region_gss_code'],
      dtype='str')

In [4]:
# Try to auto-detect a text column
text_column = None

for col in df.columns:
    if df[col].dtype == "object":
        text_column = col
        break

print("Using text column:", text_column)

Using text column: None

In [8]:
print(df[text_column].head())
print(df[text_column].isna().sum())

0    2A
1    2B
2    2C
3    2D
4    2E
Name: ons_code, dtype: str
0

In [10]:
df.columns = df.columns.str.strip()

In [14]:
df.head()
df.columns

Index(['ons_code', 'gss_code', 'district_name', 'borough_count',
       'district_population', 'region_gss_code'],
      dtype='str')

In [16]:

df.head()

  ons_code   gss_code  ... district_population  region_gss_code
0       2A  E11000001  ...             2573200        E12000002
1       2B  E11000002  ...             1365000        E12000002
2       2C  E11000003  ...             1290000        E12000003
3       2D  E11000004  ...             1089400        E12000001
4       2E  E11000005  ...             2591300        E12000005

[5 rows x 6 columns]

In [19]:
print(df.columns)

Index(['ons_code', 'gss_code', 'district_name', 'borough_count',
       'district_population', 'region_gss_code'],
      dtype='str')

In [22]:
print(type(X))
print(X[:5] if hasattr(X, "__getitem__") else X)

<class 'numpy.ndarray'>
[['2A' 'E11000001' 'Greater Manchester' 10 2573200 'E12000002']
 ['2B' 'E11000002' 'Merseyside' 5 1365000 'E12000002']
 ['2C' 'E11000003' 'South Yorkshire' 4 1290000 'E12000003']
 ['2D' 'E11000004' 'Tyne and Wear' 5 1089400 'E12000001']
 ['2E' 'E11000005' 'West Midlands' 7 2591300 'E12000005']]

In [24]:
hasattr(vectorizer, "vocabulary_")

False