In [1]:
import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
df = pd.read_csv("all-detailsepisodes.csv")

# Show dataset information
df.head()

  episodeid                    title first_diffusion  doctorid
0       4-3  The Power of the Daleks     5 Nov, 1966         2
1       4-4          The Highlanders    17 Dec, 1966         2
2       4-5    The Underwater Menace    Jan 14, 1967         2
3       4-6             The Moonbase    11 Feb, 1967         2
4       4-7         The Macra Terror    11 Mar, 1967         2

In [5]:
print(df.columns.tolist())

['episodeid', 'title', 'first_diffusion', 'doctorid']

In [7]:


df.head()

  episodeid                    title first_diffusion  doctorid
0       4-3  The Power of the Daleks     5 Nov, 1966         2
1       4-4          The Highlanders    17 Dec, 1966         2
2       4-5    The Underwater Menace    Jan 14, 1967         2
3       4-6             The Moonbase    11 Feb, 1967         2
4       4-7         The Macra Terror    11 Mar, 1967         2

In [10]:
df.columns.tolist()

['episodeid', 'title', 'first_diffusion', 'doctorid']

In [11]:
df.to_csv(
    "episodes_kmeans_clusters.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!