In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("forecasts_12m_ahead.csv")

df.head()

                               Store_ID  month_63  ...       75%       max
0  3cdfe9e4-eb23-4217-9994-0d25b751b26e -0.211377  ...  0.251655  0.302803
1  7ed52546-94f0-4ec3-8e01-0c7903a0860c -0.453663  ...  0.138666  0.405656
2  4e228000-3567-4633-9978-69380b544e55  0.529189  ...  0.560336  0.701183
3  cd5ec446-5a0d-4a15-95c3-6e9d4a7939bc -0.023547  ...  0.319877  0.377476
4  095012c8-46b8-4567-956f-cd55ba18367c -0.542186  ...  0.223241  0.320484

[5 rows x 20 columns]

In [3]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Store_ID  15000 non-null  str
 1   month_63  15000 non-null  float64
 2   month_64  15000 non-null  float64
 3   month_65  15000 non-null  float64
 4   month_66  15000 non-null  float64
 5   month_67  15000 non-null  float64
 6   month_68  15000 non-null  float64
 7   month_69  15000 non-null  float64
 8   month_70  15000 non-null  float64
 9   month_71  15000 non-null  float64
 10  month_72  15000 non-null  float64
 11  month_73  15000 non-null  float64
 12  month_74  15000 non-null  float64
 13  mean      15000 non-null  float64
 14  std       15000 non-null  float64
 15  min       15000 non-null  float64
 16  25%       15000 non-null  float64
 17  50%       15000 non-null  float64
 18  75%       15000 non-null  float64
 19  max       15000 non-null  float64
dtypes: float64(19), str(1)
memory usage: 2.8 MB
None
           month_63      month_64  ...           75%           max
count  15000.000000  15000.000000  ...  15000.000000  15000.000000
mean       0.031285      0.022992  ...      0.203731      0.370863
std        0.384412      0.382398  ...      0.267987      0.221438
min       -0.796152     -0.885845  ...     -0.547977     -0.393944
25%       -0.292548     -0.298054  ...     -0.032836      0.227729
50%        0.058311      0.043085  ...      0.259164      0.397164
75%        0.349564      0.340342  ...      0.419228      0.537171
max        0.801940      0.835712  ...      0.835073      1.005843

[8 rows x 19 columns]
Store_ID    0
month_63    0
month_64    0
month_65    0
month_66    0
month_67    0
month_68    0
month_69    0
month_70    0
month_71    0
month_72    0
month_73    0
month_74    0
mean        0
std         0
min         0
25%         0
50%         0
75%         0
max         0
dtype: int64

In [4]:
df = df.dropna()  # simple baseline approach

In [6]:
[col for col in df.columns if 'date' in col.lower()]

[]

In [8]:
df.columns.tolist()

['Store_ID',
 'month_63',
 'month_64',
 'month_65',
 'month_66',
 'month_67',
 'month_68',
 'month_69',
 'month_70',
 'month_71',
 'month_72',
 'month_73',
 'month_74',
 'mean',
 'std',
 'min',
 '25%',
 '50%',
 '75%',
 'max']

In [10]:
print(df.head())
print(df.columns)
print(df.info())

                               Store_ID  month_63  ...       75%       max
0  3cdfe9e4-eb23-4217-9994-0d25b751b26e -0.211377  ...  0.251655  0.302803
1  7ed52546-94f0-4ec3-8e01-0c7903a0860c -0.453663  ...  0.138666  0.405656
2  4e228000-3567-4633-9978-69380b544e55  0.529189  ...  0.560336  0.701183
3  cd5ec446-5a0d-4a15-95c3-6e9d4a7939bc -0.023547  ...  0.319877  0.377476
4  095012c8-46b8-4567-956f-cd55ba18367c -0.542186  ...  0.223241  0.320484

[5 rows x 20 columns]
Index(['Store_ID', 'month_63', 'month_64', 'month_65', 'month_66', 'month_67',
       'month_68', 'month_69', 'month_70', 'month_71', 'month_72', 'month_73',
       'month_74', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Store_ID  15000 non-null  str
 1   month_63  15000 non-null  float64
 2   month_64  15000 non-null  float64
 3   month_65  15000 non-null  float64
 4   month_66  15000 non-null  float64
 5   month_67  15000 non-null  float64
 6   month_68  15000 non-null  float64
 7   month_69  15000 non-null  float64
 8   month_70  15000 non-null  float64
 9   month_71  15000 non-null  float64
 10  month_72  15000 non-null  float64
 11  month_73  15000 non-null  float64
 12  month_74  15000 non-null  float64
 13  mean      15000 non-null  float64
 14  std       15000 non-null  float64
 15  min       15000 non-null  float64
 16  25%       15000 non-null  float64
 17  50%       15000 non-null  float64
 18  75%       15000 non-null  float64
 19  max       15000 non-null  float64
dtypes: float64(19), str(1)
memory usage: 2.8 MB
None

In [12]:
print(df.columns)

Index(['Store_ID', 'month_63', 'month_64', 'month_65', 'month_66', 'month_67',
       'month_68', 'month_69', 'month_70', 'month_71', 'month_72', 'month_73',
       'month_74', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'],
      dtype='str')

In [15]:
print("X exists:", "X" in globals())
print("y exists:", "y" in globals())

X exists: False
y exists: False

In [16]:
def evaluate_model(y_true, y_pred, model_name):
    print(f"\n📊 {model_name}")
    print("MAE:", mean_absolute_error(y_true, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_true, y_pred)))
    print("R²:", r2_score(y_true, y_pred))

In [20]:
'y_test' in globals()

False

In [22]:
df.head()

                               Store_ID  month_63  ...       75%       max
0  3cdfe9e4-eb23-4217-9994-0d25b751b26e -0.211377  ...  0.251655  0.302803
1  7ed52546-94f0-4ec3-8e01-0c7903a0860c -0.453663  ...  0.138666  0.405656
2  4e228000-3567-4633-9978-69380b544e55  0.529189  ...  0.560336  0.701183
3  cd5ec446-5a0d-4a15-95c3-6e9d4a7939bc -0.023547  ...  0.319877  0.377476
4  095012c8-46b8-4567-956f-cd55ba18367c -0.542186  ...  0.223241  0.320484

[5 rows x 20 columns]