In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# K-means clustering
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans as TextKMeans

# Metrics
from sklearn.metrics import silhouette_score

In [2]:
# Load dataset
df = pd.read_csv("FuelEconomy.csv")

# Display first rows
df.head()

   Horsepower  Fuel Economy
0         119            30
1         177            25
2         220            24
3         188            24
4         219            24

In [3]:
features = [
    "Engine Displacement",
    "Cylinders",
    "Fuel Economy City",
    "Fuel Economy Highway",
    "Fuel Economy Combined"
]

# Keep available columns only
features = [x for x in features if x in df.columns]

X = df[features]

X.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [6]:
df.head()

   Horsepower  Fuel Economy
0         119            30
1         177            25
2         220            24
3         188            24
4         219            24

In [8]:
print(locals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'plt', 'sns', 'KMeans', 'StandardScaler', 'PCA', 'TfidfVectorizer', 'TextKMeans', 'silhouette_score', '_i2', 'df', '_2', '_i3', 'features', 'X', '_3', '_i4', 'scaler', '_i5', 'inertia', 'k', 'kmeans', '_i6', '_6', '_i7', '_i8'])

In [10]:
df.columns

Index(['Horsepower', 'Fuel Economy'], dtype='str')

In [11]:
df.columns

Index(['Horsepower', 'Fuel Economy'], dtype='str')

In [13]:
df.columns.tolist()

['Horsepower', 'Fuel Economy']

In [14]:
print(df.columns)

Index(['Horsepower', 'Fuel Economy'], dtype='str')