In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("fullers.csv")

In [3]:
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())

      site      lat       lng       zip  ...    address phone  email  web
0  fullers  51.5682 -0.052851    E5 9HG  ...     London   NaN    NaN  NaN
1  fullers  51.4606 -0.304164   TW9 1JL  ...   Richmond   NaN    NaN  NaN
2  fullers  51.8111 -0.806535  HP21 7SZ  ...  Aylesbury   NaN    NaN  NaN
3  fullers  51.3657 -2.610800  BS40 8PR  ...    Bristol   NaN    NaN  NaN
4  fullers  51.9312 -1.276190  OX25 5LB  ...   Bicester   NaN    NaN  NaN

[5 rows x 9 columns]
<class 'pandas.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   site     338 non-null    str
 1   lat      338 non-null    float64
 2   lng      338 non-null    float64
 3   zip      338 non-null    str
 4   name     338 non-null    str
 5   address  336 non-null    str
 6   phone    0 non-null      float64
 7   email    0 non-null      float64
 8   web      0 non-null      float64
dtypes: float64(5), str(4)
memory usage: 37.1 KB
None
              lat         lng  phone  email  web
count  338.000000  338.000000    0.0    0.0  0.0
mean    51.346014   -0.638844    NaN    NaN  NaN
std      0.329468    0.573358    NaN    NaN  NaN
min     50.666400   -2.781730    NaN    NaN  NaN
25%     51.061225   -0.994209    NaN    NaN  NaN
50%     51.468850   -0.412570    NaN    NaN  NaN
75%     51.512375   -0.177720    NaN    NaN  NaN
max     52.481900    0.258220    NaN    NaN  NaN
site         0
lat          0
lng          0
zip          0
name         0
address      2
phone      338
email      338
web        338
dtype: int64

In [6]:
df.select_dtypes(include=["object", "string"])

        site       zip               name        address
0    fullers    E5 9HG  The Anchor & Hope         London
1    fullers   TW9 1JL  The Angel & Crown       Richmond
2    fullers  HP21 7SZ     The Aristocrat      Aylesbury
3    fullers  BS40 8PR    The Bear & Swan        Bristol
4    fullers  OX25 5LB     The Barley Mow       Bicester
..       ...       ...                ...            ...
333  fullers  BS20 6JZ   The Windmill Inn     Portishead
334  fullers   SE1 8LW       The Windmill         London
335  fullers   PO7 5LJ        The Woodman  Waterlooville
336  fullers  SO23 9PE   The Wykeham Arms     Winchester
337  fullers  EC1N 6SJ      Ye Olde Mitre         London

[338 rows x 4 columns]

In [8]:
for col in df.select_dtypes(include=['object', 'string']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [10]:
print(df.columns)

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [13]:
df.head()

   site      lat       lng  zip  name  address  phone  email  web
0     0  51.5682 -0.052851   40    13       70    NaN    NaN  NaN
1     0  51.4606 -0.304164  286    14       91    NaN    NaN  NaN
2     0  51.8111 -0.806535   88    17        6    NaN    NaN  NaN
3     0  51.3657 -2.610800   28    29       19    NaN    NaN  NaN
4     0  51.9312 -1.276190  129    22       11    NaN    NaN  NaN

In [16]:
print(df.head())
print(df.columns)

   site      lat       lng  zip  name  address  phone  email  web
0     0  51.5682 -0.052851   40    13       70    NaN    NaN  NaN
1     0  51.4606 -0.304164  286    14       91    NaN    NaN  NaN
2     0  51.8111 -0.806535   88    17        6    NaN    NaN  NaN
3     0  51.3657 -2.610800   28    29       19    NaN    NaN  NaN
4     0  51.9312 -1.276190  129    22       11    NaN    NaN  NaN
Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [21]:
df.columns

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')