In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP libraries
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Visualisation
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Download NLP resources
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file

df = pd.read_csv("halftime_musicians.csv")

# Display first rows
df.head()

   super_bowl                               musician  num_songs
0          52                      Justin Timberlake       11.0
1          52  University of Minnesota Marching Band        1.0
2          51                              Lady Gaga        7.0
3          50                               Coldplay        6.0
4          50                                Beyoncé        3.0

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   super_bowl  134 non-null    int64
 1   musician    134 non-null    str
 2   num_songs   88 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 5.7 KB

In [5]:

df.head()

   super_bowl                               musician  num_songs
0          52                      Justin Timberlake       11.0
1          52  University of Minnesota Marching Band        1.0
2          51                              Lady Gaga        7.0
3          50                               Coldplay        6.0
4          50                                Beyoncé        3.0

In [6]:
df.columns

Index(['super_bowl', 'musician', 'num_songs'], dtype='str')

In [8]:
df.head()

   super_bowl                               musician  num_songs
0          52                      Justin Timberlake       11.0
1          52  University of Minnesota Marching Band        1.0
2          51                              Lady Gaga        7.0
3          50                               Coldplay        6.0
4          50                                Beyoncé        3.0

In [9]:
df.to_csv(
    "halftime_musicians_kmeans_clusters.csv",
    index=False
)