In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import warnings
warnings.filterwarnings("ignore")

# Download NLP resources
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load dataset

df = pd.read_csv("HamiltonGDP.csv")

# Display first rows

df.head()

         date  Series.1
0  1952-07-01  0.606065
1  1952-10-01  2.189314
2  1953-01-01  1.763820
3  1953-04-01  0.473010
4  1953-07-01 -0.437458

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      130 non-null    str
 1   Series.1  130 non-null    float64
dtypes: float64(1), str(1)
memory usage: 3.4 KB

In [4]:
# Check missing values

df.isnull().sum()

date        0
Series.1    0
dtype: int64

In [5]:
# Statistical summary

df.describe()

         Series.1
count  130.000000
mean     0.735512
std      1.030436
min     -2.596860
25%      0.140350
50%      0.754648
75%      1.433050
max      3.156944

In [7]:
for col in df.columns:
    print(col, df[col].dtype)

date str
Series.1 float64

In [8]:
# Identify columns

text_columns = df.select_dtypes(include=['object']).columns
numeric_columns = df.select_dtypes(include=np.number).columns

print("Text Columns:")
print(text_columns)

print("\nNumeric Columns:")
print(numeric_columns)

Text Columns:
Index(['date'], dtype='str')

Numeric Columns:
Index(['Series.1'], dtype='str')

In [9]:
if len(text_columns) > 0:
    
    df["combined_text"] = df[text_columns].astype(str).apply(
        lambda x: " ".join(x),
        axis=1
    )

else:
    df["combined_text"] = ""

In [11]:
df.head()

         date  Series.1 combined_text
0  1952-07-01  0.606065    1952-07-01
1  1952-10-01  2.189314    1952-10-01
2  1953-01-01  1.763820    1953-01-01
3  1953-04-01  0.473010    1953-04-01
4  1953-07-01 -0.437458    1953-07-01

In [12]:
df.to_csv(
    "HamiltonGDP_KMeans_NLP_results.csv",
    index=False
)

print("Saved Successfully!")

Saved Successfully!