In [1]:
import pandas as pd

df = pd.read_csv("ImageInfo.csv")
df.head()

,Recipe_id,totalNumOfStep,FileName,Step_num,Nper,Category_num,SubsetNum,ImgLink
0,7003883,8,7003883_6,6,0.778,10,3,https://res.hoto.cn/5b3350510135db7c7ffdb672.j...
1,7003884,17,7003884_0,0,0.056,14,1,https://res.hoto.cn/5b334f690135db7c7ffdb643.j...
2,7003884,17,7003884_11,11,0.667,14,3,https://res.hoto.cn/5b334f6c0135db7c7ffdb64e.j...
3,7003884,17,7003884_12,12,0.722,13,3,https://res.hoto.cn/5b334f6c0135db7c7ffdb64f.j...
4,7003884,17,7003884_14,14,0.833,10,3,https://res.hoto.cn/5b334f680135db7c7ffdb642.j...

In [2]:
df.info()
df.isnull().sum()

df = df.dropna()

<class 'pandas.DataFrame'>
RangeIndex: 37056 entries, 0 to 37055
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Recipe_id       37056 non-null  int64
 1   totalNumOfStep  37056 non-null  int64
 2   FileName        37056 non-null  str
 3   Step_num        37056 non-null  int64
 4   Nper            37056 non-null  float64
 5   Category_num    37056 non-null  int64
 6   SubsetNum       37056 non-null  int64
 7   ImgLink         36994 non-null  str
dtypes: float64(1), int64(5), str(2)
memory usage: 4.6 MB

In [4]:
df.head()

,Recipe_id,totalNumOfStep,FileName,Step_num,Nper,Category_num,SubsetNum,ImgLink
0,7003883,8,7003883_6,6,0.778,10,3,https://res.hoto.cn/5b3350510135db7c7ffdb672.j...
1,7003884,17,7003884_0,0,0.056,14,1,https://res.hoto.cn/5b334f690135db7c7ffdb643.j...
2,7003884,17,7003884_11,11,0.667,14,3,https://res.hoto.cn/5b334f6c0135db7c7ffdb64e.j...
3,7003884,17,7003884_12,12,0.722,13,3,https://res.hoto.cn/5b334f6c0135db7c7ffdb64f.j...
4,7003884,17,7003884_14,14,0.833,10,3,https://res.hoto.cn/5b334f680135db7c7ffdb642.j...

In [6]:
df.columns

Index(['Recipe_id', 'totalNumOfStep', 'FileName', 'Step_num', 'Nper',
       'Category_num', 'SubsetNum', 'ImgLink'],
      dtype='str')

In [8]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'df', '_1', '_i2', '_i3', 're', 'nltk', 'stopwords', 'word_tokenize', 'stop_words', 'clean_text', '_i4', '_4', '_i5', 'KMeans', 'kmeans', '_i6', '_6', '_i7', 'PCA', 'plt', 'pca', '_i8'])