In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("imdb.csv")

df.head()

   Movie ID                              Movie Name  Year
0         8  Edison Kinetoscopic Record of a Sneeze  1894
1        91                     Le manoir du diable  1896
2       417                  Le voyage dans la lune  1902
3       628                        The  s of Dollie  1908
4       833                      The Country Doctor  1909

In [4]:
df = df.dropna()

In [6]:
for col in df.columns:
    print(repr(col))

'Movie ID'
' Movie Name'
' Year'

In [9]:
for col in df.columns:
    print(repr(col))

'Movie ID'
' Movie Name'
' Year'

In [12]:
print(df.head())
print(df.columns)

   Movie ID                              Movie Name  Year
0         8  Edison Kinetoscopic Record of a Sneeze  1894
1        91                     Le manoir du diable  1896
2       417                  Le voyage dans la lune  1902
3       628                        The  s of Dollie  1908
4       833                      The Country Doctor  1909
Index(['Movie ID', ' Movie Name', ' Year'], dtype='str')

In [14]:
print([var for var in globals().keys() if "X_train" in var])

[]

In [17]:
print(df.columns)
print(df.head())

Index(['Movie ID', ' Movie Name', ' Year'], dtype='str')
   Movie ID                              Movie Name  Year
0         8  Edison Kinetoscopic Record of a Sneeze  1894
1        91                     Le manoir du diable  1896
2       417                  Le voyage dans la lune  1902
3       628                        The  s of Dollie  1908
4       833                      The Country Doctor  1909

In [22]:
print("X exists:", "X" in globals())
print("y exists:", "y" in globals())
print("X_train exists:", "X_train" in globals())
print("y_test exists:", "y_test" in globals())

X exists: False
y exists: False
X_train exists: False
y_test exists: False

In [28]:
df.head()

   Movie ID                              Movie Name  Year
0         8  Edison Kinetoscopic Record of a Sneeze  1894
1        91                     Le manoir du diable  1896
2       417                  Le voyage dans la lune  1902
3       628                        The  s of Dollie  1908
4       833                      The Country Doctor  1909