In [1]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("income.csv")

df.head()

   ID  Income  Age  Education  Gender
0   1     113   69         12       1
1   2      91   52         18       0
2   3     121   65         14       0
3   4      81   58         12       0
4   5      68   31         16       1

In [3]:
# Check missing values
print(df.isnull().sum())

# Fill missing values (simple approach)
df = df.fillna("")

ID           0
Income       0
Age          0
Education    0
Gender       0
dtype: int64

In [4]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
text_cols = df.select_dtypes(include=['object']).columns.tolist()

print("Numeric Columns:", numeric_cols)
print("Text Columns:", text_cols)

Numeric Columns: ['ID', 'Income', 'Age', 'Education', 'Gender']
Text Columns: []

In [5]:
scaler = StandardScaler()
X_numeric = scaler.fit_transform(df[numeric_cols])

In [7]:
print("Shape:", df.shape)
print("Text columns:", text_cols)

df["combined_text"] = (
    df[text_cols]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

print(df["combined_text"].head())
print(df["combined_text"].str.len().describe())

Shape: (1500, 6)
Text columns: []
0
1
2
3
4
Name: combined_text, dtype: str
count    1500.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: combined_text, dtype: float64

In [9]:
print(text_cols)
print(df[text_cols].head())
print(df[text_cols].isna().sum())

[]
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]
Series([], dtype: float64)

In [10]:
df.head()

   ID  Income  Age  Education  Gender combined_text
0   1     113   69         12       1
1   2      91   52         18       0
2   3     121   65         14       0
3   4      81   58         12       0
4   5      68   31         16       1

In [12]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'KMeans', 'StandardScaler', 'TfidfVectorizer', 'PCA', 'plt', '_i2', 'df', '_2', '_i3', '_i4', 'numeric_cols', 'text_cols', '_i5', 'scaler', 'X_numeric', '_i6', 'tfidf', '_i7', '_i8', 'wcss', 'k', 'kmeans', '_i9', '_i10', '_10', '_i11', 'pca', '_i12'])