In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("introds_spotify.csv")

df.head()

  artist_name  duration_ms  ...   album_name popularity
0  The Weeknd       250053  ...  After Hours        100
1  The Weeknd       239973  ...  After Hours        100
2  The Weeknd       211400  ...  After Hours        100
3  The Weeknd       191306  ...  After Hours        100
4  The Weeknd       247186  ...  After Hours        100

[5 rows x 19 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

# Check missing values
print(df.isnull().sum())

(347, 19)
<class 'pandas.DataFrame'>
RangeIndex: 347 entries, 0 to 346
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   artist_name       347 non-null    str
 1   duration_ms       347 non-null    int64
 2   id                347 non-null    str
 3   track_name        347 non-null    str
 4   track_number      347 non-null    int64
 5   danceability      347 non-null    float64
 6   energy            347 non-null    float64
 7   key               347 non-null    int64
 8   loudness          347 non-null    float64
 9   mode              347 non-null    int64
 10  speechiness       347 non-null    float64
 11  acousticness      347 non-null    float64
 12  instrumentalness  347 non-null    float64
 13  liveness          347 non-null    float64
 14  valence           347 non-null    float64
 15  tempo             347 non-null    float64
 16  time_signature    347 non-null    int64
 17  album_name        347 non-null    str
 18  popularity        347 non-null    int64
dtypes: float64(9), int64(6), str(4)
memory usage: 73.4 KB
None
         duration_ms  track_number  ...  time_signature  popularity
count     347.000000    347.000000  ...      347.000000  347.000000
mean   246764.057637      6.936599  ...        3.919308   65.829971
std     94108.387773      4.203152  ...        0.531495   17.398340
min      7948.000000      1.000000  ...        0.000000   38.000000
25%    192706.500000      3.000000  ...        4.000000   53.000000
50%    230026.000000      6.000000  ...        4.000000   66.000000
75%    286893.000000     10.000000  ...        4.000000   80.000000
max    727106.000000     20.000000  ...        5.000000  100.000000

[8 rows x 15 columns]
artist_name         0
duration_ms         0
id                  0
track_name          0
track_number        0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
album_name          0
popularity          0
dtype: int64

In [5]:
for col in df.select_dtypes(include=['object', 'string']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [7]:
if "target" in df.columns:
    X = df.drop(columns=["target"])
    y = df["target"]
else:
    print("Target column not found. Available columns:", df.columns)

Target column not found. Available columns: Index(['artist_name', 'duration_ms', 'id', 'track_name', 'track_number',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'time_signature', 'album_name', 'popularity'],
      dtype='str')

In [9]:
df.columns

Index(['artist_name', 'duration_ms', 'id', 'track_name', 'track_number',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'time_signature', 'album_name', 'popularity'],
      dtype='str')

In [11]:
df.head()

   artist_name  duration_ms   id  ...  time_signature  album_name  popularity
0           21       250053  294  ...               4           0         100
1           21       239973  104  ...               4           0         100
2           21       211400  301  ...               4           0         100
3           21       191306  182  ...               4           0         100
4           21       247186  155  ...               4           0         100

[5 rows x 19 columns]

In [15]:
df.head

<bound method NDFrame.head of      artist_name  duration_ms   id  ...  time_signature  album_name  popularity
0             21       250053  294  ...               4           0         100
1             21       239973  104  ...               4           0         100
2             21       211400  301  ...               4           0         100
3             21       191306  182  ...               4           0         100
4             21       247186  155  ...               4           0         100
..           ...          ...  ...  ...             ...         ...         ...
342           12       181576  266  ...               4          11          56
343           12       271345  210  ...               4          11          56
344           12       241424  297  ...               4          11          56
345           12       332483  303  ...               4          11          56
346           12       293856   99  ...               4          11          56

[347 rows x 19 columns]>