In [2]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk

# Machine learning
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import warnings
warnings.filterwarnings("ignore")

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
# Load CSV file

df = pd.read_csv("Key Macroeconomic Indicators.csv")

# Display first rows
df.head()

         DATE  UNRATE  CPIAUCSL   DFF  USRECM
0  01/12/1957     NaN       NaN  2.98     NaN
1  01/01/1958     5.8   3.50560  2.72     1.0
2  01/02/1958     6.4   3.23741  1.67     1.0
3  01/03/1958     6.7   3.62527  1.20     1.0
4  01/04/1958     7.4   3.61618  1.26     1.0

In [4]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DATE      702 non-null    str
 1   UNRATE    701 non-null    float64
 2   CPIAUCSL  701 non-null    float64
 3   DFF       702 non-null    float64
 4   USRECM    678 non-null    float64
dtypes: float64(4), str(1)
memory usage: 34.4 KB

In [5]:
# Statistical summary

df.describe()

           UNRATE    CPIAUCSL         DFF      USRECM
count  701.000000  701.000000  702.000000  678.000000
mean     6.085735    3.763080    5.120399    0.154867
std      1.564516    2.862619    3.638846    0.362045
min      3.400000   -1.958760    0.070000    0.000000
25%      5.000000    1.756230    2.735000    0.000000
50%      5.700000    3.061890    4.940000    0.000000
75%      7.100000    4.639600    6.845000    0.000000
max     10.800000   14.592270   19.100000    1.000000

In [7]:



df.head()

         DATE  UNRATE  CPIAUCSL   DFF  USRECM
0  01/12/1957     NaN       NaN  2.98     NaN
1  01/01/1958     5.8   3.50560  2.72     1.0
2  01/02/1958     6.4   3.23741  1.67     1.0
3  01/03/1958     6.7   3.62527  1.20     1.0
4  01/04/1958     7.4   3.61618  1.26     1.0

In [8]:
df.columns

Index(['DATE', 'UNRATE', 'CPIAUCSL', 'DFF', 'USRECM'], dtype='str')

In [9]:
df.head()

         DATE  UNRATE  CPIAUCSL   DFF  USRECM
0  01/12/1957     NaN       NaN  2.98     NaN
1  01/01/1958     5.8   3.50560  2.72     1.0
2  01/02/1958     6.4   3.23741  1.67     1.0
3  01/03/1958     6.7   3.62527  1.20     1.0
4  01/04/1958     7.4   3.61618  1.26     1.0

In [10]:
df.to_csv(
    "Macroeconomic_Indicators_KMeans_Clusters.csv",
    index=False
)