In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

import re
import string

In [2]:
df = pd.read_csv("pod.csv")

df.head()

   12BC9P              Glade    21  1                 http://www.glade.com
0  12LN8U  Sante A. Kowalski   NaN  1                  http://www.sante.pl
1  12TEUJ             Clorox   NaN  1                http://www.clorox.com
2  135U8F      Juicy Couture   NaN  1          http://www.juicycouture.com
3  142RY6              M&M's  18.0  1                  http://www.m-ms.com
4  14CBIR  Marie Callender's   NaN  1  http://www.mariecallendersmeals.com

In [4]:

df.head()

   12BC9P              Glade    21  1                 http://www.glade.com
0  12LN8U  Sante A. Kowalski   NaN  1                  http://www.sante.pl
1  12TEUJ             Clorox   NaN  1                http://www.clorox.com
2  135U8F      Juicy Couture   NaN  1          http://www.juicycouture.com
3  142RY6              M&M's  18.0  1                  http://www.m-ms.com
4  14CBIR  Marie Callender's   NaN  1  http://www.mariecallendersmeals.com

In [5]:

df.head()

   12BC9P              Glade    21  1                 http://www.glade.com
0  12LN8U  Sante A. Kowalski   NaN  1                  http://www.sante.pl
1  12TEUJ             Clorox   NaN  1                http://www.clorox.com
2  135U8F      Juicy Couture   NaN  1          http://www.juicycouture.com
3  142RY6              M&M's  18.0  1                  http://www.m-ms.com
4  14CBIR  Marie Callender's   NaN  1  http://www.mariecallendersmeals.com

In [7]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'TfidfVectorizer', 'KMeans', 're', 'string', '_i2', 'df', '_2', '_i3', 'TEXT_COLUMN', '_i4', '_4', '_i5', '_5', '_i6', 'plt', 'inertia', 'K_range', 'k', 'model', '_i7'])

In [8]:
df.head()

   12BC9P              Glade    21  1                 http://www.glade.com
0  12LN8U  Sante A. Kowalski   NaN  1                  http://www.sante.pl
1  12TEUJ             Clorox   NaN  1                http://www.clorox.com
2  135U8F      Juicy Couture   NaN  1          http://www.juicycouture.com
3  142RY6              M&M's  18.0  1                  http://www.m-ms.com
4  14CBIR  Marie Callender's   NaN  1  http://www.mariecallendersmeals.com

In [11]:
df.columns

Index(['12BC9P', 'Glade', '21', '1', 'http://www.glade.com'], dtype='str')