In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

# NLP (optional)
from sklearn.feature_extraction.text import TfidfVectorizer

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load CSV file

file_path = "features_std_stats_per_target_variable.csv"

df = pd.read_csv(file_path)

# Display first rows
df.head()

,quality_rate,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0,0.915222,0.117200,0.143228,5.165026,0.028796,20.591171,48.424116,0.002530,0.147043,0.100946,0.895594,0.390465
1,1,0.834589,0.091259,0.110221,4.652523,0.018751,15.178267,39.095260,0.002898,0.152620,0.119275,1.212499,0.587282

In [3]:
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape:
(2, 13)

Column Names:
Index(['quality_rate', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='str')

Missing Values:
quality_rate            0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [4]:
# Fill numerical missing values with median

numeric_cols = df.select_dtypes(include=np.number).columns

df[numeric_cols] = df[numeric_cols].fillna(
    df[numeric_cols].median()
)


# Check again
df.isnull().sum()

quality_rate            0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [5]:
# Select numeric columns

X = df.select_dtypes(
    include=['int64','float64']
)

print(X.shape)
X.head()

(2, 13)

,quality_rate,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0,0.915222,0.117200,0.143228,5.165026,0.028796,20.591171,48.424116,0.002530,0.147043,0.100946,0.895594,0.390465
1,1,0.834589,0.091259,0.110221,4.652523,0.018751,15.178267,39.095260,0.002898,0.152620,0.119275,1.212499,0.587282

In [6]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

X_scaled.head()

,quality_rate,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0

In [8]:
df.head()

,quality_rate,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0,0.915222,0.117200,0.143228,5.165026,0.028796,20.591171,48.424116,0.002530,0.147043,0.100946,0.895594,0.390465
1,1,0.834589,0.091259,0.110221,4.652523,0.018751,15.178267,39.095260,0.002898,0.152620,0.119275,1.212499,0.587282

In [9]:
df.to_csv(
    "features_std_stats_kmeans_clusters.csv",
    index=False
)

print(
    "Clustered dataset saved successfully"
)

Clustered dataset saved successfully