In [1]:
import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

from wordcloud import WordCloud

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
file_path = "latex-typesetting-with-excel.csv"

df = pd.read_csv(file_path)

df.head()

   X1  Y1  X2   Y2
0   1   1   1  0.5
1   2   4   2  2.0
2   3   9   3  4.5
3   4  16   8  8.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      4 non-null      int64
 1   Y1      4 non-null      int64
 2   X2      4 non-null      int64
 3   Y2      4 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 260.0 bytes

In [5]:
df.select_dtypes(include=['object']).columns

Index([], dtype='str')

In [7]:


df.head()

   X1  Y1  X2   Y2
0   1   1   1  0.5
1   2   4   2  2.0
2   3   9   3  4.5
3   4  16   8  8.0

In [8]:
df.head()

   X1  Y1  X2   Y2
0   1   1   1  0.5
1   2   4   2  2.0
2   3   9   3  4.5
3   4  16   8  8.0

In [10]:
print(df.columns.tolist())

['X1', 'Y1', 'X2', 'Y2']

In [12]:
print(df.head())
print(df.columns.tolist())

   X1  Y1  X2   Y2
0   1   1   1  0.5
1   2   4   2  2.0
2   3   9   3  4.5
3   4  16   8  8.0
['X1', 'Y1', 'X2', 'Y2']