In [1]:
import pandas as pd
import numpy as np

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

# Clustering
from sklearn.cluster import KMeans

# Visualization
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Text cleaning
import re

In [2]:
df = pd.read_csv("male.csv")

df.head()

,Name,Nickname,Division,Page,Facebook,Twitter,Instagram,Record,Fight Win Streak,Wins by Knockout,...,Striking accuracy,Grappling accuracy,Sig. Str. Landed Per Min,Sig. Str. Absorbed Per Min,Takedown avg Per 15 Min,Submission avg Per 15 Min,Sig. Str. Defense,Takedown Defense,Knockdown Ratio,Average fight time
0,Shamil Abdurakhimov,"""Abrek""",Heavyweight,https://www.ufc.com/athlete/shamil-abdurakhimov,https://www.facebook.com/profile.php?id=100007...,https://twitter.com/shamilabrek,https://instagram.com/shamilabdurakhimov,20-5-0 (W-L-D),0.0,9.0,...,45%,24%,2.45,2.45,1.23,0.18,59%,47%,0.35,10:43
1,Ricardo Abreu,"""Demente""",Middleweight,https://www.ufc.com/athlete/ricardo-abreu,https://facebook.com/ricardodemente,https://twitter.com/ricardodemente,https://instagram.com/ricardodementeoficial,5-1-0 (W-L-D),NaN,NaN,...,32%,43%,3.79,3.98,2.13,0.71,68%,100%,1.42,10:33
2,Klidson Abreu,"""White Bear""",Light Heavyweight,https://www.ufc.com/athlete/klidson-abreu,NaN,NaN,https://instagram.com/klidsonabreu,15-5-0 (W-L-D),NaN,4.0,...,41%,20%,2.05,2.90,0.64,0.00,56%,80%,0.00,11:43
3,Juan Adams,"""The Kraken""",Heavyweight,https://www.ufc.com/athlete/juan-adams,NaN,https://twitter.com/chosenjuan285,https://instagram.com/chosenjuan285,5-3-0 (W-L-D),NaN,5.0,...,51%,67%,6.17,4.67,1.05,0.00,35%,57%,0.00,07:11
4,Zarrukh Adashev,NaN,Bantamweight,https://www.ufc.com/athlete/zarrukh-adashev,NaN,NaN,https://instagram.com/zarrukh_adashev,0-1-0 (W-L-D),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print(df.head())

                  Name      Nickname           Division  \
0  Shamil Abdurakhimov       "Abrek"        Heavyweight
1        Ricardo Abreu     "Demente"       Middleweight
2        Klidson Abreu  "White Bear"  Light Heavyweight
3           Juan Adams  "The Kraken"        Heavyweight
4      Zarrukh Adashev           NaN       Bantamweight

                                              Page  \
0  https://www.ufc.com/athlete/shamil-abdurakhimov
1        https://www.ufc.com/athlete/ricardo-abreu
2        https://www.ufc.com/athlete/klidson-abreu
3           https://www.ufc.com/athlete/juan-adams
4      https://www.ufc.com/athlete/zarrukh-adashev

                                            Facebook  \
0  https://www.facebook.com/profile.php?id=100007...
1                https://facebook.com/ricardodemente
2                                                NaN
3                                                NaN
4                                                NaN

                              Twitter  \
0     https://twitter.com/shamilabrek
1  https://twitter.com/ricardodemente
2                                 NaN
3   https://twitter.com/chosenjuan285
4                                 NaN

                                     Instagram          Record  \
0     https://instagram.com/shamilabdurakhimov  20-5-0 (W-L-D)
1  https://instagram.com/ricardodementeoficial   5-1-0 (W-L-D)
2           https://instagram.com/klidsonabreu  15-5-0 (W-L-D)
3          https://instagram.com/chosenjuan285   5-3-0 (W-L-D)
4        https://instagram.com/zarrukh_adashev   0-1-0 (W-L-D)

   Fight Win Streak  Wins by Knockout  ...  Striking accuracy  \
0               0.0               9.0  ...                45%
1               NaN               NaN  ...                32%
2               NaN               4.0  ...                41%
3               NaN               5.0  ...                51%
4               NaN               NaN  ...                NaN

   Grappling accuracy  Sig. Str. Landed Per Min Sig. Str. Absorbed Per Min  \
0                 24%                      2.45                       2.45
1                 43%                      3.79                       3.98
2                 20%                      2.05                       2.90
3                 67%                      6.17                       4.67
4                 NaN                       NaN                        NaN

  Takedown avg Per 15 Min  Submission avg Per 15 Min  Sig. Str. Defense  \
0                    1.23                       0.18                59%
1                    2.13                       0.71                68%
2                    0.64                       0.00                56%
3                    1.05                       0.00                35%
4                     NaN                        NaN                NaN

   Takedown Defense  Knockdown Ratio  Average fight time
0               47%             0.35               10:43
1              100%             1.42               10:33
2               80%             0.00               11:43
3               57%             0.00               07:11
4               NaN              NaN                 NaN

[5 rows x 48 columns]

In [6]:
print(df.columns.tolist())

['Name', 'Nickname', 'Division', 'Page', 'Facebook', 'Twitter', 'Instagram', 'Record', 'Fight Win Streak', 'Wins by Knockout', 'Wins by Submission', 'Wins by Decision', 'Title Defenses', 'Hometown', 'Trains at', 'Age', 'Height', 'Weight', 'Reach', 'Leg reach', 'Octagon Debut', 'Status', 'Sig. Standing Str.', 'Sig. Clinch Str.', 'Sig. Ground Str.', 'Win By KO/TKO', 'Win By SUB', 'Win By DEC', 'Sig. Head Str.', 'Sig. Head Str.(%)', 'Sig. Body Str.', 'Sig. Body Str.(%)', 'Sig. Leg Str.', 'Sig. Leg Str.(%)', 'Sig. Strikes Landed', 'Sig. Strikes Attempted', 'Takedowns Landed', 'Takedowns Attempted', 'Striking accuracy', 'Grappling accuracy', 'Sig. Str. Landed Per Min', 'Sig. Str. Absorbed Per Min', 'Takedown avg Per 15 Min', 'Submission avg Per 15 Min', 'Sig. Str. Defense', 'Takedown Defense', 'Knockdown Ratio', 'Average fight time']

In [8]:
df.head()

,Name,Nickname,Division,Page,Facebook,Twitter,Instagram,Record,Fight Win Streak,Wins by Knockout,...,Striking accuracy,Grappling accuracy,Sig. Str. Landed Per Min,Sig. Str. Absorbed Per Min,Takedown avg Per 15 Min,Submission avg Per 15 Min,Sig. Str. Defense,Takedown Defense,Knockdown Ratio,Average fight time
0,Shamil Abdurakhimov,"""Abrek""",Heavyweight,https://www.ufc.com/athlete/shamil-abdurakhimov,https://www.facebook.com/profile.php?id=100007...,https://twitter.com/shamilabrek,https://instagram.com/shamilabdurakhimov,20-5-0 (W-L-D),0.0,9.0,...,45%,24%,2.45,2.45,1.23,0.18,59%,47%,0.35,10:43
1,Ricardo Abreu,"""Demente""",Middleweight,https://www.ufc.com/athlete/ricardo-abreu,https://facebook.com/ricardodemente,https://twitter.com/ricardodemente,https://instagram.com/ricardodementeoficial,5-1-0 (W-L-D),NaN,NaN,...,32%,43%,3.79,3.98,2.13,0.71,68%,100%,1.42,10:33
2,Klidson Abreu,"""White Bear""",Light Heavyweight,https://www.ufc.com/athlete/klidson-abreu,NaN,NaN,https://instagram.com/klidsonabreu,15-5-0 (W-L-D),NaN,4.0,...,41%,20%,2.05,2.90,0.64,0.00,56%,80%,0.00,11:43
3,Juan Adams,"""The Kraken""",Heavyweight,https://www.ufc.com/athlete/juan-adams,NaN,https://twitter.com/chosenjuan285,https://instagram.com/chosenjuan285,5-3-0 (W-L-D),NaN,5.0,...,51%,67%,6.17,4.67,1.05,0.00,35%,57%,0.00,07:11
4,Zarrukh Adashev,NaN,Bantamweight,https://www.ufc.com/athlete/zarrukh-adashev,NaN,NaN,https://instagram.com/zarrukh_adashev,0-1-0 (W-L-D),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print(df.columns.tolist())

['Name', 'Nickname', 'Division', 'Page', 'Facebook', 'Twitter', 'Instagram', 'Record', 'Fight Win Streak', 'Wins by Knockout', 'Wins by Submission', 'Wins by Decision', 'Title Defenses', 'Hometown', 'Trains at', 'Age', 'Height', 'Weight', 'Reach', 'Leg reach', 'Octagon Debut', 'Status', 'Sig. Standing Str.', 'Sig. Clinch Str.', 'Sig. Ground Str.', 'Win By KO/TKO', 'Win By SUB', 'Win By DEC', 'Sig. Head Str.', 'Sig. Head Str.(%)', 'Sig. Body Str.', 'Sig. Body Str.(%)', 'Sig. Leg Str.', 'Sig. Leg Str.(%)', 'Sig. Strikes Landed', 'Sig. Strikes Attempted', 'Takedowns Landed', 'Takedowns Attempted', 'Striking accuracy', 'Grappling accuracy', 'Sig. Str. Landed Per Min', 'Sig. Str. Absorbed Per Min', 'Takedown avg Per 15 Min', 'Submission avg Per 15 Min', 'Sig. Str. Defense', 'Takedown Defense', 'Knockdown Ratio', 'Average fight time']

In [12]:
print(df.columns.tolist())

['Name', 'Nickname', 'Division', 'Page', 'Facebook', 'Twitter', 'Instagram', 'Record', 'Fight Win Streak', 'Wins by Knockout', 'Wins by Submission', 'Wins by Decision', 'Title Defenses', 'Hometown', 'Trains at', 'Age', 'Height', 'Weight', 'Reach', 'Leg reach', 'Octagon Debut', 'Status', 'Sig. Standing Str.', 'Sig. Clinch Str.', 'Sig. Ground Str.', 'Win By KO/TKO', 'Win By SUB', 'Win By DEC', 'Sig. Head Str.', 'Sig. Head Str.(%)', 'Sig. Body Str.', 'Sig. Body Str.(%)', 'Sig. Leg Str.', 'Sig. Leg Str.(%)', 'Sig. Strikes Landed', 'Sig. Strikes Attempted', 'Takedowns Landed', 'Takedowns Attempted', 'Striking accuracy', 'Grappling accuracy', 'Sig. Str. Landed Per Min', 'Sig. Str. Absorbed Per Min', 'Takedown avg Per 15 Min', 'Submission avg Per 15 Min', 'Sig. Str. Defense', 'Takedown Defense', 'Knockdown Ratio', 'Average fight time']