In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load CSV file
df = pd.read_csv("menu2_.csv")

# Preview data
print(df.head())
print(df.info())

    Category                              Item  ... Iron (% Daily Value) Observ
0  Breakfast                      Egg McMuffin  ...                 15.0    NaN
1  Breakfast                 Egg White Delight  ...                  8.0    NaN
2  Breakfast                  Sausage McMuffin  ...                 10.0    NaN
3  Breakfast         Sausage McMuffin with Egg  ...                 15.0    NaN
4  Breakfast  Sausage McMuffin with Egg Whites  ...                 10.0    NaN

[5 rows x 25 columns]
<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Category                       266 non-null    str
 1   Item                           266 non-null    str
 2   Serving Size                   266 non-null    str
 3   Calories                       263 non-null    str
 4   Calories from Fat              265 non-null    float64
 5   Total Fat                      264 non-null    float64
 6   Total Fat (% Daily Value)      264 non-null    float64
 7   Saturated Fat                  264 non-null    float64
 8   Saturated Fat (% Daily Value)  265 non-null    float64
 9   Trans Fat                      264 non-null    float64
 10  Cholesterol                    264 non-null    float64
 11  Cholesterol (% Daily Value)    265 non-null    float64
 12  Sodium                         264 non-null    float64
 13  Sodium (% Daily Value)         265 non-null    float64
 14  Carbohydrates                  263 non-null    float64
 15  Carbohydrates (% Daily Value)  265 non-null    float64
 16  Dietary Fiber                  264 non-null    float64
 17  Dietary Fiber (% Daily Value)  266 non-null    int64
 18  Sugars                         266 non-null    int64
 19  Protein                        265 non-null    float64
 20  Vitamin A (% Daily Value)      265 non-null    float64
 21  Vitamin C (% Daily Value)      264 non-null    float64
 22  Calcium (% Daily Value)        265 non-null    float64
 23  Iron (% Daily Value)           265 non-null    float64
 24  Observ                         0 non-null      float64
dtypes: float64(19), int64(2), str(4)
memory usage: 66.8 KB
None

In [3]:
# Check missing values
print(df.isnull().sum())

# Drop rows with missing values (simple approach)
df = df.dropna()

Category                           0
Item                               0
Serving Size                       0
Calories                           3
Calories from Fat                  1
Total Fat                          2
Total Fat (% Daily Value)          2
Saturated Fat                      2
Saturated Fat (% Daily Value)      1
Trans Fat                          2
Cholesterol                        2
Cholesterol (% Daily Value)        1
Sodium                             2
Sodium (% Daily Value)             1
Carbohydrates                      3
Carbohydrates (% Daily Value)      1
Dietary Fiber                      2
Dietary Fiber (% Daily Value)      0
Sugars                             0
Protein                            1
Vitamin A (% Daily Value)          1
Vitamin C (% Daily Value)          2
Calcium (% Daily Value)            1
Iron (% Daily Value)               1
Observ                           266
dtype: int64

In [4]:
label_encoders = {}

for column in df.columns:
    if df[column].dtype == 'object':
        le = LabelEncoder()
        df[column] = le.fit_transform(df[column])
        label_encoders[column] = le

In [6]:
print(df.columns)

Index(['Category', 'Item', 'Serving Size', 'Calories', 'Calories from Fat',
       'Total Fat', 'Total Fat (% Daily Value)', 'Saturated Fat',
       'Saturated Fat (% Daily Value)', 'Trans Fat', 'Cholesterol',
       'Cholesterol (% Daily Value)', 'Sodium', 'Sodium (% Daily Value)',
       'Carbohydrates', 'Carbohydrates (% Daily Value)', 'Dietary Fiber',
       'Dietary Fiber (% Daily Value)', 'Sugars', 'Protein',
       'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
       'Calcium (% Daily Value)', 'Iron (% Daily Value)', 'Observ'],
      dtype='str')

In [9]:
print(df.head())
print(df.columns.tolist())

Empty DataFrame
Columns: [Category, Item, Serving Size, Calories, Calories from Fat, Total Fat, Total Fat (% Daily Value), Saturated Fat, Saturated Fat (% Daily Value), Trans Fat, Cholesterol, Cholesterol (% Daily Value), Sodium, Sodium (% Daily Value), Carbohydrates, Carbohydrates (% Daily Value), Dietary Fiber, Dietary Fiber (% Daily Value), Sugars, Protein, Vitamin A (% Daily Value), Vitamin C (% Daily Value), Calcium (% Daily Value), Iron (% Daily Value), Observ]
Index: []
['Category', 'Item', 'Serving Size', 'Calories', 'Calories from Fat', 'Total Fat', 'Total Fat (% Daily Value)', 'Saturated Fat', 'Saturated Fat (% Daily Value)', 'Trans Fat', 'Cholesterol', 'Cholesterol (% Daily Value)', 'Sodium', 'Sodium (% Daily Value)', 'Carbohydrates', 'Carbohydrates (% Daily Value)', 'Dietary Fiber', 'Dietary Fiber (% Daily Value)', 'Sugars', 'Protein', 'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)', 'Calcium (% Daily Value)', 'Iron (% Daily Value)', 'Observ']

In [12]:
print(df.columns)

Index(['Category', 'Item', 'Serving Size', 'Calories', 'Calories from Fat',
       'Total Fat', 'Total Fat (% Daily Value)', 'Saturated Fat',
       'Saturated Fat (% Daily Value)', 'Trans Fat', 'Cholesterol',
       'Cholesterol (% Daily Value)', 'Sodium', 'Sodium (% Daily Value)',
       'Carbohydrates', 'Carbohydrates (% Daily Value)', 'Dietary Fiber',
       'Dietary Fiber (% Daily Value)', 'Sugars', 'Protein',
       'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
       'Calcium (% Daily Value)', 'Iron (% Daily Value)', 'Observ'],
      dtype='str')

In [15]:
df.head()

Empty DataFrame
Columns: [Category, Item, Serving Size, Calories, Calories from Fat, Total Fat, Total Fat (% Daily Value), Saturated Fat, Saturated Fat (% Daily Value), Trans Fat, Cholesterol, Cholesterol (% Daily Value), Sodium, Sodium (% Daily Value), Carbohydrates, Carbohydrates (% Daily Value), Dietary Fiber, Dietary Fiber (% Daily Value), Sugars, Protein, Vitamin A (% Daily Value), Vitamin C (% Daily Value), Calcium (% Daily Value), Iron (% Daily Value), Observ]
Index: []

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Category                       0 non-null      str
 1   Item                           0 non-null      str
 2   Serving Size                   0 non-null      str
 3   Calories                       0 non-null      str
 4   Calories from Fat              0 non-null      float64
 5   Total Fat                      0 non-null      float64
 6   Total Fat (% Daily Value)      0 non-null      float64
 7   Saturated Fat                  0 non-null      float64
 8   Saturated Fat (% Daily Value)  0 non-null      float64
 9   Trans Fat                      0 non-null      float64
 10  Cholesterol                    0 non-null      float64
 11  Cholesterol (% Daily Value)    0 non-null      float64
 12  Sodium                         0 non-null      float64
 13  Sodium (% Daily Value)         0 non-null      float64
 14  Carbohydrates                  0 non-null      float64
 15  Carbohydrates (% Daily Value)  0 non-null      float64
 16  Dietary Fiber                  0 non-null      float64
 17  Dietary Fiber (% Daily Value)  0 non-null      int64
 18  Sugars                         0 non-null      int64
 19  Protein                        0 non-null      float64
 20  Vitamin A (% Daily Value)      0 non-null      float64
 21  Vitamin C (% Daily Value)      0 non-null      float64
 22  Calcium (% Daily Value)        0 non-null      float64
 23  Iron (% Daily Value)           0 non-null      float64
 24  Observ                         0 non-null      float64
dtypes: float64(19), int64(2), str(4)
memory usage: 132.0 bytes

In [19]:
(df.head())

Empty DataFrame
Columns: [Category, Item, Serving Size, Calories, Calories from Fat, Total Fat, Total Fat (% Daily Value), Saturated Fat, Saturated Fat (% Daily Value), Trans Fat, Cholesterol, Cholesterol (% Daily Value), Sodium, Sodium (% Daily Value), Carbohydrates, Carbohydrates (% Daily Value), Dietary Fiber, Dietary Fiber (% Daily Value), Sugars, Protein, Vitamin A (% Daily Value), Vitamin C (% Daily Value), Calcium (% Daily Value), Iron (% Daily Value), Observ]
Index: []

In [25]:
print(df.columns)

Index(['Category', 'Item', 'Serving Size', 'Calories', 'Calories from Fat',
       'Total Fat', 'Total Fat (% Daily Value)', 'Saturated Fat',
       'Saturated Fat (% Daily Value)', 'Trans Fat', 'Cholesterol',
       'Cholesterol (% Daily Value)', 'Sodium', 'Sodium (% Daily Value)',
       'Carbohydrates', 'Carbohydrates (% Daily Value)', 'Dietary Fiber',
       'Dietary Fiber (% Daily Value)', 'Sugars', 'Protein',
       'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
       'Calcium (% Daily Value)', 'Iron (% Daily Value)', 'Observ'],
      dtype='str')