In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("MiamiHeat.csv")

# View basic structure
print(df.head())
print(df.info())
print(df.describe())

   Game        Date Location  Opp Win  FG  FGA  FG3  FG3A  FT  ...  OppFT  \
0     1  10/26/2010     Away  BOS   L  27   74    8    20  18  ...     16
1     2  10/27/2010     Away  PHI   W  33   69    8    16  23  ...      8
2     3  10/29/2010     Home  ORL   W  33   81    9    18  21  ...     24
3     4  10/31/2010     Away  NJN   W  36   67    5    16  24  ...     15
4     5   11/2/2010     Home  MIN   W  46   79   12    21  25  ...     29

   OppFTA  OppOffReb  OppRebounds  OppAssists  OppSteals  OppBlocks  \
0      25          8           42          25          6          4
1      11         10           38          24         10          4
2      34          8           40           5          5          3
3      23         19           43          16          5          0
4      38         13           40          14         10          2

   OppTurnovers  OppFouls  OppPoints
0            18        19         88
1            16        22         87
2            14        20         70
3            15        19         78
4            18        23         97

[5 rows x 33 columns]
<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Game          82 non-null     int64
 1   Date          82 non-null     str
 2   Location      82 non-null     str
 3   Opp           82 non-null     str
 4   Win           82 non-null     str
 5   FG            82 non-null     int64
 6   FGA           82 non-null     int64
 7   FG3           82 non-null     int64
 8   FG3A          82 non-null     int64
 9   FT            82 non-null     int64
 10  FTA           82 non-null     int64
 11  Rebounds      82 non-null     int64
 12  OffReb        82 non-null     int64
 13  Assists       82 non-null     int64
 14  Steals        82 non-null     int64
 15  Blocks        82 non-null     int64
 16  Trunovers     82 non-null     int64
 17  Fouls         82 non-null     int64
 18  Points        82 non-null     int64
 19  OppFG         82 non-null     int64
 20  OppFGA        82 non-null     int64
 21  OppFG3        82 non-null     int64
 22  OppFG3A       82 non-null     int64
 23  OppFT         82 non-null     int64
 24  OppFTA        82 non-null     int64
 25  OppOffReb     82 non-null     int64
 26  OppRebounds   82 non-null     int64
 27  OppAssists    82 non-null     int64
 28  OppSteals     82 non-null     int64
 29  OppBlocks     82 non-null     int64
 30  OppTurnovers  82 non-null     int64
 31  OppFouls      82 non-null     int64
 32  OppPoints     82 non-null     int64
dtypes: int64(29), str(4)
memory usage: 22.6 KB
None
            Game         FG        FGA        FG3       FG3A         FT  \
count  82.000000  82.000000  82.000000  82.000000  82.000000  82.000000
mean   41.500000  36.963415  76.841463   6.670732  18.036585  21.463415
std    23.815261   5.073400   5.957606   2.884847   5.100097   6.520992
min     1.000000  24.000000  62.000000   2.000000   8.000000   8.000000
25%    21.250000  33.250000  72.250000   5.000000  15.000000  17.000000
50%    41.500000  36.000000  77.000000   6.000000  18.000000  22.000000
75%    61.750000  41.000000  80.000000   8.750000  21.000000  25.000000
max    82.000000  51.000000  92.000000  16.000000  31.000000  36.000000

             FTA   Rebounds     OffReb    Assists  ...      OppFT     OppFTA  \
count  82.000000  82.000000  82.000000  82.000000  ...  82.000000  82.000000
mean   27.902439  42.146341   9.634146  19.987805  ...  17.963415  24.146341
std     7.881232   5.475246   3.105202   4.852119  ...   5.264475   6.820669
min    11.000000  30.000000   4.000000  12.000000  ...   8.000000  11.000000
25%    22.000000  39.000000   8.000000  17.000000  ...  14.000000  20.000000
50%    28.000000  43.000000   9.000000  19.000000  ...  17.500000  23.000000
75%    32.750000  46.000000  11.000000  23.000000  ...  21.000000  28.000000
max    47.000000  56.000000  18.000000  33.000000  ...  32.000000  40.000000

       OppOffReb  OppRebounds  OppAssists  OppSteals  OppBlocks  OppTurnovers  \
count  82.000000    82.000000   82.000000  82.000000  82.000000     82.000000
mean   10.536585    39.182927   20.134146   7.000000   3.000000     12.414634
std     3.341454     5.784458    4.845164   2.194269   2.119865      3.058892
min     2.000000    26.000000    5.000000   2.000000   0.000000      5.000000
25%     9.000000    35.000000   17.000000   5.000000   1.250000     10.250000
50%    10.000000    39.500000   20.000000   7.000000   3.000000     12.500000
75%    13.000000    43.000000   24.000000   8.000000   4.000000     14.000000
max    19.000000    53.000000   33.000000  11.000000   9.000000     23.000000

        OppFouls   OppPoints
count  82.000000   82.000000
mean   21.804878   94.597561
std     4.211797   11.599127
min    14.000000   70.000000
25%    19.000000   87.000000
50%    22.000000   94.000000
75%    24.000000  100.000000
max    32.000000  130.000000

[8 rows x 29 columns]

In [3]:
# Check missing values
print(df.isnull().sum())

# Example: fill or drop missing values
df = df.dropna()   # or use fillna() depending on dataset

Game            0
Date            0
Location        0
Opp             0
Win             0
FG              0
FGA             0
FG3             0
FG3A            0
FT              0
FTA             0
Rebounds        0
OffReb          0
Assists         0
Steals          0
Blocks          0
Trunovers       0
Fouls           0
Points          0
OppFG           0
OppFGA          0
OppFG3          0
OppFG3A         0
OppFT           0
OppFTA          0
OppOffReb       0
OppRebounds     0
OppAssists      0
OppSteals       0
OppBlocks       0
OppTurnovers    0
OppFouls        0
OppPoints       0
dtype: int64

In [5]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'DecisionTreeClassifier', 'plot_tree', 'RandomForestClassifier', 'accuracy_score', 'classification_report', 'confusion_matrix', 'plt', '_i2', 'df', '_i3', '_i4', '_i5'])

In [8]:
print(df.columns)
df.head()

Index(['Game', 'Date', 'Location', 'Opp', 'Win', 'FG', 'FGA', 'FG3', 'FG3A',
       'FT', 'FTA', 'Rebounds', 'OffReb', 'Assists', 'Steals', 'Blocks',
       'Trunovers', 'Fouls', 'Points', 'OppFG', 'OppFGA', 'OppFG3', 'OppFG3A',
       'OppFT', 'OppFTA', 'OppOffReb', 'OppRebounds', 'OppAssists',
       'OppSteals', 'OppBlocks', 'OppTurnovers', 'OppFouls', 'OppPoints'],
      dtype='str')

,Game,Date,Location,Opp,Win,FG,FGA,FG3,FG3A,FT,...,OppFT,OppFTA,OppOffReb,OppRebounds,OppAssists,OppSteals,OppBlocks,OppTurnovers,OppFouls,OppPoints
0,1,10/26/2010,Away,BOS,L,27,74,8,20,18,...,16,25,8,42,25,6,4,18,19,88
1,2,10/27/2010,Away,PHI,W,33,69,8,16,23,...,8,11,10,38,24,10,4,16,22,87
2,3,10/29/2010,Home,ORL,W,33,81,9,18,21,...,24,34,8,40,5,5,3,14,20,70
3,4,10/31/2010,Away,NJN,W,36,67,5,16,24,...,15,23,19,43,16,5,0,15,19,78
4,5,11/2/2010,Home,MIN,W,46,79,12,21,25,...,29,38,13,40,14,10,2,18,23,97

In [12]:
df.head()

,Game,Date,Location,Opp,Win,FG,FGA,FG3,FG3A,FT,...,OppFT,OppFTA,OppOffReb,OppRebounds,OppAssists,OppSteals,OppBlocks,OppTurnovers,OppFouls,OppPoints
0,1,10/26/2010,Away,BOS,L,27,74,8,20,18,...,16,25,8,42,25,6,4,18,19,88
1,2,10/27/2010,Away,PHI,W,33,69,8,16,23,...,8,11,10,38,24,10,4,16,22,87
2,3,10/29/2010,Home,ORL,W,33,81,9,18,21,...,24,34,8,40,5,5,3,14,20,70
3,4,10/31/2010,Away,NJN,W,36,67,5,16,24,...,15,23,19,43,16,5,0,15,19,78
4,5,11/2/2010,Home,MIN,W,46,79,12,21,25,...,29,38,13,40,14,10,2,18,23,97

In [17]:
df.head(5)

,Game,Date,Location,Opp,Win,FG,FGA,FG3,FG3A,FT,...,OppFT,OppFTA,OppOffReb,OppRebounds,OppAssists,OppSteals,OppBlocks,OppTurnovers,OppFouls,OppPoints
0,1,10/26/2010,Away,BOS,L,27,74,8,20,18,...,16,25,8,42,25,6,4,18,19,88
1,2,10/27/2010,Away,PHI,W,33,69,8,16,23,...,8,11,10,38,24,10,4,16,22,87
2,3,10/29/2010,Home,ORL,W,33,81,9,18,21,...,24,34,8,40,5,5,3,14,20,70
3,4,10/31/2010,Away,NJN,W,36,67,5,16,24,...,15,23,19,43,16,5,0,15,19,78
4,5,11/2/2010,Home,MIN,W,46,79,12,21,25,...,29,38,13,40,14,10,2,18,23,97

In [19]:
print('y_test' in globals())

False

In [21]:
print(hasattr(rf_model, "estimators_"))

False

In [27]:
print(df.head())

   Game        Date Location  Opp Win  FG  FGA  FG3  FG3A  FT  ...  OppFT  \
0     1  10/26/2010     Away  BOS   L  27   74    8    20  18  ...     16
1     2  10/27/2010     Away  PHI   W  33   69    8    16  23  ...      8
2     3  10/29/2010     Home  ORL   W  33   81    9    18  21  ...     24
3     4  10/31/2010     Away  NJN   W  36   67    5    16  24  ...     15
4     5   11/2/2010     Home  MIN   W  46   79   12    21  25  ...     29

   OppFTA  OppOffReb  OppRebounds  OppAssists  OppSteals  OppBlocks  \
0      25          8           42          25          6          4
1      11         10           38          24         10          4
2      34          8           40           5          5          3
3      23         19           43          16          5          0
4      38         13           40          14         10          2

   OppTurnovers  OppFouls  OppPoints
0            18        19         88
1            16        22         87
2            14        20         70
3            15        19         78
4            18        23         97

[5 rows x 33 columns]

In [28]:
print(df.columns)

Index(['Game', 'Date', 'Location', 'Opp', 'Win', 'FG', 'FGA', 'FG3', 'FG3A',
       'FT', 'FTA', 'Rebounds', 'OffReb', 'Assists', 'Steals', 'Blocks',
       'Trunovers', 'Fouls', 'Points', 'OppFG', 'OppFGA', 'OppFG3', 'OppFG3A',
       'OppFT', 'OppFTA', 'OppOffReb', 'OppRebounds', 'OppAssists',
       'OppSteals', 'OppBlocks', 'OppTurnovers', 'OppFouls', 'OppPoints'],
      dtype='str')