In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Missing values
from sklearn.impute import SimpleImputer

# Scaling
from sklearn.preprocessing import StandardScaler

# K-Means clustering
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load CSV file
df = pd.read_csv("missing_values.csv")

# Display first rows
df.head()

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,Total,0,0,0,0,0,0,0,0,0,0,0,0
1,Percent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Types,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,int64

In [3]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            3 non-null      str
 1   fixed acidity         3 non-null      str
 2   volatile acidity      3 non-null      str
 3   citric acid           3 non-null      str
 4   residual sugar        3 non-null      str
 5   chlorides             3 non-null      str
 6   free sulfur dioxide   3 non-null      str
 7   total sulfur dioxide  3 non-null      str
 8   density               3 non-null      str
 9   pH                    3 non-null      str
 10  sulphates             3 non-null      str
 11  alcohol               3 non-null      str
 12  quality               3 non-null      str
dtypes: str(13)
memory usage: 591.0 bytes

In [4]:
# Numerical columns
numeric_columns = df.select_dtypes(include=['int64','float64']).columns

# Text columns
text_columns = df.select_dtypes(include=['object']).columns

print("Numeric columns:", numeric_columns)
print("Text columns:", text_columns)

Numeric columns: Index([], dtype='str')
Text columns: Index(['Unnamed: 0', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='str')

In [6]:
df.head()

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,Total,0,0,0,0,0,0,0,0,0,0,0,0
1,Percent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Types,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,int64

In [7]:
if "combined_text" in df.columns:

    tfidf = TfidfVectorizer(
        stop_words="english",
        max_features=500
    )

    text_features = tfidf.fit_transform(
        df["combined_text"]
    )

    print(text_features.shape)

In [8]:
df.head()

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,Total,0,0,0,0,0,0,0,0,0,0,0,0
1,Percent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Types,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,int64

In [9]:
df.to_csv(
    "missing_values_processed.csv",
    index=False
)

print("File saved successfully")

File saved successfully