In [1]:
import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

from wordcloud import WordCloud

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
df = pd.read_csv("Move to Canada.csv")

df.head()

         Date  From US  From Britain
0  10/01/2004        2             0
1  17/01/2004        2            16
2  24/01/2004        3            16
3  31/01/2004        2            17
4  07/02/2004        3            18

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 653 entries, 0 to 652
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          653 non-null    str
 1   From US       653 non-null    int64
 2   From Britain  653 non-null    int64
dtypes: int64(2), str(1)
memory usage: 21.8 KB

In [5]:
df.columns

Index(['Date', 'From US', 'From Britain'], dtype='str')

In [8]:
print(df.columns)

Index(['Date', 'From US', 'From Britain'], dtype='str')

In [9]:
df.head()

         Date  From US  From Britain
0  10/01/2004        2             0
1  17/01/2004        2            16
2  24/01/2004        3            16
3  31/01/2004        2            17
4  07/02/2004        3            18

In [10]:
df.head()

         Date  From US  From Britain
0  10/01/2004        2             0
1  17/01/2004        2            16
2  24/01/2004        3            16
3  31/01/2004        2            17
4  07/02/2004        3            18

In [11]:
df.to_csv(
    "Move_to_Canada_KMeans_results.csv",
    index=False
)