In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt

# Machine learning
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

# Download NLP resources
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file
df = pd.read_csv("mpg123-play-stream-syscall.csv")

# Display first rows
df.head()

,POWER,getsockname,send,kill,unlink,close,brk,open,getuid32,time,...,access,clock_gettime,openat,getcwd,set_tid_address,getgid32,mmap2,ftruncate64,bind,readlink
0,19.91030,8,56747,17,4,113,5,244,14,2,...,35,251786,5,0,1,4,118,4,0,7
1,19.89760,8,56585,17,4,113,5,244,14,2,...,35,251306,5,0,1,4,118,4,0,7
2,19.90563,8,7825,17,5,119,5,244,14,2,...,35,34183,5,0,1,4,118,4,0,7
3,19.94871,6,172245,13,3,101,4,241,10,2,...,34,749913,5,2,1,3,117,3,0,5
4,19.93659,6,171811,13,3,101,4,241,10,2,...,34,748004,5,2,1,3,117,3,0,5

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 61 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   POWER            47 non-null     float64
 1   getsockname      47 non-null     int64
 2   send             47 non-null     int64
 3   kill             47 non-null     int64
 4   unlink           47 non-null     int64
 5   close            47 non-null     int64
 6   brk              47 non-null     int64
 7   open             47 non-null     int64
 8   getuid32         47 non-null     int64
 9   time             47 non-null     int64
 10  poll             47 non-null     int64
 11  ioctl            47 non-null     int64
 12  writev           47 non-null     int64
 13  socket           47 non-null     int64
 14  chdir            47 non-null     int64
 15  getrlimit        47 non-null     int64
 16  pipe2            47 non-null     int64
 17  clone            47 non-null     int64
 18  mprotect         47 non-null     int64
 19  prctl            47 non-null     int64
 20  uname            47 non-null     int64
 21  recvfrom         47 non-null     int64
 22  getsockopt       47 non-null     int64
 23  sendmsg          47 non-null     int64
 24  recv             47 non-null     int64
 25  _llseek          47 non-null     int64
 26  gettimeofday     47 non-null     int64
 27  set_robust_list  47 non-null     int64
 28  stat64           47 non-null     int64
 29  fcntl64          47 non-null     int64
 30  munmap           47 non-null     int64
 31  getdents         47 non-null     int64
 32  connect          47 non-null     int64
 33  sendto           47 non-null     int64
 34  rt_sigprocmask   47 non-null     int64
 35  pipe             47 non-null     int64
 36  execve           47 non-null     int64
 37  setsockopt       47 non-null     int64
 38  getpeername      47 non-null     int64
 39  getdents64       47 non-null     int64
 40  write            47 non-null     int64
 41  rt_sigaction     47 non-null     int64
 42  read             47 non-null     int64
 43  futex            47 non-null     int64
 44  shutdown         47 non-null     int64
 45  set_thread_area  47 non-null     int64
 46  fstat64          47 non-null     int64
 47  lseek            47 non-null     int64
 48  statfs           47 non-null     int64
 49  recvmsg          47 non-null     int64
 50  madvise          47 non-null     int64
 51  access           47 non-null     int64
 52  clock_gettime    47 non-null     int64
 53  openat           47 non-null     int64
 54  getcwd           47 non-null     int64
 55  set_tid_address  47 non-null     int64
 56  getgid32         47 non-null     int64
 57  mmap2            47 non-null     int64
 58  ftruncate64      47 non-null     int64
 59  bind             47 non-null     int64
 60  readlink         47 non-null     int64
dtypes: float64(1), int64(60)
memory usage: 22.5 KB

In [4]:
df.isnull().sum()

POWER          0
getsockname    0
send           0
kill           0
unlink         0
              ..
getgid32       0
mmap2          0
ftruncate64    0
bind           0
readlink       0
Length: 61, dtype: int64

In [5]:
text_columns = df.select_dtypes(include=['object']).columns

print(text_columns)

Index([], dtype='str')

In [7]:
print(df.shape)
print(df.columns.tolist())
print(df.head())

(47, 61)
['POWER', 'getsockname', 'send', 'kill', 'unlink', 'close', 'brk', 'open', 'getuid32', 'time', 'poll', 'ioctl', 'writev', 'socket', 'chdir', 'getrlimit', 'pipe2', 'clone', 'mprotect', 'prctl', 'uname', 'recvfrom', 'getsockopt', 'sendmsg', 'recv', '_llseek', 'gettimeofday', 'set_robust_list', 'stat64', 'fcntl64', 'munmap', 'getdents', 'connect', 'sendto', 'rt_sigprocmask', 'pipe', 'execve', 'setsockopt', 'getpeername', 'getdents64', 'write', 'rt_sigaction', 'read', 'futex', 'shutdown', 'set_thread_area', 'fstat64', 'lseek', 'statfs', 'recvmsg', 'madvise', 'access', 'clock_gettime', 'openat', 'getcwd', 'set_tid_address', 'getgid32', 'mmap2', 'ftruncate64', 'bind', 'readlink']
      POWER  getsockname    send  kill  unlink  close  brk  open  getuid32  \
0  19.91030            8   56747    17       4    113    5   244        14
1  19.89760            8   56585    17       4    113    5   244        14
2  19.90563            8    7825    17       5    119    5   244        14
3  19.94871            6  172245    13       3    101    4   241        10
4  19.93659            6  171811    13       3    101    4   241        10

   time  ...  access  clock_gettime  openat  getcwd  set_tid_address  \
0     2  ...      35         251786       5       0                1
1     2  ...      35         251306       5       0                1
2     2  ...      35          34183       5       0                1
3     2  ...      34         749913       5       2                1
4     2  ...      34         748004       5       2                1

   getgid32  mmap2  ftruncate64  bind  readlink
0         4    118            4     0         7
1         4    118            4     0         7
2         4    118            4     0         7
3         3    117            3     0         5
4         3    117            3     0         5

[5 rows x 61 columns]

In [9]:
df.columns

Index(['POWER', 'getsockname', 'send', 'kill', 'unlink', 'close', 'brk',
       'open', 'getuid32', 'time', 'poll', 'ioctl', 'writev', 'socket',
       'chdir', 'getrlimit', 'pipe2', 'clone', 'mprotect', 'prctl', 'uname',
       'recvfrom', 'getsockopt', 'sendmsg', 'recv', '_llseek', 'gettimeofday',
       'set_robust_list', 'stat64', 'fcntl64', 'munmap', 'getdents', 'connect',
       'sendto', 'rt_sigprocmask', 'pipe', 'execve', 'setsockopt',
       'getpeername', 'getdents64', 'write', 'rt_sigaction', 'read', 'futex',
       'shutdown', 'set_thread_area', 'fstat64', 'lseek', 'statfs', 'recvmsg',
       'madvise', 'access', 'clock_gettime', 'openat', 'getcwd',
       'set_tid_address', 'getgid32', 'mmap2', 'ftruncate64', 'bind',
       'readlink'],
      dtype='str')

In [10]:
df.chdir

0     0
1     0
2     0
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
11    2
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
Name: chdir, dtype: int64

In [11]:
df.close

0     113
1     113
2     119
3     101
4     101
5     101
6     101
7     101
8     101
9     119
10    119
11    119
12    119
13    121
14    121
15    119
16    119
17    121
18    121
19    121
20    121
21    121
22    121
23    121
24    116
25    116
26    116
27    116
28    116
29    116
30    116
31    116
32    116
33    116
34    116
35    116
36    116
37    116
38    116
39    115
40    115
41    115
42    115
43    115
44    115
45    115
46    115
Name: close, dtype: int64

In [12]:
df.head()

,POWER,getsockname,send,kill,unlink,close,brk,open,getuid32,time,...,access,clock_gettime,openat,getcwd,set_tid_address,getgid32,mmap2,ftruncate64,bind,readlink
0,19.91030,8,56747,17,4,113,5,244,14,2,...,35,251786,5,0,1,4,118,4,0,7
1,19.89760,8,56585,17,4,113,5,244,14,2,...,35,251306,5,0,1,4,118,4,0,7
2,19.90563,8,7825,17,5,119,5,244,14,2,...,35,34183,5,0,1,4,118,4,0,7
3,19.94871,6,172245,13,3,101,4,241,10,2,...,34,749913,5,2,1,3,117,3,0,5
4,19.93659,6,171811,13,3,101,4,241,10,2,...,34,748004,5,2,1,3,117,3,0,5

In [13]:
df.to_csv(
    "mpg123-play-stream-syscall-kmeans-results.csv",
    index=False
)

print("Saved successfully")

Saved successfully