In [1]:
# 📦 1. Import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# 📂 2. Load Dataset
df = pd.read_csv("NBAchampionsdata.csv")

# Preview data
df.head()

   Year    Team  Game  Win  Home   MP  FG  ...  TRB  AST  STL  BLK  TOV  PF  PTS
0  1980  Lakers     1    1     1  240  48  ...   43   30    5    9   17  24  109
1  1980  Lakers     2    0     1  240  48  ...   52   32   12    7   26  27  104
2  1980  Lakers     3    1     0  240  44  ...   56   20    5    5   20  25  111
3  1980  Lakers     4    0     0  240  44  ...   49   23   12    6   19  22  102
4  1980  Lakers     5    1     1  240  41  ...   56   28    7    6   21  27  108

[5 rows x 24 columns]

In [3]:
# 🔍 3. Basic Data Exploration
print(df.info())
print(df.describe())

# Check missing values
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    220 non-null    int64
 1   Team    220 non-null    str
 2   Game    220 non-null    int64
 3   Win     220 non-null    int64
 4   Home    220 non-null    int64
 5   MP      220 non-null    int64
 6   FG      220 non-null    int64
 7   FGA     220 non-null    int64
 8   FGP     220 non-null    float64
 9   TP      220 non-null    int64
 10  TPA     220 non-null    int64
 11  TPP     214 non-null    float64
 12  FT      220 non-null    int64
 13  FTA     220 non-null    int64
 14  FTP     220 non-null    float64
 15  ORB     220 non-null    int64
 16  DRB     220 non-null    int64
 17  TRB     220 non-null    int64
 18  AST     220 non-null    int64
 19  STL     220 non-null    int64
 20  BLK     220 non-null    int64
 21  TOV     220 non-null    int64
 22  PF      220 non-null    int64
 23  PTS     220 non-null    int64
dtypes: float64(3), int64(20), str(1)
memory usage: 42.7 KB
None
              Year        Game         Win  ...         TOV          PF         PTS
count   220.000000  220.000000  220.000000  ...  220.000000  220.000000  220.000000
mean   1998.863636    3.400000    0.709091  ...   13.709091   22.859091  100.786364
std      11.310865    1.734422    0.455217  ...    3.872029    4.371259   13.314763
min    1980.000000    1.000000    0.000000  ...    4.000000   12.000000   71.000000
25%    1989.000000    2.000000    0.000000  ...   11.000000   20.000000   90.750000
50%    1999.000000    3.000000    1.000000  ...   14.000000   23.000000  101.000000
75%    2009.000000    5.000000    1.000000  ...   16.000000   26.000000  109.000000
max    2018.000000    7.000000    1.000000  ...   26.000000   33.000000  141.000000

[8 rows x 23 columns]
Year    0
Team    0
Game    0
Win     0
Home    0
MP      0
FG      0
FGA     0
FGP     0
TP      0
TPA     0
TPP     6
FT      0
FTA     0
FTP     0
ORB     0
DRB     0
TRB     0
AST     0
STL     0
BLK     0
TOV     0
PF      0
PTS     0
dtype: int64

In [5]:
print(df.dtypes)

Year      int64
Team      int64
Game      int64
Win       int64
Home      int64
MP        int64
FG        int64
FGA       int64
FGP     float64
TP        int64
TPA       int64
TPP     float64
FT        int64
FTA       int64
FTP     float64
ORB       int64
DRB       int64
TRB       int64
AST       int64
STL       int64
BLK       int64
TOV       int64
PF        int64
PTS       int64
dtype: object

In [7]:
# Remove accidental spaces from column names
df.columns = df.columns.str.strip()

# Show all available columns
print("Columns in dataset:")
print(df.columns.tolist())

# Set the correct target column name
target_column = "Champion"   # Change if needed

# Check that the column exists before using it
if target_column in df.columns:
    X = df.drop(columns=[target_column])
    y = df[target_column]

    print("Features shape:", X.shape)
    print("Target shape:", y.shape)

else:
    print(f"ERROR: '{target_column}' column not found.")
    print("Available columns are:")
    print(df.columns.tolist())

Columns in dataset:
['Year', 'Team', 'Game', 'Win', 'Home', 'MP', 'FG', 'FGA', 'FGP', 'TP', 'TPA', 'TPP', 'FT', 'FTA', 'FTP', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']
ERROR: 'Champion' column not found.
Available columns are:
['Year', 'Team', 'Game', 'Win', 'Home', 'MP', 'FG', 'FGA', 'FGP', 'TP', 'TPA', 'TPP', 'FT', 'FTA', 'FTP', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

In [11]:
print(df.columns)

Index(['Year', 'Team', 'Game', 'Win', 'Home', 'MP', 'FG', 'FGA', 'FGP', 'TP',
       'TPA', 'TPP', 'FT', 'FTA', 'FTP', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='str')

In [14]:
df.head()
df.columns

Index(['Year', 'Team', 'Game', 'Win', 'Home', 'MP', 'FG', 'FGA', 'FGP', 'TP',
       'TPA', 'TPP', 'FT', 'FTA', 'FTP', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='str')

In [18]:
print(df.columns)
df.head()

Index(['Year', 'Team', 'Game', 'Win', 'Home', 'MP', 'FG', 'FGA', 'FGP', 'TP',
       'TPA', 'TPP', 'FT', 'FTA', 'FTP', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='str')

   Year  Team  Game  Win  Home   MP  FG  ...  TRB  AST  STL  BLK  TOV  PF  PTS
0  1980     5     1    1     1  240  48  ...   43   30    5    9   17  24  109
1  1980     5     2    0     1  240  48  ...   52   32   12    7   26  27  104
2  1980     5     3    1     0  240  44  ...   56   20    5    5   20  25  111
3  1980     5     4    0     0  240  44  ...   49   23   12    6   19  22  102
4  1980     5     5    1     1  240  41  ...   56   28    7    6   21  27  108

[5 rows x 24 columns]

In [22]:
df.head()
df.columns

Index(['Year', 'Team', 'Game', 'Win', 'Home', 'MP', 'FG', 'FGA', 'FGP', 'TP',
       'TPA', 'TPP', 'FT', 'FTA', 'FTP', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='str')