In [1]:
# =====================================================
# NFL Fandom Google Trends
# K-Means Clustering + NLP Analysis
# =====================================================

# Import libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.decomposition import PCA

import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import re

nltk.download('punkt')
nltk.download('stopwords')

# -----------------------------------------------------
# Load Dataset
# -----------------------------------------------------

df = pd.read_csv("NFL_fandom_data-google_trends.csv")

df.head()

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Unnamed: 0,Pct. Of major sports searches,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,DMA,NFL,NBA,MLB,NHL,NASCAR,CBB,CFB,Trump 2016 Vote%
1,Abilene-Sweetwater TX,45%,21%,14%,2%,4%,3%,11%,79.13%
2,Albany GA,32%,30%,9%,1%,8%,3%,17%,59.12%
3,Albany-Schenectady-Troy NY,40%,20%,20%,8%,6%,3%,4%,44.11%
4,Albuquerque-Santa Fe NM,53%,21%,11%,3%,3%,4%,6%,39.58%

In [2]:
# Dataset Information

df.info()

df.describe()

df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     208 non-null    str
 1   Pct. Of major sports searches  208 non-null    str
 2   Unnamed: 2                     208 non-null    str
 3   Unnamed: 3                     208 non-null    str
 4   Unnamed: 4                     208 non-null    str
 5   Unnamed: 5                     208 non-null    str
 6   Unnamed: 6                     208 non-null    str
 7   Unnamed: 7                     208 non-null    str
 8   Unnamed: 8                     208 non-null    str
dtypes: str(9)
memory usage: 23.3 KB

Unnamed: 0                       0
Pct. Of major sports searches    0
Unnamed: 2                       0
Unnamed: 3                       0
Unnamed: 4                       0
Unnamed: 5                       0
Unnamed: 6                       0
Unnamed: 7                       0
Unnamed: 8                       0
dtype: int64

In [5]:
df.head()

,Unnamed: 0,Pct. Of major sports searches,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,DMA,NFL,NBA,MLB,NHL,NASCAR,CBB,CFB,Trump 2016 Vote%
1,Abilene-Sweetwater TX,45%,21%,14%,2%,4%,3%,11%,79.13%
2,Albany GA,32%,30%,9%,1%,8%,3%,17%,59.12%
3,Albany-Schenectady-Troy NY,40%,20%,20%,8%,6%,3%,4%,44.11%
4,Albuquerque-Santa Fe NM,53%,21%,11%,3%,3%,4%,6%,39.58%

In [7]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['Unnamed: 0', 'Pct. Of major sports searches', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8'],
      dtype='str')

In [9]:
print(df.columns.tolist())

['Unnamed: 0', 'Pct. Of major sports searches', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']

In [10]:
df.head()

,Unnamed: 0,Pct. Of major sports searches,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,DMA,NFL,NBA,MLB,NHL,NASCAR,CBB,CFB,Trump 2016 Vote%
1,Abilene-Sweetwater TX,45%,21%,14%,2%,4%,3%,11%,79.13%
2,Albany GA,32%,30%,9%,1%,8%,3%,17%,59.12%
3,Albany-Schenectady-Troy NY,40%,20%,20%,8%,6%,3%,4%,44.11%
4,Albuquerque-Santa Fe NM,53%,21%,11%,3%,3%,4%,6%,39.58%

In [11]:
df.head()

,Unnamed: 0,Pct. Of major sports searches,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,DMA,NFL,NBA,MLB,NHL,NASCAR,CBB,CFB,Trump 2016 Vote%
1,Abilene-Sweetwater TX,45%,21%,14%,2%,4%,3%,11%,79.13%
2,Albany GA,32%,30%,9%,1%,8%,3%,17%,59.12%
3,Albany-Schenectady-Troy NY,40%,20%,20%,8%,6%,3%,4%,44.11%
4,Albuquerque-Santa Fe NM,53%,21%,11%,3%,3%,4%,6%,39.58%

In [12]:
df.to_csv("NFL_fandom_clusters.csv", index=False)

print("Clustered dataset saved successfully.")

Clustered dataset saved successfully.