In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# NLP
import re
import string
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# ML
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

In [2]:
df = pd.read_csv("Starbucks satisfactory survey.csv")

df.head()

                      Timestamp  ... 20. Will you continue buying at Starbucks?
0  2019/10/01 12:38:43 PM GMT+8  ...                                        Yes
1  2019/10/01 12:38:54 PM GMT+8  ...                                        Yes
2  2019/10/01 12:38:56 PM GMT+8  ...                                        Yes
3  2019/10/01 12:39:08 PM GMT+8  ...                                         No
4  2019/10/01 12:39:20 PM GMT+8  ...                                        Yes

[5 rows x 21 columns]

In [3]:
print(df.info())
print(df.isnull().sum())

df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 21 columns):
 #   Column                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                  --------------  -----
 0   Timestamp                                                                                                               122 non-null    str
 1   1. Your Gender                                                                                                          122 non-null    str
 2   2. Your Age                                                                                                             122 non-null    str
 3   3. Are you currently....?                                                                                               122 non-null    str
 4   4. What is your annual income?                                                                                          122 non-null    str
 5   5. How often do you visit Starbucks?                                                                                    122 non-null    str
 6   6. How do you usually enjoy Starbucks?                                                                                  121 non-null    str
 7   7. How much time do you normally  spend during your visit?                                                              122 non-null    str
 8   8. The nearest Starbucks's outlet to you is...?                                                                         122 non-null    str
 9   9. Do you have Starbucks membership card?                                                                               122 non-null    str
 10  10. What do you most frequently purchase at Starbucks?                                                                  122 non-null    str
 11  11. On average, how much would you spend at Starbucks per visit?                                                        122 non-null    str
 12  12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:  122 non-null    int64
 13  13. How would you rate the price range at Starbucks?                                                                    122 non-null    int64
 14  14. How important are sales and promotions in your purchase decision?                                                   122 non-null    int64
 15  15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)                                             122 non-null    int64
 16  16. You rate the WiFi quality at Starbucks as..                                                                         122 non-null    int64
 17  17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)                                      122 non-null    int64
 18  18. How likely you will choose Starbucks for doing business meetings or hangout with friends?                           122 non-null    int64
 19  19. How do you come to hear of promotions at Starbucks? Check all that apply.                                           121 non-null    str
 20  20. Will you continue buying at Starbucks?                                                                              122 non-null    str
dtypes: int64(7), str(14)
memory usage: 42.1 KB
None
Timestamp                                                                                                                 0
1. Your Gender                                                                                                            0
2. Your Age                                                                                                               0
3. Are you currently....?                                                                                                 0
4. What is your annual income?                                                                                            0
5. How often do you visit Starbucks?                                                                                      0
6. How do you usually enjoy Starbucks?                                                                                    1
7. How much time do you normally  spend during your visit?                                                                0
8. The nearest Starbucks's outlet to you is...?                                                                           0
9. Do you have Starbucks membership card?                                                                                 0
10. What do you most frequently purchase at Starbucks?                                                                    0
11. On average, how much would you spend at Starbucks per visit?                                                          0
12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:    0
13. How would you rate the price range at Starbucks?                                                                      0
14. How important are sales and promotions in your purchase decision?                                                     0
15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)                                               0
16. You rate the WiFi quality at Starbucks as..                                                                           0
17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)                                        0
18. How likely you will choose Starbucks for doing business meetings or hangout with friends?                             0
19. How do you come to hear of promotions at Starbucks? Check all that apply.                                             1
20. Will you continue buying at Starbucks?                                                                                0
dtype: int64

                           Timestamp  ... 20. Will you continue buying at Starbucks?
count                            122  ...                                        122
unique                           122  ...                                          2
top     2019/10/01 12:38:43 PM GMT+8  ...                                        Yes
freq                               1  ...                                         94
mean                             NaN  ...                                        NaN
std                              NaN  ...                                        NaN
min                              NaN  ...                                        NaN
25%                              NaN  ...                                        NaN
50%                              NaN  ...                                        NaN
75%                              NaN  ...                                        NaN
max                              NaN  ...                                        NaN

[11 rows x 21 columns]

In [5]:
print(df.columns.tolist())

['Timestamp', '1. Your Gender', '2. Your Age', '3. Are you currently....?', '4. What is your annual income?', '5. How often do you visit Starbucks?', '6. How do you usually enjoy Starbucks?', '7. How much time do you normally  spend during your visit?', "8. The nearest Starbucks's outlet to you is...?", '9. Do you have Starbucks membership card?', '10. What do you most frequently purchase at Starbucks?', '11. On average, how much would you spend at Starbucks per visit?', '12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:', '13. How would you rate the price range at Starbucks?', '14. How important are sales and promotions in your purchase decision?', '15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)', '16. You rate the WiFi quality at Starbucks as..', '17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)', '18. How likely you will choose Starbucks for doing business meetings or hangout with friends?', '19. How do you come to hear of promotions at Starbucks? Check all that apply.', '20. Will you continue buying at Starbucks?']

In [7]:
print(df.columns.tolist())

['Timestamp', '1. Your Gender', '2. Your Age', '3. Are you currently....?', '4. What is your annual income?', '5. How often do you visit Starbucks?', '6. How do you usually enjoy Starbucks?', '7. How much time do you normally  spend during your visit?', "8. The nearest Starbucks's outlet to you is...?", '9. Do you have Starbucks membership card?', '10. What do you most frequently purchase at Starbucks?', '11. On average, how much would you spend at Starbucks per visit?', '12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:', '13. How would you rate the price range at Starbucks?', '14. How important are sales and promotions in your purchase decision?', '15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)', '16. You rate the WiFi quality at Starbucks as..', '17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)', '18. How likely you will choose Starbucks for doing business meetings or hangout with friends?', '19. How do you come to hear of promotions at Starbucks? Check all that apply.', '20. Will you continue buying at Starbucks?']

In [10]:
print(df.columns)

Index(['Timestamp', '1. Your Gender', '2. Your Age',
       '3. Are you currently....?', '4. What is your annual income?',
       '5. How often do you visit Starbucks?',
       '6. How do you usually enjoy Starbucks?',
       '7. How much time do you normally  spend during your visit?',
       '8. The nearest Starbucks's outlet to you is...?',
       '9. Do you have Starbucks membership card?',
       '10. What do you most frequently purchase at Starbucks?',
       '11. On average, how much would you spend at Starbucks per visit?',
       '12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:',
       '13. How would you rate the price range at Starbucks?',
       '14. How important are sales and promotions in your purchase decision?',
       '15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)',
       '16. You rate the WiFi quality at Starbucks as..',
       '17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)',
       '18. How likely you will choose Starbucks for doing business meetings or hangout with friends?',
       '19. How do you come to hear of promotions at Starbucks? Check all that apply.',
       '20. Will you continue buying at Starbucks?'],
      dtype='str')

In [12]:
print(df.columns)

Index(['Timestamp', '1. Your Gender', '2. Your Age',
       '3. Are you currently....?', '4. What is your annual income?',
       '5. How often do you visit Starbucks?',
       '6. How do you usually enjoy Starbucks?',
       '7. How much time do you normally  spend during your visit?',
       '8. The nearest Starbucks's outlet to you is...?',
       '9. Do you have Starbucks membership card?',
       '10. What do you most frequently purchase at Starbucks?',
       '11. On average, how much would you spend at Starbucks per visit?',
       '12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:',
       '13. How would you rate the price range at Starbucks?',
       '14. How important are sales and promotions in your purchase decision?',
       '15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)',
       '16. You rate the WiFi quality at Starbucks as..',
       '17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)',
       '18. How likely you will choose Starbucks for doing business meetings or hangout with friends?',
       '19. How do you come to hear of promotions at Starbucks? Check all that apply.',
       '20. Will you continue buying at Starbucks?'],
      dtype='str')

In [14]:
print(df.columns.tolist())
print("X exists:", "X" in globals())

['Timestamp', '1. Your Gender', '2. Your Age', '3. Are you currently....?', '4. What is your annual income?', '5. How often do you visit Starbucks?', '6. How do you usually enjoy Starbucks?', '7. How much time do you normally  spend during your visit?', "8. The nearest Starbucks's outlet to you is...?", '9. Do you have Starbucks membership card?', '10. What do you most frequently purchase at Starbucks?', '11. On average, how much would you spend at Starbucks per visit?', '12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:', '13. How would you rate the price range at Starbucks?', '14. How important are sales and promotions in your purchase decision?', '15. How would you rate the ambiance at Starbucks? (lighting, music, etc...)', '16. You rate the WiFi quality at Starbucks as..', '17. How would you rate the service at Starbucks? (Promptness, friendliness, etc..)', '18. How likely you will choose Starbucks for doing business meetings or hangout with friends?', '19. How do you come to hear of promotions at Starbucks? Check all that apply.', '20. Will you continue buying at Starbucks?']
X exists: False