In [1]:
# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import matplotlib.pyplot as plt

In [2]:
# =========================
# 2. Load Dataset
# =========================
df = pd.read_csv("nintendo_3ds.csv")

df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,Animal Crossing - New Leaf,2013-06-09,4.48,88,Life Simulation,Animal Crossing: New Leaf is a social simulati...,https://i.postimg.cc/yxn9KJtW/4da82dc6-f314-4a...
1,Blazblue - Continuum Shift II,2011-05-31,3.80,64,Action - Fighting - 2D,BlazBlue: Continuum Shift II contains the comp...,https://i.postimg.cc/mrwT8QHc/07e211da-41d3-4c...
2,Bravely Default,2014-02-07,4.36,85,Role Playing - Japanese Style,Square Enix's highly-acclaimed fantasy RPG bri...,https://i.postimg.cc/Cx4KQTyL/b4d30158-c516-46...
3,Bravely Second - End Layer,2016-04-06,4.32,81,Role Playing - Japanese Style,Steel yourself for the next evolution of the s...,https://i.postimg.cc/Xvz4Rns3/8b780661-8e74-4b...
4,Fantasy Life,2014-10-24,4.40,73,Role Playing,Fantasy Life is an original RPG for the Ninten...,https://i.postimg.cc/KvfSXZYV/70866da9-4dc0-44...

In [3]:
# =========================
# 3. Basic Exploration
# =========================
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(27, 7)
<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          27 non-null     str
 1   released       27 non-null     str
 2   gf_score       27 non-null     float64
 3   metascore      27 non-null     int64
 4   genre          27 non-null     str
 5   description    27 non-null     str
 6   cover_art_url  27 non-null     str
dtypes: float64(1), int64(1), str(5)
memory usage: 14.0 KB
None
        gf_score  metascore
count  27.000000  27.000000
mean    4.237407  83.481481
std     0.308826   6.658542
min     3.190000  64.000000
25%     4.125000  81.000000
50%     4.360000  85.000000
75%     4.425000  88.000000
max     4.560000  94.000000
title            0
released         0
gf_score         0
metascore        0
genre            0
description      0
cover_art_url    0
dtype: int64

In [6]:
df.dtypes

title                str
released             str
gf_score         float64
metascore          int64
genre                str
description          str
cover_art_url        str
dtype: object

In [7]:
df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,Animal Crossing - New Leaf,2013-06-09,4.48,88,Life Simulation,Animal Crossing: New Leaf is a social simulati...,https://i.postimg.cc/yxn9KJtW/4da82dc6-f314-4a...
1,Blazblue - Continuum Shift II,2011-05-31,3.80,64,Action - Fighting - 2D,BlazBlue: Continuum Shift II contains the comp...,https://i.postimg.cc/mrwT8QHc/07e211da-41d3-4c...
2,Bravely Default,2014-02-07,4.36,85,Role Playing - Japanese Style,Square Enix's highly-acclaimed fantasy RPG bri...,https://i.postimg.cc/Cx4KQTyL/b4d30158-c516-46...
3,Bravely Second - End Layer,2016-04-06,4.32,81,Role Playing - Japanese Style,Steel yourself for the next evolution of the s...,https://i.postimg.cc/Xvz4Rns3/8b780661-8e74-4b...
4,Fantasy Life,2014-10-24,4.40,73,Role Playing,Fantasy Life is an original RPG for the Ninten...,https://i.postimg.cc/KvfSXZYV/70866da9-4dc0-44...

In [9]:
df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,Animal Crossing - New Leaf,2013-06-09,4.48,88,Life Simulation,Animal Crossing: New Leaf is a social simulati...,https://i.postimg.cc/yxn9KJtW/4da82dc6-f314-4a...
1,Blazblue - Continuum Shift II,2011-05-31,3.80,64,Action - Fighting - 2D,BlazBlue: Continuum Shift II contains the comp...,https://i.postimg.cc/mrwT8QHc/07e211da-41d3-4c...
2,Bravely Default,2014-02-07,4.36,85,Role Playing - Japanese Style,Square Enix's highly-acclaimed fantasy RPG bri...,https://i.postimg.cc/Cx4KQTyL/b4d30158-c516-46...
3,Bravely Second - End Layer,2016-04-06,4.32,81,Role Playing - Japanese Style,Steel yourself for the next evolution of the s...,https://i.postimg.cc/Xvz4Rns3/8b780661-8e74-4b...
4,Fantasy Life,2014-10-24,4.40,73,Role Playing,Fantasy Life is an original RPG for the Ninten...,https://i.postimg.cc/KvfSXZYV/70866da9-4dc0-44...

In [10]:
print(df.columns)

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')

In [13]:
df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,Animal Crossing - New Leaf,2013-06-09,4.48,88,Life Simulation,Animal Crossing: New Leaf is a social simulati...,https://i.postimg.cc/yxn9KJtW/4da82dc6-f314-4a...
1,Blazblue - Continuum Shift II,2011-05-31,3.80,64,Action - Fighting - 2D,BlazBlue: Continuum Shift II contains the comp...,https://i.postimg.cc/mrwT8QHc/07e211da-41d3-4c...
2,Bravely Default,2014-02-07,4.36,85,Role Playing - Japanese Style,Square Enix's highly-acclaimed fantasy RPG bri...,https://i.postimg.cc/Cx4KQTyL/b4d30158-c516-46...
3,Bravely Second - End Layer,2016-04-06,4.32,81,Role Playing - Japanese Style,Steel yourself for the next evolution of the s...,https://i.postimg.cc/Xvz4Rns3/8b780661-8e74-4b...
4,Fantasy Life,2014-10-24,4.40,73,Role Playing,Fantasy Life is an original RPG for the Ninten...,https://i.postimg.cc/KvfSXZYV/70866da9-4dc0-44...

In [15]:
df.head()
df.columns

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')

In [17]:
df.head()
df.columns

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')