In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("SI_4_corr_pred_ref.csv")
df.head()

,Unnamed: 0,pred_species,ref_species,threshold,pred_ref_corr,ref_ref_corr,ref_ref_corr_higher0.5,station,classifier
0,1,Alnus,Alnus,0.0,0.650255,1.000000,True,Basel,2022 classifier
1,2,Alnus,Betula,0.0,0.139956,-0.210417,False,Basel,2022 classifier
2,3,Alnus,Carpinus,0.0,0.127936,-0.125223,False,Basel,2022 classifier
3,4,Alnus,Corylus,0.0,0.386939,0.572424,True,Basel,2022 classifier
4,5,Alnus,Cupressaceae,0.0,0.633641,0.444319,False,Basel,2022 classifier

In [3]:
print(df.columns)
print(df.info())

Index(['Unnamed: 0', 'pred_species', 'ref_species', 'threshold',
       'pred_ref_corr', 'ref_ref_corr', 'ref_ref_corr_higher0.5', 'station',
       'classifier'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 52800 entries, 0 to 52799
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              52800 non-null  int64
 1   pred_species            52800 non-null  str
 2   ref_species             52800 non-null  str
 3   threshold               52800 non-null  float64
 4   pred_ref_corr           47235 non-null  float64
 5   ref_ref_corr            39820 non-null  float64
 6   ref_ref_corr_higher0.5  52800 non-null  bool
 7   station                 52800 non-null  str
 8   classifier              52800 non-null  str
dtypes: bool(1), float64(3), int64(1), str(4)
memory usage: 5.0 MB
None

In [6]:
for col in df.columns:
    print(col, df[col].dtype)
    print(df[col].head(2))
    print("-" * 40)

Unnamed: 0 int64
0    1
1    2
Name: Unnamed: 0, dtype: int64
----------------------------------------
pred_species str
0    Alnus
1    Alnus
Name: pred_species, dtype: str
----------------------------------------
ref_species str
0     Alnus
1    Betula
Name: ref_species, dtype: str
----------------------------------------
threshold float64
0    0.0
1    0.0
Name: threshold, dtype: float64
----------------------------------------
pred_ref_corr float64
0    0.650255
1    0.139956
Name: pred_ref_corr, dtype: float64
----------------------------------------
ref_ref_corr float64
0    1.000000
1   -0.210417
Name: ref_ref_corr, dtype: float64
----------------------------------------
ref_ref_corr_higher0.5 bool
0     True
1    False
Name: ref_ref_corr_higher0.5, dtype: bool
----------------------------------------
station str
0    Basel
1    Basel
Name: station, dtype: str
----------------------------------------
classifier str
0    2022 classifier
1    2022 classifier
Name: classifier, dtype: str
----------------------------------------

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

# define your text data
texts = [
    "this is the first document",
    "this document is the second document",
    "and this is the third one",
    "is this the first document"
]

# create vectorizer
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

# fit and transform
X = vectorizer.fit_transform(texts)

# output shape
print(X.shape)

(4, 2)

In [11]:
import numpy as np
X = np.array(X)
print("Shape:", X.shape)
print("Dimension:", X.ndim)

Shape: ()
Dimension: 0

In [13]:
df.head()

,Unnamed: 0,pred_species,ref_species,threshold,pred_ref_corr,ref_ref_corr,ref_ref_corr_higher0.5,station,classifier
0,1,Alnus,Alnus,0.0,0.650255,1.000000,True,Basel,2022 classifier
1,2,Alnus,Betula,0.0,0.139956,-0.210417,False,Basel,2022 classifier
2,3,Alnus,Carpinus,0.0,0.127936,-0.125223,False,Basel,2022 classifier
3,4,Alnus,Corylus,0.0,0.386939,0.572424,True,Basel,2022 classifier
4,5,Alnus,Cupressaceae,0.0,0.633641,0.444319,False,Basel,2022 classifier

In [14]:
print(type(X))
print(X.shape)
print(X.dtype if hasattr(X, "dtype") else "no dtype")

<class 'numpy.ndarray'>
()
object

In [16]:
cols = [c for c in [text_column, "cluster"] if c in df.columns]
df[cols].head(10)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
print("Columns:", df.columns.tolist())
print(df.head())

Columns: ['Unnamed: 0', 'pred_species', 'ref_species', 'threshold', 'pred_ref_corr', 'ref_ref_corr', 'ref_ref_corr_higher0.5', 'station', 'classifier']
   Unnamed: 0 pred_species   ref_species  threshold  pred_ref_corr  \
0           1        Alnus         Alnus        0.0       0.650255
1           2        Alnus        Betula        0.0       0.139956
2           3        Alnus      Carpinus        0.0       0.127936
3           4        Alnus       Corylus        0.0       0.386939
4           5        Alnus  Cupressaceae        0.0       0.633641

   ref_ref_corr  ref_ref_corr_higher0.5 station       classifier
0      1.000000                    True   Basel  2022 classifier
1     -0.210417                   False   Basel  2022 classifier
2     -0.125223                   False   Basel  2022 classifier
3      0.572424                    True   Basel  2022 classifier
4      0.444319                   False   Basel  2022 classifier

In [19]:
df.to_csv("clustered_output.csv", index=False)