In [1]:
import pandas as pd
import numpy as np

# NLP tools
from sklearn.feature_extraction.text import TfidfVectorizer

# ML model
from sklearn.cluster import KMeans

# Preprocessing
import re
import string

# Visualization
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv("fr_other_years.csv")

# View data
df.head()

  original_code  ...  HCAT2_code
0           ACA  ...  3399000000
1           ACP  ...  3303120000
2           BDT  ...  3301010202
3           BUR  ...  3301099900
4           CGS  ...  3301011599

[5 rows x 7 columns]

In [3]:
print(df.info())
print(df.columns)
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   original_code    41 non-null     str
 1   original_name    41 non-null     str
 2   translated_name  39 non-null     str
 3   HCAT3_name       41 non-null     str
 4   HCAT3_code       41 non-null     int64
 5   HCAT2_name       41 non-null     str
 6   HCAT2_code       41 non-null     int64
dtypes: int64(2), str(5)
memory usage: 7.0 KB
None
Index(['original_code', 'original_name', 'translated_name', 'HCAT3_name',
       'HCAT3_code', 'HCAT2_name', 'HCAT2_code'],
      dtype='str')
original_code      0
original_name      0
translated_name    2
HCAT3_name         0
HCAT3_code         0
HCAT2_name         0
HCAT2_code         0
dtype: int64

In [5]:
for col in df.columns:
    print(repr(col))

'original_code'
'original_name'
'translated_name'
'HCAT3_name'
'HCAT3_code'
'HCAT2_name'
'HCAT2_code'

In [7]:
print(df.columns)

Index(['original_code', 'original_name', 'translated_name', 'HCAT3_name',
       'HCAT3_code', 'HCAT2_name', 'HCAT2_code'],
      dtype='str')

In [9]:
if "clean_text" in df.columns:
    X = vectorizer.fit_transform(df["clean_text"])
else:
    print("clean_text column not found")

clean_text column not found

In [12]:
print(df.head())

  original_code  ...  HCAT2_code
0           ACA  ...  3399000000
1           ACP  ...  3303120000
2           BDT  ...  3301010202
3           BUR  ...  3301099900
4           CGS  ...  3301011599

[5 rows x 7 columns]

In [14]:

df.head()

  original_code  ...  HCAT2_code
0           ACA  ...  3399000000
1           ACP  ...  3303120000
2           BDT  ...  3301010202
3           BUR  ...  3301099900
4           CGS  ...  3301011599

[5 rows x 7 columns]

In [18]:
print(hasattr(vectorizer, "vocabulary_"))

False

In [21]:
print("X" in globals())

False

In [23]:
df.head()

  original_code  ...  HCAT2_code
0           ACA  ...  3399000000
1           ACP  ...  3303120000
2           BDT  ...  3301010202
3           BUR  ...  3301099900
4           CGS  ...  3301011599

[5 rows x 7 columns]

In [24]:
df.to_csv("clustered_fr_other_years.csv", index=False)