In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

In [2]:
# Load CSV file
df = pd.read_csv("datasets.v2.csv")

# Show first rows
df.head()

,0.0.1,0.0.2,0.0.3,0.0.5,0.8.0,1.0.0,10.0.0,11.0.0,12.0.0,13.0.0,...,physicalSampleAvailability,pid,populationType,publisher,releaseDate,statisticalPopulation,title,type,url,version
0,31e42cb6-b5d1-49ad-b831-c8ac4393fb72,NaN,NaN,NaN,NaN,f5b35869-1546-4d63-bede-d21607b2dc3d,NaN,NaN,NaN,NaN,...,NaN,b06415af-9151-4ccc-83a1-ab859943fb2b,NaN,ALLIANCE > HQIP,NaN,NaN,National Joint Registry - Primary Elbow Replac...,Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,2.0.0
1,292812aa-8254-4afa-9242-858e73a548cd,NaN,NaN,NaN,NaN,dde07739-b848-4a6f-8d5e-69a120331b8a,NaN,NaN,NaN,NaN,...,"SALIVA,TISSUE,WHOLE BLOOD",19fa25a7-c15d-441c-b635-ad49043e7a96,Biobank samples and data,ALLIANCE > TISSUE DIRECTORY,NaN,NaN,PTCL Biobank,Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,3.0.0
2,8c07035d-b072-48a5-921f-6fb14096703b,NaN,NaN,NaN,NaN,275d26b4-c0bd-47dc-b4fc-19440b94ea9c,NaN,NaN,NaN,NaN,...,"CDNA/MRNA,TISSUE",399a6d67-7577-4476-a3b6-4bbceb5a8ff7,Biobank samples and data,ALLIANCE > TISSUE DIRECTORY,NaN,NaN,Human Developmental Biology Resource (HDBR),Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,3.0.0
3,0f2acd6c-a774-46ec-9e73-bccc997073c5,NaN,NaN,NaN,NaN,e6b66a6f-3f4a-4f88-9fdf-639220251693,NaN,NaN,NaN,NaN,...,NOT AVAILABLE,56130df6-1880-4600-a7a4-afa9a4bcc895,Adults,HUB > BREATHE,NaN,NaN,Estimating Chronic Respiratory Disease burden ...,Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,2.0.0
4,b63ca8b7-f763-4185-82e1-9ebbdd12eb98,NaN,NaN,NaN,NaN,79ccc583-45d9-4054-927c-9e6e3b3212c5,NaN,NaN,NaN,NaN,...,NaN,4ca76471-6970-4ad4-87c7-fae77a98cbf5,NaN,ALLIANCE > HQIP,NaN,NaN,Paediatric Intensive Care Audit Network - core...,Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,2.0.0

In [4]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['0.0.1', '0.0.2', '0.0.3', '0.0.5', '0.8.0', '1.0.0', '10.0.0',
       '11.0.0', '12.0.0', '13.0.0', '14.0.0', '15.0.0', '16.0.0', '17.0.0',
       '18.0.0', '2.0.0', '3.0.0', '4.0.0', '5.0.0', '6.0.0', '7.0.0', '8.0.0',
       '9.0.0', 'abstract', 'accessRequestCost', 'accessRequestDuration',
       'accessRights', 'ageBand', 'aliases', 'author', 'citations',
       'conformsTo', 'contactPoint', 'controlledVocabulary', 'creator',
       'dataClassesCount', 'dataController', 'dataElementsCount',
       'dataProcessor', 'dataType', 'datasetEndDate', 'datasetStartDate',
       'derivedDatasets', 'description', 'doi', 'domainType', 'editable',
       'fileSize', 'finalised', 'format', 'geographicCoverage', 'group', 'id',
       'identifier', 'issued', 'jurisdiction', 'keywords', 'label', 'language',
       'lastUpdated', 'latest', 'license', 'linkedDataset', 'maxMultiplicity',
       'minMultiplicity', 'modified', 'name', 'organisation', 'periodicity',
       'physicalSampleAvailability', 'pid', 'populationType', 'publisher',
       'releaseDate', 'statisticalPopulation', 'title', 'type', 'url',
       'version'],
      dtype='str')

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

texts = [
    "Machine learning is fun",
    "Natural language processing uses text",
    "TF-IDF converts text into numbers"
]

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

X = vectorizer.fit_transform(texts)

print("Shape:", X.shape)

Shape: (3, 12)

In [9]:

df.head()

,0.0.1,0.0.2,0.0.3,0.0.5,0.8.0,1.0.0,10.0.0,11.0.0,12.0.0,13.0.0,...,physicalSampleAvailability,pid,populationType,publisher,releaseDate,statisticalPopulation,title,type,url,version
0,31e42cb6-b5d1-49ad-b831-c8ac4393fb72,NaN,NaN,NaN,NaN,f5b35869-1546-4d63-bede-d21607b2dc3d,NaN,NaN,NaN,NaN,...,NaN,b06415af-9151-4ccc-83a1-ab859943fb2b,NaN,ALLIANCE > HQIP,NaN,NaN,National Joint Registry - Primary Elbow Replac...,Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,2.0.0
1,292812aa-8254-4afa-9242-858e73a548cd,NaN,NaN,NaN,NaN,dde07739-b848-4a6f-8d5e-69a120331b8a,NaN,NaN,NaN,NaN,...,"SALIVA,TISSUE,WHOLE BLOOD",19fa25a7-c15d-441c-b635-ad49043e7a96,Biobank samples and data,ALLIANCE > TISSUE DIRECTORY,NaN,NaN,PTCL Biobank,Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,3.0.0
2,8c07035d-b072-48a5-921f-6fb14096703b,NaN,NaN,NaN,NaN,275d26b4-c0bd-47dc-b4fc-19440b94ea9c,NaN,NaN,NaN,NaN,...,"CDNA/MRNA,TISSUE",399a6d67-7577-4476-a3b6-4bbceb5a8ff7,Biobank samples and data,ALLIANCE > TISSUE DIRECTORY,NaN,NaN,Human Developmental Biology Resource (HDBR),Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,3.0.0
3,0f2acd6c-a774-46ec-9e73-bccc997073c5,NaN,NaN,NaN,NaN,e6b66a6f-3f4a-4f88-9fdf-639220251693,NaN,NaN,NaN,NaN,...,NOT AVAILABLE,56130df6-1880-4600-a7a4-afa9a4bcc895,Adults,HUB > BREATHE,NaN,NaN,Estimating Chronic Respiratory Disease burden ...,Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,2.0.0
4,b63ca8b7-f763-4185-82e1-9ebbdd12eb98,NaN,NaN,NaN,NaN,79ccc583-45d9-4054-927c-9e6e3b3212c5,NaN,NaN,NaN,NaN,...,NaN,4ca76471-6970-4ad4-87c7-fae77a98cbf5,NaN,ALLIANCE > HQIP,NaN,NaN,Paediatric Intensive Care Audit Network - core...,Data Asset,https://raw.githubusercontent.com/HDRUK/schema...,2.0.0

In [11]:
df.columns

Index(['0.0.1', '0.0.2', '0.0.3', '0.0.5', '0.8.0', '1.0.0', '10.0.0',
       '11.0.0', '12.0.0', '13.0.0', '14.0.0', '15.0.0', '16.0.0', '17.0.0',
       '18.0.0', '2.0.0', '3.0.0', '4.0.0', '5.0.0', '6.0.0', '7.0.0', '8.0.0',
       '9.0.0', 'abstract', 'accessRequestCost', 'accessRequestDuration',
       'accessRights', 'ageBand', 'aliases', 'author', 'citations',
       'conformsTo', 'contactPoint', 'controlledVocabulary', 'creator',
       'dataClassesCount', 'dataController', 'dataElementsCount',
       'dataProcessor', 'dataType', 'datasetEndDate', 'datasetStartDate',
       'derivedDatasets', 'description', 'doi', 'domainType', 'editable',
       'fileSize', 'finalised', 'format', 'geographicCoverage', 'group', 'id',
       'identifier', 'issued', 'jurisdiction', 'keywords', 'label', 'language',
       'lastUpdated', 'latest', 'license', 'linkedDataset', 'maxMultiplicity',
       'minMultiplicity', 'modified', 'name', 'organisation', 'periodicity',
       'physicalSampleAvailability', 'pid', 'populationType', 'publisher',
       'releaseDate', 'statisticalPopulation', 'title', 'type', 'url',
       'version'],
      dtype='str')

In [13]:
hasattr(kmeans, "cluster_centers_")

False

In [15]:
print(X.shape)
print(df.shape)
print(X_pca.shape)

(3, 12)
(605, 79)
(3, 2)

In [17]:
print(X.shape)
print(X_pca.shape)
print(df.shape)
print(df.columns)

(3, 12)
(3, 2)
(605, 79)
Index(['0.0.1', '0.0.2', '0.0.3', '0.0.5', '0.8.0', '1.0.0', '10.0.0',
       '11.0.0', '12.0.0', '13.0.0', '14.0.0', '15.0.0', '16.0.0', '17.0.0',
       '18.0.0', '2.0.0', '3.0.0', '4.0.0', '5.0.0', '6.0.0', '7.0.0', '8.0.0',
       '9.0.0', 'abstract', 'accessRequestCost', 'accessRequestDuration',
       'accessRights', 'ageBand', 'aliases', 'author', 'citations',
       'conformsTo', 'contactPoint', 'controlledVocabulary', 'creator',
       'dataClassesCount', 'dataController', 'dataElementsCount',
       'dataProcessor', 'dataType', 'datasetEndDate', 'datasetStartDate',
       'derivedDatasets', 'description', 'doi', 'domainType', 'editable',
       'fileSize', 'finalised', 'format', 'geographicCoverage', 'group', 'id',
       'identifier', 'issued', 'jurisdiction', 'keywords', 'label', 'language',
       'lastUpdated', 'latest', 'license', 'linkedDataset', 'maxMultiplicity',
       'minMultiplicity', 'modified', 'name', 'organisation', 'periodicity',
       'physicalSampleAvailability', 'pid', 'populationType', 'publisher',
       'releaseDate', 'statisticalPopulation', 'title', 'type', 'url',
       'version'],
      dtype='str')

In [18]:
df.to_csv("clustered_output.csv", index=False)
print("Saved as clustered_output.csv")

Saved as clustered_output.csv