In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("oil-dataset.csv")

df.head()

   Report Number  Supplemental Number  ...  Other Costs All Costs
0       20100016                17305  ...          0.0      1627
1       20100254                17331  ...          0.0      4008
2       20100038                17747  ...          0.0       200
3       20100260                18574  ...          0.0     11540
4       20100030                16276  ...          0.0     29650

[5 rows x 48 columns]

In [3]:
print(df.info())
print(df.columns)
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 2795 entries, 0 to 2794
Data columns (total 48 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Report Number                         2795 non-null   int64
 1   Supplemental Number                   2795 non-null   int64
 2   Accident Year                         2795 non-null   int64
 3   Accident Date/Time                    2795 non-null   str
 4   Operator ID                           2795 non-null   int64
 5   Operator Name                         2795 non-null   str
 6   Pipeline/Facility Name                2674 non-null   str
 7   Pipeline Location                     2795 non-null   str
 8   Pipeline Type                         2777 non-null   str
 9   Liquid Type                           2795 non-null   str
 10  Liquid Subtype                        1349 non-null   str
 11  Liquid Name                           222 non-null    str
 12  Accident City                         2480 non-null   str
 13  Accident County                       2720 non-null   str
 14  Accident State                        2783 non-null   str
 15  Accident Latitude                     2795 non-null   float64
 16  Accident Longitude                    2795 non-null   float64
 17  Cause Category                        2795 non-null   str
 18  Cause Subcategory                     2795 non-null   str
 19  Unintentional Release (Barrels)       2795 non-null   float64
 20  Intentional Release (Barrels)         1209 non-null   float64
 21  Liquid Recovery (Barrels)             2795 non-null   float64
 22  Net Loss (Barrels)                    2795 non-null   float64
 23  Liquid Ignition                       2795 non-null   str
 24  Liquid Explosion                      2795 non-null   str
 25  Pipeline Shutdown                     2583 non-null   str
 26  Shutdown Date/Time                    1390 non-null   str
 27  Restart Date/Time                     1341 non-null   str
 28  Public Evacuations                    2338 non-null   float64
 29  Operator Employee Injuries            12 non-null     float64
 30  Operator Contractor Injuries          12 non-null     float64
 31  Emergency Responder Injuries          12 non-null     float64
 32  Other Injuries                        12 non-null     float64
 33  Public Injuries                       12 non-null     float64
 34  All Injuries                          12 non-null     float64
 35  Operator Employee Fatalities          8 non-null      float64
 36  Operator Contractor Fatalities        8 non-null      float64
 37  Emergency Responder Fatalities        8 non-null      float64
 38  Other Fatalities                      8 non-null      float64
 39  Public Fatalities                     8 non-null      float64
 40  All Fatalities                        8 non-null      float64
 41  Property Damage Costs                 2788 non-null   float64
 42  Lost Commodity Costs                  2791 non-null   float64
 43  Public/Private Property Damage Costs  2785 non-null   float64
 44  Emergency Response Costs              2789 non-null   float64
 45  Environmental Remediation Costs       2787 non-null   float64
 46  Other Costs                           2779 non-null   float64
 47  All Costs                             2795 non-null   int64
dtypes: float64(25), int64(5), str(18)
memory usage: 1.6 MB
None
Index(['Report Number', 'Supplemental Number', 'Accident Year',
       'Accident Date/Time', 'Operator ID', 'Operator Name',
       'Pipeline/Facility Name', 'Pipeline Location', 'Pipeline Type',
       'Liquid Type', 'Liquid Subtype', 'Liquid Name', 'Accident City',
       'Accident County', 'Accident State', 'Accident Latitude',
       'Accident Longitude', 'Cause Category', 'Cause Subcategory',
       'Unintentional Release (Barrels)', 'Intentional Release (Barrels)',
       'Liquid Recovery (Barrels)', 'Net Loss (Barrels)', 'Liquid Ignition',
       'Liquid Explosion', 'Pipeline Shutdown', 'Shutdown Date/Time',
       'Restart Date/Time', 'Public Evacuations', 'Operator Employee Injuries',
       'Operator Contractor Injuries', 'Emergency Responder Injuries',
       'Other Injuries', 'Public Injuries', 'All Injuries',
       'Operator Employee Fatalities', 'Operator Contractor Fatalities',
       'Emergency Responder Fatalities', 'Other Fatalities',
       'Public Fatalities', 'All Fatalities', 'Property Damage Costs',
       'Lost Commodity Costs', 'Public/Private Property Damage Costs',
       'Emergency Response Costs', 'Environmental Remediation Costs',
       'Other Costs', 'All Costs'],
      dtype='str')
Report Number                              0
Supplemental Number                        0
Accident Year                              0
Accident Date/Time                         0
Operator ID                                0
Operator Name                              0
Pipeline/Facility Name                   121
Pipeline Location                          0
Pipeline Type                             18
Liquid Type                                0
Liquid Subtype                          1446
Liquid Name                             2573
Accident City                            315
Accident County                           75
Accident State                            12
Accident Latitude                          0
Accident Longitude                         0
Cause Category                             0
Cause Subcategory                          0
Unintentional Release (Barrels)            0
Intentional Release (Barrels)           1586
Liquid Recovery (Barrels)                  0
Net Loss (Barrels)                         0
Liquid Ignition                            0
Liquid Explosion                           0
Pipeline Shutdown                        212
Shutdown Date/Time                      1405
Restart Date/Time                       1454
Public Evacuations                       457
Operator Employee Injuries              2783
Operator Contractor Injuries            2783
Emergency Responder Injuries            2783
Other Injuries                          2783
Public Injuries                         2783
All Injuries                            2783
Operator Employee Fatalities            2787
Operator Contractor Fatalities          2787
Emergency Responder Fatalities          2787
Other Fatalities                        2787
Public Fatalities                       2787
All Fatalities                          2787
Property Damage Costs                      7
Lost Commodity Costs                       4
Public/Private Property Damage Costs      10
Emergency Response Costs                   6
Environmental Remediation Costs            8
Other Costs                               16
All Costs                                  0
dtype: int64

In [6]:
[c for c in df.columns if "text" in c.lower()]

[]

In [11]:
[c for c in df.columns if "text" in c.lower()]

[]

In [13]:
print(df.columns)
df.head()

Index(['Report Number', 'Supplemental Number', 'Accident Year',
       'Accident Date/Time', 'Operator ID', 'Operator Name',
       'Pipeline/Facility Name', 'Pipeline Location', 'Pipeline Type',
       'Liquid Type', 'Liquid Subtype', 'Liquid Name', 'Accident City',
       'Accident County', 'Accident State', 'Accident Latitude',
       'Accident Longitude', 'Cause Category', 'Cause Subcategory',
       'Unintentional Release (Barrels)', 'Intentional Release (Barrels)',
       'Liquid Recovery (Barrels)', 'Net Loss (Barrels)', 'Liquid Ignition',
       'Liquid Explosion', 'Pipeline Shutdown', 'Shutdown Date/Time',
       'Restart Date/Time', 'Public Evacuations', 'Operator Employee Injuries',
       'Operator Contractor Injuries', 'Emergency Responder Injuries',
       'Other Injuries', 'Public Injuries', 'All Injuries',
       'Operator Employee Fatalities', 'Operator Contractor Fatalities',
       'Emergency Responder Fatalities', 'Other Fatalities',
       'Public Fatalities', 'All Fatalities', 'Property Damage Costs',
       'Lost Commodity Costs', 'Public/Private Property Damage Costs',
       'Emergency Response Costs', 'Environmental Remediation Costs',
       'Other Costs', 'All Costs'],
      dtype='str')

   Report Number  Supplemental Number  ...  Other Costs All Costs
0       20100016                17305  ...          0.0      1627
1       20100254                17331  ...          0.0      4008
2       20100038                17747  ...          0.0       200
3       20100260                18574  ...          0.0     11540
4       20100030                16276  ...          0.0     29650

[5 rows x 48 columns]

In [15]:
df.columns
df.head()

   Report Number  Supplemental Number  ...  Other Costs All Costs
0       20100016                17305  ...          0.0      1627
1       20100254                17331  ...          0.0      4008
2       20100038                17747  ...          0.0       200
3       20100260                18574  ...          0.0     11540
4       20100030                16276  ...          0.0     29650

[5 rows x 48 columns]

In [17]:
print(df.columns)
df.head()

Index(['Report Number', 'Supplemental Number', 'Accident Year',
       'Accident Date/Time', 'Operator ID', 'Operator Name',
       'Pipeline/Facility Name', 'Pipeline Location', 'Pipeline Type',
       'Liquid Type', 'Liquid Subtype', 'Liquid Name', 'Accident City',
       'Accident County', 'Accident State', 'Accident Latitude',
       'Accident Longitude', 'Cause Category', 'Cause Subcategory',
       'Unintentional Release (Barrels)', 'Intentional Release (Barrels)',
       'Liquid Recovery (Barrels)', 'Net Loss (Barrels)', 'Liquid Ignition',
       'Liquid Explosion', 'Pipeline Shutdown', 'Shutdown Date/Time',
       'Restart Date/Time', 'Public Evacuations', 'Operator Employee Injuries',
       'Operator Contractor Injuries', 'Emergency Responder Injuries',
       'Other Injuries', 'Public Injuries', 'All Injuries',
       'Operator Employee Fatalities', 'Operator Contractor Fatalities',
       'Emergency Responder Fatalities', 'Other Fatalities',
       'Public Fatalities', 'All Fatalities', 'Property Damage Costs',
       'Lost Commodity Costs', 'Public/Private Property Damage Costs',
       'Emergency Response Costs', 'Environmental Remediation Costs',
       'Other Costs', 'All Costs'],
      dtype='str')

   Report Number  Supplemental Number  ...  Other Costs All Costs
0       20100016                17305  ...          0.0      1627
1       20100254                17331  ...          0.0      4008
2       20100038                17747  ...          0.0       200
3       20100260                18574  ...          0.0     11540
4       20100030                16276  ...          0.0     29650

[5 rows x 48 columns]

In [20]:

print(hasattr(vectorizer, "vocabulary_"))
print(hasattr(kmeans, "cluster_centers_"))

False
False