In [1]:
import pandas as pd
import numpy as np

# NLP
import re
import string
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# ML
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
df = pd.read_csv("pizza_sales_data.csv")
df.info()

,order_details_id,order_id,pizza_id,quantity,size,price,total_price,name,pizza_type_id,category,ingredients,order_time
0,1,1,hawaiian_m,1,Medium,13.25,13.25,The Hawaiian Pizza,hawaiian,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",2015-01-01 11:38:36
1,2,2,classic_dlx_m,1,Medium,16.00,16.00,The Classic Deluxe Pizza,classic_dlx,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2015-01-01 11:57:40
2,3,2,five_cheese_l,1,Large,18.50,18.50,The Five Cheese Pizza,five_cheese,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2015-01-01 11:57:40
3,4,2,ital_supr_l,1,Large,20.75,20.75,The Italian Supreme Pizza,ital_supr,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2015-01-01 11:57:40
4,5,2,mexicana_m,1,Medium,16.00,16.00,The Mexicana Pizza,mexicana,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-01-01 11:57:40

In [3]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  str
 3   quantity          48620 non-null  int64
 4   size              48620 non-null  str
 5   price             48620 non-null  float64
 6   total_price       48620 non-null  float64
 7   name              48620 non-null  str
 8   pizza_type_id     48620 non-null  str
 9   category          48620 non-null  str
 10  ingredients       48620 non-null  str
 11  order_time        48620 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 11.1 MB

order_details_id    0
order_id            0
pizza_id            0
quantity            0
size                0
price               0
total_price         0
name                0
pizza_type_id       0
category            0
ingredients         0
order_time          0
dtype: int64

In [5]:
print(df.head())
print(df.columns.tolist())

   order_details_id  order_id       pizza_id  quantity    size  price  \
0                 1         1     hawaiian_m         1  Medium  13.25
1                 2         2  classic_dlx_m         1  Medium  16.00
2                 3         2  five_cheese_l         1   Large  18.50
3                 4         2    ital_supr_l         1   Large  20.75
4                 5         2     mexicana_m         1  Medium  16.00

   total_price                       name pizza_type_id category  \
0        13.25         The Hawaiian Pizza      hawaiian  Classic
1        16.00   The Classic Deluxe Pizza   classic_dlx  Classic
2        18.50      The Five Cheese Pizza   five_cheese   Veggie
3        20.75  The Italian Supreme Pizza     ital_supr  Supreme
4        16.00         The Mexicana Pizza      mexicana   Veggie

                                         ingredients           order_time
0           Sliced Ham, Pineapple, Mozzarella Cheese  2015-01-01 11:38:36
1  Pepperoni, Mushrooms, Red Onions, Red Peppers,...  2015-01-01 11:57:40
2  Mozzarella Cheese, Provolone Cheese, Smoked Go...  2015-01-01 11:57:40
3  Calabrese Salami, Capocollo, Tomatoes, Red Oni...  2015-01-01 11:57:40
4  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...  2015-01-01 11:57:40
['order_details_id', 'order_id', 'pizza_id', 'quantity', 'size', 'price', 'total_price', 'name', 'pizza_type_id', 'category', 'ingredients', 'order_time']

In [7]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [10]:
df.head()

,order_details_id,order_id,pizza_id,quantity,size,price,total_price,name,pizza_type_id,category,ingredients,order_time
0,1,1,hawaiian_m,1,Medium,13.25,13.25,The Hawaiian Pizza,hawaiian,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",2015-01-01 11:38:36
1,2,2,classic_dlx_m,1,Medium,16.00,16.00,The Classic Deluxe Pizza,classic_dlx,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2015-01-01 11:57:40
2,3,2,five_cheese_l,1,Large,18.50,18.50,The Five Cheese Pizza,five_cheese,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2015-01-01 11:57:40
3,4,2,ital_supr_l,1,Large,20.75,20.75,The Italian Supreme Pizza,ital_supr,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2015-01-01 11:57:40
4,5,2,mexicana_m,1,Medium,16.00,16.00,The Mexicana Pizza,mexicana,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-01-01 11:57:40

In [11]:

df.head()

,order_details_id,order_id,pizza_id,quantity,size,price,total_price,name,pizza_type_id,category,ingredients,order_time
0,1,1,hawaiian_m,1,Medium,13.25,13.25,The Hawaiian Pizza,hawaiian,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",2015-01-01 11:38:36
1,2,2,classic_dlx_m,1,Medium,16.00,16.00,The Classic Deluxe Pizza,classic_dlx,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2015-01-01 11:57:40
2,3,2,five_cheese_l,1,Large,18.50,18.50,The Five Cheese Pizza,five_cheese,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2015-01-01 11:57:40
3,4,2,ital_supr_l,1,Large,20.75,20.75,The Italian Supreme Pizza,ital_supr,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2015-01-01 11:57:40
4,5,2,mexicana_m,1,Medium,16.00,16.00,The Mexicana Pizza,mexicana,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-01-01 11:57:40

In [13]:
print(df.head())

   order_details_id  order_id       pizza_id  quantity    size  price  \
0                 1         1     hawaiian_m         1  Medium  13.25
1                 2         2  classic_dlx_m         1  Medium  16.00
2                 3         2  five_cheese_l         1   Large  18.50
3                 4         2    ital_supr_l         1   Large  20.75
4                 5         2     mexicana_m         1  Medium  16.00

   total_price                       name pizza_type_id category  \
0        13.25         The Hawaiian Pizza      hawaiian  Classic
1        16.00   The Classic Deluxe Pizza   classic_dlx  Classic
2        18.50      The Five Cheese Pizza   five_cheese   Veggie
3        20.75  The Italian Supreme Pizza     ital_supr  Supreme
4        16.00         The Mexicana Pizza      mexicana   Veggie

                                         ingredients           order_time
0           Sliced Ham, Pineapple, Mozzarella Cheese  2015-01-01 11:38:36
1  Pepperoni, Mushrooms, Red Onions, Red Peppers,...  2015-01-01 11:57:40
2  Mozzarella Cheese, Provolone Cheese, Smoked Go...  2015-01-01 11:57:40
3  Calabrese Salami, Capocollo, Tomatoes, Red Oni...  2015-01-01 11:57:40
4  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...  2015-01-01 11:57:40
['order_details_id', 'order_id', 'pizza_id', 'quantity', 'size', 'price', 'total_price', 'name', 'pizza_type_id', 'category', 'ingredients', 'order_time']

In [15]:
print(df.columns.tolist())

['order_details_id', 'order_id', 'pizza_id', 'quantity', 'size', 'price', 'total_price', 'name', 'pizza_type_id', 'category', 'ingredients', 'order_time']