In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("pizzas.csv")

df.head()

     pizza_id pizza_type_id size  price
0   bbq_ckn_s       bbq_ckn    S  12.75
1   bbq_ckn_m       bbq_ckn    M  16.75
2   bbq_ckn_l       bbq_ckn    L  20.75
3  cali_ckn_s      cali_ckn    S  12.75
4  cali_ckn_m      cali_ckn    M  16.75

In [3]:
print(df.info())
print(df.describe())

print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pizza_id       96 non-null     str
 1   pizza_type_id  96 non-null     str
 2   size           96 non-null     str
 3   price          96 non-null     float64
dtypes: float64(1), str(3)
memory usage: 5.3 KB
None
           price
count  96.000000
mean   16.440625
std     4.090266
min     9.750000
25%    12.500000
50%    16.250000
75%    20.250000
max    35.950000
pizza_id         0
pizza_type_id    0
size             0
price            0
dtype: int64

In [4]:
# Fill missing values (simple approach)
df = df.fillna(df.median(numeric_only=True))

In [6]:
df.columns = df.columns.str.strip()

In [9]:
print(df.head())

     pizza_id pizza_type_id size  price
0   bbq_ckn_s       bbq_ckn    S  12.75
1   bbq_ckn_m       bbq_ckn    M  16.75
2   bbq_ckn_l       bbq_ckn    L  20.75
3  cali_ckn_s      cali_ckn    S  12.75
4  cali_ckn_m      cali_ckn    M  16.75

In [12]:
print(df.columns.tolist())

['pizza_id', 'pizza_type_id', 'size', 'price']

In [15]:
print(df.columns)

Index(['pizza_id', 'pizza_type_id', 'size', 'price'], dtype='str')

In [18]:
print(df.head())

     pizza_id pizza_type_id size  price
0   bbq_ckn_s       bbq_ckn    S  12.75
1   bbq_ckn_m       bbq_ckn    M  16.75
2   bbq_ckn_l       bbq_ckn    L  20.75
3  cali_ckn_s      cali_ckn    S  12.75
4  cali_ckn_m      cali_ckn    M  16.75

In [21]:
df.head()

     pizza_id pizza_type_id size  price
0   bbq_ckn_s       bbq_ckn    S  12.75
1   bbq_ckn_m       bbq_ckn    M  16.75
2   bbq_ckn_l       bbq_ckn    L  20.75
3  cali_ckn_s      cali_ckn    S  12.75
4  cali_ckn_m      cali_ckn    M  16.75