In [1]:
import pandas as pd
import numpy as np

import re
import string

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("portfolio_for_ml.csv")

df.head()

,difficulty,duration,id,reward,bogo,discount,informational,email,mobile,social,web,offer_code
0,10,7,ae264e3637204a6fb9bb56bc8210ddfd,10,1,0,0,1,1,1,0,1
1,10,5,4d5c57ea9a6940dd891ad53e9dbe8da0,10,1,0,0,1,1,1,1,2
2,0,4,3f207df678b143eea3cee63160fa8bed,0,0,0,1,1,1,0,1,3
3,5,7,9b98b8c7a33c4b65b9aebfe6a799e6d9,5,1,0,0,1,1,0,1,4
4,20,10,0b1e1539f2cc45b7b9fa7c272da2e1d7,5,0,1,0,1,0,0,1,5

In [3]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   difficulty     10 non-null     int64
 1   duration       10 non-null     int64
 2   id             10 non-null     str
 3   reward         10 non-null     int64
 4   bogo           10 non-null     int64
 5   discount       10 non-null     int64
 6   informational  10 non-null     int64
 7   email          10 non-null     int64
 8   mobile         10 non-null     int64
 9   social         10 non-null     int64
 10  web            10 non-null     int64
 11  offer_code     10 non-null     int64
dtypes: int64(11), str(1)
memory usage: 1.4 KB
None
difficulty       0
duration         0
id               0
reward           0
bogo             0
discount         0
informational    0
email            0
mobile           0
social           0
web              0
offer_code       0
dtype: int64

In [6]:
df.head()

,difficulty,duration,id,reward,bogo,discount,informational,email,mobile,social,web,offer_code
0,10,7,ae264e3637204a6fb9bb56bc8210ddfd,10,1,0,0,1,1,1,0,1
1,10,5,4d5c57ea9a6940dd891ad53e9dbe8da0,10,1,0,0,1,1,1,1,2
2,0,4,3f207df678b143eea3cee63160fa8bed,0,0,0,1,1,1,0,1,3
3,5,7,9b98b8c7a33c4b65b9aebfe6a799e6d9,5,1,0,0,1,1,0,1,4
4,20,10,0b1e1539f2cc45b7b9fa7c272da2e1d7,5,0,1,0,1,0,0,1,5

In [8]:
print(df.head())
print(df.columns)

   difficulty  duration                                id  reward  bogo  \
0          10         7  ae264e3637204a6fb9bb56bc8210ddfd      10     1
1          10         5  4d5c57ea9a6940dd891ad53e9dbe8da0      10     1
2           0         4  3f207df678b143eea3cee63160fa8bed       0     0
3           5         7  9b98b8c7a33c4b65b9aebfe6a799e6d9       5     1
4          20        10  0b1e1539f2cc45b7b9fa7c272da2e1d7       5     0

   discount  informational  email  mobile  social  web  offer_code
0         0              0      1       1       1    0           1
1         0              0      1       1       1    1           2
2         0              1      1       1       0    1           3
3         0              0      1       1       0    1           4
4         1              0      1       0       0    1           5
Index(['difficulty', 'duration', 'id', 'reward', 'bogo', 'discount',
       'informational', 'email', 'mobile', 'social', 'web', 'offer_code'],
      dtype='str')

In [10]:
print(df.columns)

Index(['difficulty', 'duration', 'id', 'reward', 'bogo', 'discount',
       'informational', 'email', 'mobile', 'social', 'web', 'offer_code'],
      dtype='str')

In [11]:
df.head()

,difficulty,duration,id,reward,bogo,discount,informational,email,mobile,social,web,offer_code
0,10,7,ae264e3637204a6fb9bb56bc8210ddfd,10,1,0,0,1,1,1,0,1
1,10,5,4d5c57ea9a6940dd891ad53e9dbe8da0,10,1,0,0,1,1,1,1,2
2,0,4,3f207df678b143eea3cee63160fa8bed,0,0,0,1,1,1,0,1,3
3,5,7,9b98b8c7a33c4b65b9aebfe6a799e6d9,5,1,0,0,1,1,0,1,4
4,20,10,0b1e1539f2cc45b7b9fa7c272da2e1d7,5,0,1,0,1,0,0,1,5

In [12]:
df.to_csv("portfolio_with_clusters.csv", index=False)