In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("production_staff.csv")

# Preview data
df.head()

,Employee Name,Race Desc,Date of Hire,TermDate,Reason for Term,Employment Status,Department,Position,Pay,Manager Name,Performance Score,Abutments/Hour Wk 1,Abutments/Hour Wk 2,Daily Error Rate,90-day Complaints
0,"Albert, Michael",White,8/1/2011,NaN,N/A - still employed,Active,Production,Production Manager,$54.50,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
1,"Bozzi, Charles",Asian,9/30/2013,8/7/2014,retiring,Voluntarily Terminated,Production,Production Manager,$50.50,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
2,"Butler, Webster L",White,1/28/2016,NaN,N/A - still employed,Active,Production,Production Manager,$55.00,Elisa Bramante,Exceeds,0.0,0.0,0.0,0.0
3,"Dunn, Amy",White,9/18/2014,NaN,N/A - still employed,Active,Production,Production Manager,$51.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
4,"Gray, Elijiah",White,6/2/2015,NaN,N/A - still employed,Active,Production,Production Manager,$54.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0

In [3]:
print(df.info())
print(df.isnull().sum())

df.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee Name        209 non-null    str
 1   Race Desc            209 non-null    str
 2   Date of Hire         209 non-null    str
 3   TermDate             83 non-null     str
 4   Reason for Term      209 non-null    str
 5   Employment Status    209 non-null    str
 6   Department           209 non-null    str
 7   Position             209 non-null    str
 8   Pay                  209 non-null    str
 9   Manager Name         209 non-null    str
 10  Performance Score    209 non-null    str
 11  Abutments/Hour Wk 1  208 non-null    float64
 12  Abutments/Hour Wk 2  208 non-null    float64
 13  Daily Error Rate     208 non-null    float64
 14  90-day Complaints    208 non-null    float64
dtypes: float64(4), str(11)
memory usage: 59.0 KB
None
Employee Name           47
Race Desc               47
Date of Hire            47
TermDate               173
Reason for Term         47
Employment Status       47
Department              47
Position                47
Pay                     47
Manager Name            47
Performance Score       47
Abutments/Hour Wk 1     48
Abutments/Hour Wk 2     48
Daily Error Rate        48
90-day Complaints       48
dtype: int64

,Employee Name,Race Desc,Date of Hire,TermDate,Reason for Term,Employment Status,Department,Position,Pay,Manager Name,Performance Score,Abutments/Hour Wk 1,Abutments/Hour Wk 2,Daily Error Rate,90-day Complaints
0,"Albert, Michael",White,8/1/2011,NaN,N/A - still employed,Active,Production,Production Manager,$54.50,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
1,"Bozzi, Charles",Asian,9/30/2013,8/7/2014,retiring,Voluntarily Terminated,Production,Production Manager,$50.50,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
2,"Butler, Webster L",White,1/28/2016,NaN,N/A - still employed,Active,Production,Production Manager,$55.00,Elisa Bramante,Exceeds,0.0,0.0,0.0,0.0
3,"Dunn, Amy",White,9/18/2014,NaN,N/A - still employed,Active,Production,Production Manager,$51.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
4,"Gray, Elijiah",White,6/2/2015,NaN,N/A - still employed,Active,Production,Production Manager,$54.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
5,"Hogland, Jonathan",White,1/10/2011,12/12/2015,attendance,Terminated for Cause,Production,Production Manager,$48.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
6,"Immediato, Walter",Asian,2/21/2011,9/24/2012,unhappy,Voluntarily Terminated,Production,Production Manager,$42.00,Elisa Bramante,Needs Improvement,0.0,0.0,0.0,0.0
7,"Liebig, Ketsia",White,9/30/2013,NaN,N/A - still employed,Active,Production,Production Manager,$55.00,Elisa Bramante,Exceeds,0.0,0.0,0.0,0.0
8,"Miller, Brannon",Hispanic,8/16/2012,NaN,N/A - still employed,Active,Production,Production Manager,$53.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
9,"Peterson, Ebonee",White,10/25/2010,5/18/2016,Another position,Voluntarily Terminated,Production,Production Manager,$38.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0

In [5]:
print(df.columns)

Index(['Employee Name', 'Race Desc', 'Date of Hire', 'TermDate',
       'Reason for Term', 'Employment Status', 'Department', 'Position', 'Pay',
       'Manager Name', 'Performance Score', 'Abutments/Hour Wk 1',
       'Abutments/Hour Wk 2', 'Daily Error Rate', '90-day Complaints'],
      dtype='str')

In [7]:
df.head()

,Employee Name,Race Desc,Date of Hire,TermDate,Reason for Term,Employment Status,Department,Position,Pay,Manager Name,Performance Score,Abutments/Hour Wk 1,Abutments/Hour Wk 2,Daily Error Rate,90-day Complaints
0,"Albert, Michael",White,8/1/2011,NaN,N/A - still employed,Active,Production,Production Manager,$54.50,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
1,"Bozzi, Charles",Asian,9/30/2013,8/7/2014,retiring,Voluntarily Terminated,Production,Production Manager,$50.50,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
2,"Butler, Webster L",White,1/28/2016,NaN,N/A - still employed,Active,Production,Production Manager,$55.00,Elisa Bramante,Exceeds,0.0,0.0,0.0,0.0
3,"Dunn, Amy",White,9/18/2014,NaN,N/A - still employed,Active,Production,Production Manager,$51.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
4,"Gray, Elijiah",White,6/2/2015,NaN,N/A - still employed,Active,Production,Production Manager,$54.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0

In [8]:
df.head()

,Employee Name,Race Desc,Date of Hire,TermDate,Reason for Term,Employment Status,Department,Position,Pay,Manager Name,Performance Score,Abutments/Hour Wk 1,Abutments/Hour Wk 2,Daily Error Rate,90-day Complaints
0,"Albert, Michael",White,8/1/2011,NaN,N/A - still employed,Active,Production,Production Manager,$54.50,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
1,"Bozzi, Charles",Asian,9/30/2013,8/7/2014,retiring,Voluntarily Terminated,Production,Production Manager,$50.50,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
2,"Butler, Webster L",White,1/28/2016,NaN,N/A - still employed,Active,Production,Production Manager,$55.00,Elisa Bramante,Exceeds,0.0,0.0,0.0,0.0
3,"Dunn, Amy",White,9/18/2014,NaN,N/A - still employed,Active,Production,Production Manager,$51.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0
4,"Gray, Elijiah",White,6/2/2015,NaN,N/A - still employed,Active,Production,Production Manager,$54.00,Elisa Bramante,Fully Meets,0.0,0.0,0.0,0.0

In [9]:
df.to_csv("production_staff_clustered.csv", index=False)
print("Saved clustered dataset.")

Saved clustered dataset.