In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluation
from sklearn.metrics import silhouette_score

In [2]:
# Load CSV file
df = pd.read_csv("promotergene.csv")

# Display first rows
df.head()

,Class,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V49,V50,V51,V52,V53,V54,V55,V56,V57,V58
0,1,g,c,c,t,t,c,t,c,c,...,a,a,a,c,c,t,a,a,a,t
1,1,a,t,g,c,a,a,t,t,t,...,g,c,t,a,c,t,t,g,a,t
2,1,c,c,g,t,t,t,a,t,t,...,c,g,c,c,c,t,c,g,a,t
3,1,t,c,t,c,a,a,c,g,t,...,c,c,g,c,t,t,c,c,c,g
4,1,t,a,g,g,c,a,c,c,c,...,t,g,g,a,a,t,t,g,t,g

In [3]:
# Check columns
df.columns

Index(['Class', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58'],
      dtype='str')

In [4]:
df.head()

,Class,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V49,V50,V51,V52,V53,V54,V55,V56,V57,V58
0,1,g,c,c,t,t,c,t,c,c,...,a,a,a,c,c,t,a,a,a,t
1,1,a,t,g,c,a,a,t,t,t,...,g,c,t,a,c,t,t,g,a,t
2,1,c,c,g,t,t,t,a,t,t,...,c,g,c,c,c,t,c,g,a,t
3,1,t,c,t,c,a,a,c,g,t,...,c,c,g,c,t,t,c,c,c,g
4,1,t,a,g,g,c,a,c,c,c,...,t,g,g,a,a,t,t,g,t,g

In [6]:
print(df.head())
print(df.columns)

   Class V2 V3 V4 V5 V6 V7 V8 V9 V10  ... V49 V50 V51 V52 V53 V54 V55 V56 V57  \
0      1  g  c  c  t  t  c  t  c   c  ...   a   a   a   c   c   t   a   a   a
1      1  a  t  g  c  a  a  t  t   t  ...   g   c   t   a   c   t   t   g   a
2      1  c  c  g  t  t  t  a  t   t  ...   c   g   c   c   c   t   c   g   a
3      1  t  c  t  c  a  a  c  g   t  ...   c   c   g   c   t   t   c   c   c
4      1  t  a  g  g  c  a  c  c   c  ...   t   g   g   a   a   t   t   g   t

  V58
0   t
1   t
2   t
3   g
4   g

[5 rows x 58 columns]
Index(['Class', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58'],
      dtype='str')

In [8]:


df.head()

,Class,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V49,V50,V51,V52,V53,V54,V55,V56,V57,V58
0,1,g,c,c,t,t,c,t,c,c,...,a,a,a,c,c,t,a,a,a,t
1,1,a,t,g,c,a,a,t,t,t,...,g,c,t,a,c,t,t,g,a,t
2,1,c,c,g,t,t,t,a,t,t,...,c,g,c,c,c,t,c,g,a,t
3,1,t,c,t,c,a,a,c,g,t,...,c,c,g,c,t,t,c,c,c,g
4,1,t,a,g,g,c,a,c,c,c,...,t,g,g,a,a,t,t,g,t,g

In [10]:
df.columns

Index(['Class', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58'],
      dtype='str')

In [11]:
df.to_csv(
    "promotergene_kmeans_clusters.csv",
    index=False
)

print("File saved successfully!")

File saved successfully!