In [1]:
# ============================================
# 1. IMPORT LIBRARIES
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Display settings
pd.set_option("display.max_columns", None)

# ============================================
# 2. LOAD DATASET
# ============================================

file_path = "qsar_fish_toxicity.csv"

df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (907, 1)

    3.26;0.829;1.676;0;1;1.453;3.770
0   2.189;0.58;0.863;0;0;1.348;3.115
1  2.125;0.638;0.831;0;0;1.348;3.531
2  3.027;0.331;1.472;1;0;1.807;3.510
3   2.094;0.827;0.86;0;0;1.886;5.390
4  3.222;0.331;2.177;0;0;0.706;1.819

In [2]:
# Dataset information
print("\nDataset Information:")
df.info()

# Descriptive statistics
print("\nDescriptive Statistics:")
display(df.describe(include="all"))

# Missing values
print("\nMissing Values:")
display(df.isnull().sum())

# Duplicate rows
print("\nNumber of duplicate rows:", df.duplicated().sum())

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 907 entries, 0 to 906
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   3.26;0.829;1.676;0;1;1.453;3.770  907 non-null    str
dtypes: str(1)
memory usage: 35.9 KB

Descriptive Statistics:

        3.26;0.829;1.676;0;1;1.453;3.770
count                                907
unique                               906
top     2.508;0.58;0.941;0;0;1.701;3.799
freq                                   2

Missing Values:

3.26;0.829;1.676;0;1;1.453;3.770    0
dtype: int64

Number of duplicate rows: 1

In [3]:
# Remove duplicate rows
df = df.drop_duplicates().reset_index(drop=True)

# Separate numeric and non-numeric columns
numeric_columns = df.select_dtypes(include=np.number).columns.tolist()
categorical_columns = df.select_dtypes(exclude=np.number).columns.tolist()

print("Numeric columns:")
print(numeric_columns)

print("\nNon-numeric columns:")
print(categorical_columns)

Numeric columns:
[]

Non-numeric columns:
['3.26;0.829;1.676;0;1;1.453;3.770']