In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP libraries
import nltk
import re
import string

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
df = pd.read_csv("reddit_metrics.csv")

df.head()

,Name,Year,Total Posts,Total Comments,Total Scores,Avg Comments Per Post,Avg Score Per Post
0,2024 World Series Game 1,2024,10,5,10,0.500000,1.000000
1,2024 World Series Game 2,2024,15,2,45,0.133333,3.000000
2,2024 World Series Game 3,2024,4,1042,31,260.500000,7.750000
3,2024 World Series Game 4,2024,16,710,1309,44.375000,81.812500
4,2024 World Series Game 5,2024,14,60,685,4.285714,48.928571

In [4]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   22 non-null     str
 1   Year                   22 non-null     int64
 2   Total Posts            22 non-null     int64
 3   Total Comments         22 non-null     int64
 4   Total Scores           22 non-null     int64
 5   Avg Comments Per Post  22 non-null     float64
 6   Avg Score Per Post     22 non-null     float64
dtypes: float64(2), int64(4), str(1)
memory usage: 1.8 KB

In [5]:
df.columns.tolist()

['Name',
 'Year',
 'Total Posts',
 'Total Comments',
 'Total Scores',
 'Avg Comments Per Post',
 'Avg Score Per Post']

In [6]:
stop_words = set(stopwords.words('english'))

lemmatizer = WordNetLemmatizer()


def clean_text(text):
    
    # Convert to lowercase
    text = str(text).lower()
    
    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)
    
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    
    # Remove punctuation
    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )
    
    # Tokenize
    words = text.split()
    
    # Remove stopwords and lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]
    
    return " ".join(words)

In [8]:
df.head()

,Name,Year,Total Posts,Total Comments,Total Scores,Avg Comments Per Post,Avg Score Per Post
0,2024 World Series Game 1,2024,10,5,10,0.500000,1.000000
1,2024 World Series Game 2,2024,15,2,45,0.133333,3.000000
2,2024 World Series Game 3,2024,4,1042,31,260.500000,7.750000
3,2024 World Series Game 4,2024,16,710,1309,44.375000,81.812500
4,2024 World Series Game 5,2024,14,60,685,4.285714,48.928571

In [9]:
df.to_csv(
    "reddit_metrics_kmeans_results.csv",
    index=False
)