In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("selected_schools_elem.csv")

# View data
df.head()

   objectid  objectid_1  input_fid  near_fid  ...  fsid  tcoid  fcoid copairid
0       236         236          0        33  ...    10      2      1        1
1     15431       15431         33        27  ...    38      1      2        1
2     12553       12553         25        33  ...    29      2      1        1
3     14525       14525         30        25  ...    37      1      2        1
4     15452       15452         33         2  ...    38      1      2        1

[5 rows x 22 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(1713, 22)
<class 'pandas.DataFrame'>
RangeIndex: 1713 entries, 0 to 1712
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   objectid       1713 non-null   int64
 1   objectid_1     1713 non-null   int64
 2   input_fid      1713 non-null   int64
 3   near_fid       1713 non-null   int64
 4   distance       1713 non-null   float64
 5   distmet        1713 non-null   float64
 6   distmiles      1713 non-null   float64
 7   from_county    1713 non-null   str
 8   fromschoolnum  1713 non-null   int64
 9   fromschool     1713 non-null   str
 10  fromlat        1713 non-null   float64
 11  fromlon        1713 non-null   float64
 12  tocounty       1713 non-null   str
 13  toschoolnum    1713 non-null   int64
 14  toschoolname   1713 non-null   str
 15  tolat          1713 non-null   float64
 16  tolon          1713 non-null   float64
 17  tsid           1713 non-null   int64
 18  fsid           1713 non-null   int64
 19  tcoid          1713 non-null   int64
 20  fcoid          1713 non-null   int64
 21  copairid       1713 non-null   int64
dtypes: float64(7), int64(11), str(4)
memory usage: 406.6 KB
None
           objectid    objectid_1  ...        fcoid     copairid
count  1.713000e+03  1.713000e+03  ...  1713.000000  1713.000000
mean   4.938562e+05  4.938562e+05  ...    30.860479   180.129597
std    3.091798e+05  3.091798e+05  ...    17.962995   105.136336
min    1.660000e+02  1.660000e+02  ...     1.000000     1.000000
25%    2.761190e+05  2.761190e+05  ...    14.000000    88.000000
50%    4.630420e+05  4.630420e+05  ...    31.000000   181.000000
75%    7.658580e+05  7.658580e+05  ...    47.000000   273.000000
max    1.017044e+06  1.017044e+06  ...    63.000000   359.000000

[8 rows x 18 columns]
objectid         0
objectid_1       0
input_fid        0
near_fid         0
distance         0
distmet          0
distmiles        0
from_county      0
fromschoolnum    0
fromschool       0
fromlat          0
fromlon          0
tocounty         0
toschoolnum      0
toschoolname     0
tolat            0
tolon            0
tsid             0
fsid             0
tcoid            0
fcoid            0
copairid         0
dtype: int64

In [6]:
df.head()

   objectid  objectid_1  input_fid  near_fid  ...  fsid  tcoid  fcoid copairid
0       236         236          0        33  ...    10      2      1        1
1     15431       15431         33        27  ...    38      1      2        1
2     12553       12553         25        33  ...    29      2      1        1
3     14525       14525         30        25  ...    37      1      2        1
4     15452       15452         33         2  ...    38      1      2        1

[5 rows x 22 columns]

In [8]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

cat_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

In [10]:
df.columns = df.columns.str.strip()

In [13]:
print(df.columns)

Index(['objectid', 'objectid_1', 'input_fid', 'near_fid', 'distance',
       'distmet', 'distmiles', 'from_county', 'fromschoolnum', 'fromschool',
       'fromlat', 'fromlon', 'tocounty', 'toschoolnum', 'toschoolname',
       'tolat', 'tolon', 'tsid', 'fsid', 'tcoid', 'fcoid', 'copairid'],
      dtype='str')

In [16]:
df.head()

   objectid  objectid_1  input_fid  near_fid  ...  fsid  tcoid  fcoid copairid
0       236         236          0        33  ...    10      2      1        1
1     15431       15431         33        27  ...    38      1      2        1
2     12553       12553         25        33  ...    29      2      1        1
3     14525       14525         30        25  ...    37      1      2        1
4     15452       15452         33         2  ...    38      1      2        1

[5 rows x 22 columns]