In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load dataset
df = pd.read_csv("seed.csv")

# View first rows
df.head()

,Transaction Name,Organization Name,Funding Type,Money Raised,Lead Investors,Announced Date,Organization Industries,Funding Stage,Pre-Money Valuation,Equity Only Funding,...,Diversity Spotlight (US Headquarters Only),Organization Revenue Range,Organization Website,Total Funding Amount,Funding Status,Number of Funding Rounds,Investor Names,Number of Partner Investors,Number of Investors,CB Rank (Funding Round)
0,Seed Round - Binske,Binske,Seed,"$80,259,714",NaN,"Jan 17, 2023","Alternative Medicine , Cannabis , Marketing , ...",Seed,NaN,Yes,...,NaN,$1M to $10M,www.binske.com/,"$80,259,714",Seed,1,NaN,NaN,NaN,"47,792"
1,Seed Round - Descope,Descope,Seed,"$53,000,000","GGV Capital , Lightspeed Venture Partners","Feb 15, 2023","Apps , Developer Platform , Information Techno...",Seed,NaN,Yes,...,NaN,NaN,www.descope.com,"$53,000,000",Seed,1,"Assaf Rappaport , Bipul Sinha , Cerca Partners...",2.0,12.0,"2,149"
2,Pre Seed Round - Homz Global,Homz Global,Pre-Seed,"$50,000,000",Nanban Ventures,"Mar 1, 2023",NaN,Seed,NaN,Yes,...,NaN,NaN,www.homzglobal.com/,"$50,000,000",Seed,1,Nanban Ventures,1.0,1.0,"11,605"
3,Seed Round - Nifter,Nifter,Seed,"$40,000,000",NaN,"Nov 29, 2022","Marketing , Marketplace , Music",Seed,NaN,Yes,...,NaN,NaN,nifter.io/,"$40,000,000",M&A,1,NaN,NaN,NaN,"54,536"
4,Seed Round - Plai Labs,Plai Labs,Seed,"$32,000,000",a16z crypto,"Jan 19, 2023","Blockchain , Internet , Social Media , Social ...",Seed,NaN,Yes,...,NaN,NaN,www.plailabs.com,"$32,000,000",Seed,1,a16z crypto,NaN,1.0,"3,458"

In [3]:
# Shape of dataset
print("Shape:", df.shape)

# Check missing values
print(df.isnull().sum())

# Dataset info
print(df.info())

Shape: (1000, 22)
Transaction Name                                0
Organization Name                               0
Funding Type                                    0
Money Raised                                    0
Lead Investors                                320
Announced Date                                  0
Organization Industries                        66
Funding Stage                                   0
Pre-Money Valuation                           958
Equity Only Funding                             0
Organization Description                        0
Organization Location                           0
Diversity Spotlight (US Headquarters Only)    907
Organization Revenue Range                    875
Organization Website                            1
Total Funding Amount                            0
Funding Status                                  4
Number of Funding Rounds                        0
Investor Names                                162
Number of Partner Investors                   462
Number of Investors                           161
CB Rank (Funding Round)                         0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Transaction Name                            1000 non-null   str
 1   Organization Name                           1000 non-null   str
 2   Funding Type                                1000 non-null   str
 3   Money Raised                                1000 non-null   str
 4   Lead Investors                              680 non-null    str
 5   Announced Date                              1000 non-null   str
 6   Organization Industries                     934 non-null    str
 7   Funding Stage                               1000 non-null   str
 8   Pre-Money Valuation                         42 non-null     str
 9   Equity Only Funding                         1000 non-null   str
 10  Organization Description                    1000 non-null   str
 11  Organization Location                       1000 non-null   str
 12  Diversity Spotlight (US Headquarters Only)  93 non-null     str
 13  Organization Revenue Range                  125 non-null    str
 14  Organization Website                        999 non-null    str
 15  Total Funding Amount                        1000 non-null   str
 16  Funding Status                              996 non-null    str
 17  Number of Funding Rounds                    1000 non-null   int64
 18  Investor Names                              838 non-null    str
 19  Number of Partner Investors                 538 non-null    float64
 20  Number of Investors                         839 non-null    float64
 21  CB Rank (Funding Round)                     1000 non-null   str
dtypes: float64(2), int64(1), str(19)
memory usage: 547.0 KB
None

In [4]:
df.head()

,Transaction Name,Organization Name,Funding Type,Money Raised,Lead Investors,Announced Date,Organization Industries,Funding Stage,Pre-Money Valuation,Equity Only Funding,...,Diversity Spotlight (US Headquarters Only),Organization Revenue Range,Organization Website,Total Funding Amount,Funding Status,Number of Funding Rounds,Investor Names,Number of Partner Investors,Number of Investors,CB Rank (Funding Round)
0,Seed Round - Binske,Binske,Seed,"$80,259,714",NaN,"Jan 17, 2023","Alternative Medicine , Cannabis , Marketing , ...",Seed,NaN,Yes,...,NaN,$1M to $10M,www.binske.com/,"$80,259,714",Seed,1,NaN,NaN,NaN,"47,792"
1,Seed Round - Descope,Descope,Seed,"$53,000,000","GGV Capital , Lightspeed Venture Partners","Feb 15, 2023","Apps , Developer Platform , Information Techno...",Seed,NaN,Yes,...,NaN,NaN,www.descope.com,"$53,000,000",Seed,1,"Assaf Rappaport , Bipul Sinha , Cerca Partners...",2.0,12.0,"2,149"
2,Pre Seed Round - Homz Global,Homz Global,Pre-Seed,"$50,000,000",Nanban Ventures,"Mar 1, 2023",NaN,Seed,NaN,Yes,...,NaN,NaN,www.homzglobal.com/,"$50,000,000",Seed,1,Nanban Ventures,1.0,1.0,"11,605"
3,Seed Round - Nifter,Nifter,Seed,"$40,000,000",NaN,"Nov 29, 2022","Marketing , Marketplace , Music",Seed,NaN,Yes,...,NaN,NaN,nifter.io/,"$40,000,000",M&A,1,NaN,NaN,NaN,"54,536"
4,Seed Round - Plai Labs,Plai Labs,Seed,"$32,000,000",a16z crypto,"Jan 19, 2023","Blockchain , Internet , Social Media , Social ...",Seed,NaN,Yes,...,NaN,NaN,www.plailabs.com,"$32,000,000",Seed,1,a16z crypto,NaN,1.0,"3,458"

In [7]:
print(df.columns)

Index(['Transaction Name', 'Organization Name', 'Funding Type', 'Money Raised',
       'Lead Investors', 'Announced Date', 'Organization Industries',
       'Funding Stage', 'Pre-Money Valuation', 'Equity Only Funding',
       'Organization Description', 'Organization Location',
       'Diversity Spotlight (US Headquarters Only)',
       'Organization Revenue Range', 'Organization Website',
       'Total Funding Amount', 'Funding Status', 'Number of Funding Rounds',
       'Investor Names', 'Number of Partner Investors', 'Number of Investors',
       'CB Rank (Funding Round)'],
      dtype='str')

In [10]:
print(df.head())
print(df.columns)

               Transaction Name Organization Name Funding Type Money Raised  \
0           Seed Round - Binske            Binske         Seed  $80,259,714
1          Seed Round - Descope           Descope         Seed  $53,000,000
2  Pre Seed Round - Homz Global       Homz Global     Pre-Seed  $50,000,000
3           Seed Round - Nifter            Nifter         Seed  $40,000,000
4        Seed Round - Plai Labs         Plai Labs         Seed  $32,000,000

                              Lead Investors Announced Date  \
0                                        NaN   Jan 17, 2023
1  GGV Capital , Lightspeed Venture Partners   Feb 15, 2023
2                            Nanban Ventures    Mar 1, 2023
3                                        NaN   Nov 29, 2022
4                                a16z crypto   Jan 19, 2023

                             Organization Industries Funding Stage  \
0  Alternative Medicine , Cannabis , Marketing , ...          Seed
1  Apps , Developer Platform , Information Techno...          Seed
2                                                NaN          Seed
3                    Marketing , Marketplace , Music          Seed
4  Blockchain , Internet , Social Media , Social ...          Seed

  Pre-Money Valuation Equity Only Funding  ...  \
0                 NaN                 Yes  ...
1                 NaN                 Yes  ...
2                 NaN                 Yes  ...
3                 NaN                 Yes  ...
4                 NaN                 Yes  ...

  Diversity Spotlight (US Headquarters Only) Organization Revenue Range  \
0                                        NaN                $1M to $10M
1                                        NaN                        NaN
2                                        NaN                        NaN
3                                        NaN                        NaN
4                                        NaN                        NaN

  Organization Website Total Funding Amount Funding Status  \
0      www.binske.com/          $80,259,714           Seed
1      www.descope.com          $53,000,000           Seed
2  www.homzglobal.com/          $50,000,000           Seed
3           nifter.io/          $40,000,000            M&A
4     www.plailabs.com          $32,000,000           Seed

  Number of Funding Rounds                                     Investor Names  \
0                        1                                                NaN
1                        1  Assaf Rappaport , Bipul Sinha , Cerca Partners...
2                        1                                    Nanban Ventures
3                        1                                                NaN
4                        1                                        a16z crypto

   Number of Partner Investors Number of Investors  CB Rank (Funding Round)
0                          NaN                 NaN                   47,792
1                          2.0                12.0                    2,149
2                          1.0                 1.0                   11,605
3                          NaN                 NaN                   54,536
4                          NaN                 1.0                    3,458

[5 rows x 22 columns]
Index(['Transaction Name', 'Organization Name', 'Funding Type', 'Money Raised',
       'Lead Investors', 'Announced Date', 'Organization Industries',
       'Funding Stage', 'Pre-Money Valuation', 'Equity Only Funding',
       'Organization Description', 'Organization Location',
       'Diversity Spotlight (US Headquarters Only)',
       'Organization Revenue Range', 'Organization Website',
       'Total Funding Amount', 'Funding Status', 'Number of Funding Rounds',
       'Investor Names', 'Number of Partner Investors', 'Number of Investors',
       'CB Rank (Funding Round)'],
      dtype='str')