In [1]:
# If needed (run once)
!pip install pandas numpy scikit-learn matplotlib seaborn nltk

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

Requirement already satisfied: pandas in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy in ./miniconda3/envs/coding/lib/python3.12/site-packages (2.4.6)
Requirement already satisfied: scikit-learn in ./miniconda3/envs/coding/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: matplotlib in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.10.9)
Requirement already satisfied: seaborn in ./miniconda3/envs/coding/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: nltk in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.9.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: click in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (2025.10.23)
Requirement already satisfied: tqdm in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
df = pd.read_csv("SI_3_metrics_area.csv")

# Show first rows
df.head()

                                                                                                                            species;model;area_sf_max;area_sf_min;area_sf_diff;area_ratio_max;area_ratio_min;area_ratio_diff;area_kendall_max;area_kendall_min;area_kendall_diff
Alnus;2022-operational;6 40395386;2  944190012;3   459763848;0 200179192;0 0751584;0   125020792;0 660251727;0 153179854;0                                        507071873.0
Alnus;2025-Beta-1;999    99987;4     678681918;995 3211881;0   237447473;0 027746082;0 209701391;0 709105855;0 052658128;0                                        656447728.0
Alnus;2025-Beta-2;8      214392028;3 12857083;5    085821198;0 056433534;0 016514065;0 039919469;0 746487595;0 261621602;0                                        484865993.0
Alnus;2025-Gamma-1;275   1265398;5   191851333;269 9346884;0   322816302;0 061385527;0 261430774;0 617598992;0 13343622;0                                         484162772.0
Alnus;2025-Gamma-2;6     138338428;2 986956854;3   151381574;0 048699592;0 014874813;0 03382478;0  748048965;0 060287855;0                                         68776111.0

In [4]:
df.info()
df.columns
df.isnull().sum()

<class 'pandas.DataFrame'>
MultiIndex: 120 entries, ('Alnus;2022-operational;6', '40395386;2', '944190012;3', '459763848;0', '200179192;0', '0751584;0', '125020792;0', '660251727;0', '153179854;0') to ('Ulmus;2025-Omega-2;0;0;0;0;0;0;0', '622798007;0', '229159402;0', '393638605', nan, nan, nan, nan, nan)
Data columns (total 1 columns):
 #   Column                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                --------------  -----
 0   species;model;area_sf_max;area_sf_min;area_sf_diff;area_ratio_max;area_ratio_min;area_ratio_diff;area_kendall_max;area_kendall_min;area_kendall_diff  96 non-null     float64
dtypes: float64(1)
memory usage: 21.2 KB

species;model;area_sf_max;area_sf_min;area_sf_diff;area_ratio_max;area_ratio_min;area_ratio_diff;area_kendall_max;area_kendall_min;area_kendall_diff    24
dtype: int64

In [6]:
print(df.columns)

Index(['species;model;area_sf_max;area_sf_min;area_sf_diff;area_ratio_max;area_ratio_min;area_ratio_diff;area_kendall_max;area_kendall_min;area_kendall_diff'], dtype='str')

In [8]:
print(df.columns)

Index(['species;model;area_sf_max;area_sf_min;area_sf_diff;area_ratio_max;area_ratio_min;area_ratio_diff;area_kendall_max;area_kendall_min;area_kendall_diff'], dtype='str')

In [11]:
print(df.columns)

Index(['species;model;area_sf_max;area_sf_min;area_sf_diff;area_ratio_max;area_ratio_min;area_ratio_diff;area_kendall_max;area_kendall_min;area_kendall_diff'], dtype='str')

In [12]:
df.head()

                                                                                                                            species;model;area_sf_max;area_sf_min;area_sf_diff;area_ratio_max;area_ratio_min;area_ratio_diff;area_kendall_max;area_kendall_min;area_kendall_diff
Alnus;2022-operational;6 40395386;2  944190012;3   459763848;0 200179192;0 0751584;0   125020792;0 660251727;0 153179854;0                                        507071873.0
Alnus;2025-Beta-1;999    99987;4     678681918;995 3211881;0   237447473;0 027746082;0 209701391;0 709105855;0 052658128;0                                        656447728.0
Alnus;2025-Beta-2;8      214392028;3 12857083;5    085821198;0 056433534;0 016514065;0 039919469;0 746487595;0 261621602;0                                        484865993.0
Alnus;2025-Gamma-1;275   1265398;5   191851333;269 9346884;0   322816302;0 061385527;0 261430774;0 617598992;0 13343622;0                                         484162772.0
Alnus;2025-Gamma-2;6     138338428;2 986956854;3   151381574;0 048699592;0 014874813;0 03382478;0  748048965;0 060287855;0                                         68776111.0

In [19]:
df.head()

                                                                                                                            species;model;area_sf_max;area_sf_min;area_sf_diff;area_ratio_max;area_ratio_min;area_ratio_diff;area_kendall_max;area_kendall_min;area_kendall_diff
Alnus;2022-operational;6 40395386;2  944190012;3   459763848;0 200179192;0 0751584;0   125020792;0 660251727;0 153179854;0                                        507071873.0
Alnus;2025-Beta-1;999    99987;4     678681918;995 3211881;0   237447473;0 027746082;0 209701391;0 709105855;0 052658128;0                                        656447728.0
Alnus;2025-Beta-2;8      214392028;3 12857083;5    085821198;0 056433534;0 016514065;0 039919469;0 746487595;0 261621602;0                                        484865993.0
Alnus;2025-Gamma-1;275   1265398;5   191851333;269 9346884;0   322816302;0 061385527;0 261430774;0 617598992;0 13343622;0                                         484162772.0
Alnus;2025-Gamma-2;6     138338428;2 986956854;3   151381574;0 048699592;0 014874813;0 03382478;0  748048965;0 060287855;0                                         68776111.0

In [26]:
df.head()
df.columns

Index(['species;model;area_sf_max;area_sf_min;area_sf_diff;area_ratio_max;area_ratio_min;area_ratio_diff;area_kendall_max;area_kendall_min;area_kendall_diff'], dtype='str')

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

text_data = [
    "The economy is improving with lower inflation",
    "Stock markets are rising due to tech gains",
    "Football teams are preparing for the season",
    "The match ended in a surprising victory",
    "New AI models are changing technology",
    "Deep learning improves natural language processing"
]

k = 2

vectorizer = TfidfVectorizer(stop_words="english")
X = vectorizer.fit_transform(text_data)

kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
kmeans.fit(X)

terms = vectorizer.get_feature_names_out()

order_centroids = kmeans.cluster_centers_.argsort()[:, ::-1]

for i in range(k):
    print(f"\nCluster {i} top words:")
    top_words = [terms[ind] for ind in order_centroids[i, :10]]
    print(top_words)

Cluster 0 top words:
['victory', 'lower', 'teams', 'surprising', 'economy', 'season', 'ended', 'football', 'preparing', 'improving']

Cluster 1 top words:
['deep', 'processing', 'improves', 'natural', 'language', 'learning', 'victory', 'lower', 'changing', 'economy']