In [1]:
# Data Handling
import pandas as pd
import numpy as np

# NLP
import nltk
import re
import string

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
# Load CSV file
df = pd.read_csv('SI_6_2022Operational.csv')

# Display first 5 rows
df.head()

,system,classifier config id,classifier config label,start time,end time,system operative,reason for non operative,dactylis,dactylis normalized count,alnus,...,fraxinus,fraxinus normalized count,pinaceae,pinaceae normalized count,platanus,platanus normalized count,cupressus,cupressus normalized count,---,--- normalized count
0,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 06:30:00 UTC,09.07.25 07:30:00 UTC,Yes,NaN,1.666667,4.0,0.000000,...,0.0,0.0,1.250000,3.0,0.0,0.0,0,0,85.000000,204.0
1,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 07:30:00 UTC,09.07.25 08:30:00 UTC,Yes,NaN,3.750000,9.0,0.416667,...,0.0,0.0,4.583333,11.0,0.0,0.0,0,0,270.416667,649.0
2,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 08:30:00 UTC,09.07.25 09:30:00 UTC,Yes,NaN,1.666667,4.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,52.916667,127.0
3,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 09:30:00 UTC,09.07.25 10:30:00 UTC,Yes,NaN,0.833333,2.0,0.000000,...,0.0,0.0,0.416667,1.0,0.0,0.0,0,0,47.083333,113.0
4,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 10:30:00 UTC,09.07.25 11:30:00 UTC,Yes,NaN,0.000000,0.0,0.000000,...,0.0,0.0,1.250000,3.0,0.0,0.0,0,0,39.583333,95.0

In [4]:
# Dataset structure
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 41 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   system                      288 non-null    str
 1   classifier config id        288 non-null    str
 2   classifier config label     288 non-null    str
 3   start time                  288 non-null    str
 4   end time                    288 non-null    str
 5   system operative            288 non-null    str
 6   reason for non operative    0 non-null      float64
 7   dactylis                    288 non-null    float64
 8   dactylis normalized count   288 non-null    float64
 9   alnus                       288 non-null    float64
 10  alnus normalized count      288 non-null    float64
 11  fagus                       288 non-null    float64
 12  fagus normalized count      288 non-null    float64
 13  taxus                       288 non-null    float64
 14  taxus normalized count      288 non-null    float64
 15  ulmus                       288 non-null    float64
 16  ulmus normalized count      288 non-null    int64
 17  water                       288 non-null    float64
 18  water normalized count      288 non-null    float64
 19  betula                      288 non-null    float64
 20  betula normalized count     288 non-null    float64
 21  corylus                     288 non-null    float64
 22  corylus normalized count    288 non-null    float64
 23  poaceae                     288 non-null    int64
 24  poaceae normalized count    288 non-null    int64
 25  populus                     288 non-null    float64
 26  populus normalized count    288 non-null    float64
 27  quercus                     288 non-null    float64
 28  quercus normalized count    288 non-null    float64
 29  carpinus                    288 non-null    int64
 30  carpinus normalized count   288 non-null    int64
 31  fraxinus                    288 non-null    float64
 32  fraxinus normalized count   288 non-null    float64
 33  pinaceae                    288 non-null    float64
 34  pinaceae normalized count   288 non-null    float64
 35  platanus                    288 non-null    float64
 36  platanus normalized count   288 non-null    float64
 37  cupressus                   288 non-null    int64
 38  cupressus normalized count  288 non-null    int64
 39  ---                         288 non-null    float64
 40  --- normalized count        288 non-null    float64
dtypes: float64(28), int64(7), str(6)
memory usage: 123.6 KB

In [6]:
df.head()

,system,classifier config id,classifier config label,start time,end time,system operative,reason for non operative,dactylis,dactylis normalized count,alnus,...,fraxinus,fraxinus normalized count,pinaceae,pinaceae normalized count,platanus,platanus normalized count,cupressus,cupressus normalized count,---,--- normalized count
0,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 06:30:00 UTC,09.07.25 07:30:00 UTC,Yes,NaN,1.666667,4.0,0.000000,...,0.0,0.0,1.250000,3.0,0.0,0.0,0,0,85.000000,204.0
1,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 07:30:00 UTC,09.07.25 08:30:00 UTC,Yes,NaN,3.750000,9.0,0.416667,...,0.0,0.0,4.583333,11.0,0.0,0.0,0,0,270.416667,649.0
2,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 08:30:00 UTC,09.07.25 09:30:00 UTC,Yes,NaN,1.666667,4.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0,0,52.916667,127.0
3,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 09:30:00 UTC,09.07.25 10:30:00 UTC,Yes,NaN,0.833333,2.0,0.000000,...,0.0,0.0,0.416667,1.0,0.0,0.0,0,0,47.083333,113.0
4,poleno-33,11ee982c-cb32-872a-bd0d-ae7b87f820b4,Model 2022 Productive,09.07.25 10:30:00 UTC,09.07.25 11:30:00 UTC,Yes,NaN,0.000000,0.0,0.000000,...,0.0,0.0,1.250000,3.0,0.0,0.0,0,0,39.583333,95.0

In [8]:
# Initialize lemmatizer
lemmatizer = WordNetLemmatizer()

# Stopwords
stop_words = set(stopwords.words('english'))

def clean_text(text):
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # Remove extra spaces
    text = text.strip()
    
    # Tokenization
    words = text.split()
    
    # Remove stopwords and lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]
    
    return ' '.join(words)

In [10]:
print(df.columns)

Index(['system', 'classifier config id', 'classifier config label',
       'start time', 'end time', 'system operative',
       'reason for non operative', 'dactylis', 'dactylis normalized count',
       'alnus', 'alnus normalized count', 'fagus', 'fagus normalized count',
       'taxus', 'taxus normalized count', 'ulmus', 'ulmus normalized count',
       'water', 'water normalized count', 'betula', 'betula normalized count',
       'corylus', 'corylus normalized count', 'poaceae',
       'poaceae normalized count', 'populus', 'populus normalized count',
       'quercus', 'quercus normalized count', 'carpinus',
       'carpinus normalized count', 'fraxinus', 'fraxinus normalized count',
       'pinaceae', 'pinaceae normalized count', 'platanus',
       'platanus normalized count', 'cupressus', 'cupressus normalized count',
       '---', '--- normalized count'],
      dtype='str')

In [12]:
'cleaned_text' in df.columns

False

In [14]:
print(df.head())
print(df.columns)

      system                  classifier config id classifier config label  \
0  poleno-33  11ee982c-cb32-872a-bd0d-ae7b87f820b4   Model 2022 Productive
1  poleno-33  11ee982c-cb32-872a-bd0d-ae7b87f820b4   Model 2022 Productive
2  poleno-33  11ee982c-cb32-872a-bd0d-ae7b87f820b4   Model 2022 Productive
3  poleno-33  11ee982c-cb32-872a-bd0d-ae7b87f820b4   Model 2022 Productive
4  poleno-33  11ee982c-cb32-872a-bd0d-ae7b87f820b4   Model 2022 Productive

              start time               end time system operative  \
0  09.07.25 06:30:00 UTC  09.07.25 07:30:00 UTC              Yes
1  09.07.25 07:30:00 UTC  09.07.25 08:30:00 UTC              Yes
2  09.07.25 08:30:00 UTC  09.07.25 09:30:00 UTC              Yes
3  09.07.25 09:30:00 UTC  09.07.25 10:30:00 UTC              Yes
4  09.07.25 10:30:00 UTC  09.07.25 11:30:00 UTC              Yes

   reason for non operative  dactylis  dactylis normalized count     alnus  \
0                       NaN  1.666667                        4.0  0.000000
1                       NaN  3.750000                        9.0  0.416667
2                       NaN  1.666667                        4.0  0.000000
3                       NaN  0.833333                        2.0  0.000000
4                       NaN  0.000000                        0.0  0.000000

   ...  fraxinus  fraxinus normalized count  pinaceae  \
0  ...       0.0                        0.0  1.250000
1  ...       0.0                        0.0  4.583333
2  ...       0.0                        0.0  0.000000
3  ...       0.0                        0.0  0.416667
4  ...       0.0                        0.0  1.250000

   pinaceae normalized count  platanus  platanus normalized count  cupressus  \
0                        3.0       0.0                        0.0          0
1                       11.0       0.0                        0.0          0
2                        0.0       0.0                        0.0          0
3                        1.0       0.0                        0.0          0
4                        3.0       0.0                        0.0          0

   cupressus normalized count         ---  --- normalized count
0                           0   85.000000                 204.0
1                           0  270.416667                 649.0
2                           0   52.916667                 127.0
3                           0   47.083333                 113.0
4                           0   39.583333                  95.0

[5 rows x 41 columns]
Index(['system', 'classifier config id', 'classifier config label',
       'start time', 'end time', 'system operative',
       'reason for non operative', 'dactylis', 'dactylis normalized count',
       'alnus', 'alnus normalized count', 'fagus', 'fagus normalized count',
       'taxus', 'taxus normalized count', 'ulmus', 'ulmus normalized count',
       'water', 'water normalized count', 'betula', 'betula normalized count',
       'corylus', 'corylus normalized count', 'poaceae',
       'poaceae normalized count', 'populus', 'populus normalized count',
       'quercus', 'quercus normalized count', 'carpinus',
       'carpinus normalized count', 'fraxinus', 'fraxinus normalized count',
       'pinaceae', 'pinaceae normalized count', 'platanus',
       'platanus normalized count', 'cupressus', 'cupressus normalized count',
       '---', '--- normalized count'],
      dtype='str')

In [16]:
from sklearn.datasets import make_blobs
X, _ = make_blobs(n_samples=300, centers=4, random_state=42)

In [18]:
print(len(df))
print(len(X))
print(len(kmeans.labels_))

288
300
300

In [20]:
[col for col in df.columns if 'clean' in col.lower()]
[col for col in df.columns if 'cluster' in col.lower()]

[]

In [22]:
from sklearn.decomposition import PCA

X_input = X.toarray() if hasattr(X, "toarray") else X

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_input)

In [23]:
df.to_csv('clustered_results.csv', index=False)

print("Clustered dataset saved successfully.")

Clustered dataset saved successfully.