In [1]:
import pandas as pd
import numpy as np

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

# Clustering
from sklearn.cluster import KMeans

# Evaluation
from sklearn.metrics import silhouette_score

# Visualization
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [3]:
import csv

with open("SI_2_metrics.csv", "r") as f:
    sample = f.read(2048)
    dialect = csv.Sniffer().sniff(sample)

df = pd.read_csv("SI_2_metrics.csv", sep=dialect.delimiter)

In [4]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   species          13200 non-null  str
 1   model            13200 non-null  str
 2   dataset          13200 non-null  str
 3   threshold        13200 non-null  str
 4   scaling_factor   7744 non-null   str
 5   season_start     7744 non-null   str
 6   season_end       7744 non-null   str
 7   mean_in_season   7744 non-null   str
 8   mean_out_season  13200 non-null  str
 9   ratio_mean       7731 non-null   str
 10  kendall_corr     11754 non-null  str
dtypes: str(11)
memory usage: 1.9 MB

species               0
model                 0
dataset               0
threshold             0
scaling_factor     5456
season_start       5456
season_end         5456
mean_in_season     5456
mean_out_season       0
ratio_mean         5469
kendall_corr       1446
dtype: int64

In [7]:
# ensure no missing values in numeric/analysis columns if needed
df = df.dropna()

# you can now use the dataset directly
print(df.head())

  species        model dataset  ... mean_out_season ratio_mean kendall_corr
0   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
1   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
2   Alnus  2025-Beta-1   Basel  ...          1,2931     0,0385        0,703
3   Alnus  2025-Beta-1   Basel  ...          1,0885     0,0335       0,7078
4   Alnus  2025-Beta-1   Basel  ...          0,8946     0,0289       0,7166

[5 rows x 11 columns]

In [9]:
print(df.columns)

Index(['species', 'model', 'dataset', 'threshold', 'scaling_factor',
       'season_start', 'season_end', 'mean_in_season', 'mean_out_season',
       'ratio_mean', 'kendall_corr'],
      dtype='str')

In [12]:
df.head()

  species        model dataset  ... mean_out_season ratio_mean kendall_corr
0   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
1   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
2   Alnus  2025-Beta-1   Basel  ...          1,2931     0,0385        0,703
3   Alnus  2025-Beta-1   Basel  ...          1,0885     0,0335       0,7078
4   Alnus  2025-Beta-1   Basel  ...          0,8946     0,0289       0,7166

[5 rows x 11 columns]

In [14]:
df.head()

  species        model dataset  ... mean_out_season ratio_mean kendall_corr
0   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
1   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
2   Alnus  2025-Beta-1   Basel  ...          1,2931     0,0385        0,703
3   Alnus  2025-Beta-1   Basel  ...          1,0885     0,0335       0,7078
4   Alnus  2025-Beta-1   Basel  ...          0,8946     0,0289       0,7166

[5 rows x 11 columns]

In [17]:
print(df.columns)

Index(['species', 'model', 'dataset', 'threshold', 'scaling_factor',
       'season_start', 'season_end', 'mean_in_season', 'mean_out_season',
       'ratio_mean', 'kendall_corr'],
      dtype='str')

In [19]:
print(df.head())
print(df.columns.tolist())

  species        model dataset  ... mean_out_season ratio_mean kendall_corr
0   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
1   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
2   Alnus  2025-Beta-1   Basel  ...          1,2931     0,0385        0,703
3   Alnus  2025-Beta-1   Basel  ...          1,0885     0,0335       0,7078
4   Alnus  2025-Beta-1   Basel  ...          0,8946     0,0289       0,7166

[5 rows x 11 columns]
['species', 'model', 'dataset', 'threshold', 'scaling_factor', 'season_start', 'season_end', 'mean_in_season', 'mean_out_season', 'ratio_mean', 'kendall_corr']

In [21]:
print(hasattr(vectorizer, "vocabulary_"))

False

In [25]:
df.head()

  species        model dataset  ... mean_out_season ratio_mean kendall_corr
0   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
1   Alnus  2025-Beta-1   Basel  ...           1,327     0,0395       0,7018
2   Alnus  2025-Beta-1   Basel  ...          1,2931     0,0385        0,703
3   Alnus  2025-Beta-1   Basel  ...          1,0885     0,0335       0,7078
4   Alnus  2025-Beta-1   Basel  ...          0,8946     0,0289       0,7166

[5 rows x 11 columns]

In [26]:
df.to_csv("SI_2_metrics_clustered.csv", index=False)