In [3]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Visualisation
import matplotlib.pyplot as plt

# Download NLP resources
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [4]:
# Load CSV file
df = pd.read_csv("horoscope_data.csv")

# Display first rows
df.head()

,date_range,current_date,description,compatibility,mood,color,lucky_number,lucky_time,sign
0,Mar 21 - Apr 20,"June 29, 2022",Money matters will be far more important now t...,Scorpio,Leading,Copper,60,9pm,aries
1,Jul 23 - Aug 22,"June 29, 2022",You may start out that long-distance chat with...,Scorpio,Smart,Brown,36,2pm,leo
2,Nov 23 - Dec 21,"June 29, 2022",The stars are feeling sexy. Get ready for a lo...,Cancer,Charming,Blue,30,10am,sagittarius
3,Apr 21 - May 20,"June 29, 2022",Anyone with an opinion different from yours wi...,Aquarius,Cautious,Peach,22,8am,taurus
4,Aug 23 - Sep 22,"June 29, 2022",If tonight doesn't find you in the arms of som...,Aries,Sweet,Red,1,6pm,virgo

In [5]:
# Example: find text column
df.columns

Index(['date_range', 'current_date', 'description', 'compatibility', 'mood',
       'color', 'lucky_number', 'lucky_time', 'sign'],
      dtype='str')

In [7]:


df.head()

,date_range,current_date,description,compatibility,mood,color,lucky_number,lucky_time,sign
0,Mar 21 - Apr 20,"June 29, 2022",Money matters will be far more important now t...,Scorpio,Leading,Copper,60,9pm,aries
1,Jul 23 - Aug 22,"June 29, 2022",You may start out that long-distance chat with...,Scorpio,Smart,Brown,36,2pm,leo
2,Nov 23 - Dec 21,"June 29, 2022",The stars are feeling sexy. Get ready for a lo...,Cancer,Charming,Blue,30,10am,sagittarius
3,Apr 21 - May 20,"June 29, 2022",Anyone with an opinion different from yours wi...,Aquarius,Cautious,Peach,22,8am,taurus
4,Aug 23 - Sep 22,"June 29, 2022",If tonight doesn't find you in the arms of som...,Aries,Sweet,Red,1,6pm,virgo

In [9]:
df.head()

,date_range,current_date,description,compatibility,mood,color,lucky_number,lucky_time,sign
0,Mar 21 - Apr 20,"June 29, 2022",Money matters will be far more important now t...,Scorpio,Leading,Copper,60,9pm,aries
1,Jul 23 - Aug 22,"June 29, 2022",You may start out that long-distance chat with...,Scorpio,Smart,Brown,36,2pm,leo
2,Nov 23 - Dec 21,"June 29, 2022",The stars are feeling sexy. Get ready for a lo...,Cancer,Charming,Blue,30,10am,sagittarius
3,Apr 21 - May 20,"June 29, 2022",Anyone with an opinion different from yours wi...,Aquarius,Cautious,Peach,22,8am,taurus
4,Aug 23 - Sep 22,"June 29, 2022",If tonight doesn't find you in the arms of som...,Aries,Sweet,Red,1,6pm,virgo

In [10]:
df.head()

,date_range,current_date,description,compatibility,mood,color,lucky_number,lucky_time,sign
0,Mar 21 - Apr 20,"June 29, 2022",Money matters will be far more important now t...,Scorpio,Leading,Copper,60,9pm,aries
1,Jul 23 - Aug 22,"June 29, 2022",You may start out that long-distance chat with...,Scorpio,Smart,Brown,36,2pm,leo
2,Nov 23 - Dec 21,"June 29, 2022",The stars are feeling sexy. Get ready for a lo...,Cancer,Charming,Blue,30,10am,sagittarius
3,Apr 21 - May 20,"June 29, 2022",Anyone with an opinion different from yours wi...,Aquarius,Cautious,Peach,22,8am,taurus
4,Aug 23 - Sep 22,"June 29, 2022",If tonight doesn't find you in the arms of som...,Aries,Sweet,Red,1,6pm,virgo

In [12]:
df.to_csv(
    "horoscope_clusters.csv",
    index=False
)

print("Saved horoscope_clusters.csv")

Saved horoscope_clusters.csv