In [1]:
# Sports Political Donations Dataset
# K-Means Clustering + NLP Analysis

# Import libraries

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP libraries
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Download NLP resources
nltk.download('stopwords')


# ---------------------------------------
# 1. Load Dataset
# ---------------------------------------

df = pd.read_csv("sports-political-donations.csv")

# Display first rows

df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Owner,Team,League,Recipient,Amount,Election Year,Party
0,Adam Silver,Commissioner,NBA,WRIGHT 2016,"$4,000",2016,Democrat
1,Adam Silver,Commissioner,NBA,BIDEN FOR PRESIDENT,"$2,800",2020,Democrat
2,Adam Silver,Commissioner,NBA,CORY 2020,"$2,700",2020,Democrat
3,Adam Silver,Commissioner,NBA,Kamala Harris for the People,"$2,700",2020,Democrat
4,Adam Silver,Commissioner,NBA,Win The Era PAC,"$2,700",2020,Democrat

In [2]:
# Sports Political Donations Dataset
# K-Means Clustering + NLP Analysis

# Import libraries

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP libraries
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Download NLP resources
nltk.download('stopwords')


# ---------------------------------------
# 1. Load Dataset
# ---------------------------------------

df = pd.read_csv("sports-political-donations.csv")

# Display first rows

df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Owner,Team,League,Recipient,Amount,Election Year,Party
0,Adam Silver,Commissioner,NBA,WRIGHT 2016,"$4,000",2016,Democrat
1,Adam Silver,Commissioner,NBA,BIDEN FOR PRESIDENT,"$2,800",2020,Democrat
2,Adam Silver,Commissioner,NBA,CORY 2020,"$2,700",2020,Democrat
3,Adam Silver,Commissioner,NBA,Kamala Harris for the People,"$2,700",2020,Democrat
4,Adam Silver,Commissioner,NBA,Win The Era PAC,"$2,700",2020,Democrat

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2798 entries, 0 to 2797
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Owner          2798 non-null   str
 1   Team           2798 non-null   str
 2   League         2798 non-null   str
 3   Recipient      2798 non-null   str
 4   Amount         2798 non-null   str
 5   Election Year  2798 non-null   int64
 6   Party          2789 non-null   str
dtypes: int64(1), str(6)
memory usage: 368.4 KB

In [4]:
df.columns

Index(['Owner', 'Team', 'League', 'Recipient', 'Amount', 'Election Year',
       'Party'],
      dtype='str')

In [5]:
# Find text columns

text_columns = df.select_dtypes(include=['object']).columns

text_columns

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_78980/3645602333.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include=['object']).columns

Index(['Owner', 'Team', 'League', 'Recipient', 'Amount', 'Party'], dtype='str')

In [7]:
df['combined_text'] = (
    df[text_columns]
    .fillna('unknown')
    .astype(str)
    .apply(lambda x: ' '.join(x), axis=1)
)

df[['combined_text']].head()

                                       combined_text
0  Adam Silver Commissioner NBA WRIGHT 2016 $4,00...
1  Adam Silver Commissioner NBA BIDEN FOR PRESIDE...
2  Adam Silver Commissioner NBA CORY 2020 $2,700 ...
3  Adam Silver Commissioner NBA Kamala Harris for...
4  Adam Silver Commissioner NBA Win The Era PAC $...

In [9]:
df.head()

,Owner,Team,League,Recipient,Amount,Election Year,Party,combined_text
0,Adam Silver,Commissioner,NBA,WRIGHT 2016,"$4,000",2016,Democrat,"Adam Silver Commissioner NBA WRIGHT 2016 $4,00..."
1,Adam Silver,Commissioner,NBA,BIDEN FOR PRESIDENT,"$2,800",2020,Democrat,Adam Silver Commissioner NBA BIDEN FOR PRESIDE...
2,Adam Silver,Commissioner,NBA,CORY 2020,"$2,700",2020,Democrat,"Adam Silver Commissioner NBA CORY 2020 $2,700 ..."
3,Adam Silver,Commissioner,NBA,Kamala Harris for the People,"$2,700",2020,Democrat,Adam Silver Commissioner NBA Kamala Harris for...
4,Adam Silver,Commissioner,NBA,Win The Era PAC,"$2,700",2020,Democrat,Adam Silver Commissioner NBA Win The Era PAC $...

In [11]:
df.to_csv(
    "sports-political-donations_clustered.csv",
    index=False
)