In [1]:
import pandas as pd
import numpy as np

import nltk
import re
import string

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import matplotlib.pyplot as plt
import seaborn as sns

from wordcloud import WordCloud

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
df = pd.read_csv("starfleet_academy_comment_history.csv")

df.head()

,snapshot_utc,post_id,post_name,subreddit,episode_code,is_episode,is_trailer,title,permalink,num_comments
0,2026-02-10T19:46:49.505203+00:00,1qxossm,t3_1qxossm,television,NaN,0,0,So... Starfleet Academy is ragebait right?,https://www.reddit.com/r/television/comments/1...,67
1,2026-02-10T19:46:49.505203+00:00,1qxj5a1,t3_1qxj5a1,television,NaN,0,0,Star Trek : Starfleet Academy - Why the hate?,https://www.reddit.com/r/television/comments/1...,51
2,2026-02-10T19:46:49.505203+00:00,1qx5d5o,t3_1qx5d5o,television,E01,1,0,Star Trek: Starfleet Academy - 1x05 - “Series ...,https://www.reddit.com/r/television/comments/1...,43
3,2026-02-10T19:46:49.505203+00:00,1qrvn9u,t3_1qrvn9u,television,E04,1,0,Welp! I just saw episode 4 of Star Trek Starfl...,https://www.reddit.com/r/television/comments/1...,16
4,2026-02-10T19:46:49.505203+00:00,1qr7018,t3_1qr7018,television,NaN,0,0,The online disourse around Star Trek: Starflee...,https://www.reddit.com/r/television/comments/1...,135

In [5]:
print(df.columns.tolist())

['snapshot_utc', 'post_id', 'post_name', 'subreddit', 'episode_code', 'is_episode', 'is_trailer', 'title', 'permalink', 'num_comments']

In [8]:
print(df.head())
print(df.columns)

                       snapshot_utc  post_id   post_name   subreddit  \
0  2026-02-10T19:46:49.505203+00:00  1qxossm  t3_1qxossm  television
1  2026-02-10T19:46:49.505203+00:00  1qxj5a1  t3_1qxj5a1  television
2  2026-02-10T19:46:49.505203+00:00  1qx5d5o  t3_1qx5d5o  television
3  2026-02-10T19:46:49.505203+00:00  1qrvn9u  t3_1qrvn9u  television
4  2026-02-10T19:46:49.505203+00:00  1qr7018  t3_1qr7018  television

  episode_code  is_episode  is_trailer  \
0          NaN           0           0
1          NaN           0           0
2          E01           1           0
3          E04           1           0
4          NaN           0           0

                                               title  \
0         So... Starfleet Academy is ragebait right?
1      Star Trek : Starfleet Academy - Why the hate?
2  Star Trek: Starfleet Academy - 1x05 - “Series ...
3  Welp! I just saw episode 4 of Star Trek Starfl...
4  The online disourse around Star Trek: Starflee...

                                           permalink  num_comments
0  https://www.reddit.com/r/television/comments/1...            67
1  https://www.reddit.com/r/television/comments/1...            51
2  https://www.reddit.com/r/television/comments/1...            43
3  https://www.reddit.com/r/television/comments/1...            16
4  https://www.reddit.com/r/television/comments/1...           135
Index(['snapshot_utc', 'post_id', 'post_name', 'subreddit', 'episode_code',
       'is_episode', 'is_trailer', 'title', 'permalink', 'num_comments'],
      dtype='str')

In [9]:
df.head()

,snapshot_utc,post_id,post_name,subreddit,episode_code,is_episode,is_trailer,title,permalink,num_comments
0,2026-02-10T19:46:49.505203+00:00,1qxossm,t3_1qxossm,television,NaN,0,0,So... Starfleet Academy is ragebait right?,https://www.reddit.com/r/television/comments/1...,67
1,2026-02-10T19:46:49.505203+00:00,1qxj5a1,t3_1qxj5a1,television,NaN,0,0,Star Trek : Starfleet Academy - Why the hate?,https://www.reddit.com/r/television/comments/1...,51
2,2026-02-10T19:46:49.505203+00:00,1qx5d5o,t3_1qx5d5o,television,E01,1,0,Star Trek: Starfleet Academy - 1x05 - “Series ...,https://www.reddit.com/r/television/comments/1...,43
3,2026-02-10T19:46:49.505203+00:00,1qrvn9u,t3_1qrvn9u,television,E04,1,0,Welp! I just saw episode 4 of Star Trek Starfl...,https://www.reddit.com/r/television/comments/1...,16
4,2026-02-10T19:46:49.505203+00:00,1qr7018,t3_1qr7018,television,NaN,0,0,The online disourse around Star Trek: Starflee...,https://www.reddit.com/r/television/comments/1...,135

In [10]:
df.to_csv(
    "starfleet_academy_comment_clusters.csv",
    index=False
)

print("Saved clustered dataset.")

Saved clustered dataset.