In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans as TextKMeans

In [2]:
df = pd.read_csv("USA-Starbucks.csv")

# Preview
df.head()

,Lng,Lat,City,Address
0,-81.56897,41.51592,USA-Cleveland Heights,Clifton Blvd. 11501 Clifton Boulevard Cleveland
1,-79.08474,33.49768,USA-Pawleys Island,Target Simpsonville T-1870 694 Fairview Road ...
2,-85.57426,38.28698,USA-Louisville,Oxmoor Center Kiosk 7900 Shelbyville Rd Louis...
3,-96.60873,33.01126,USA-Murphy,North St & West College 2021 North Street Nac...
4,-119.10229,35.33993,USA-Bakersfield,Bakersfield Marketplace 9000 Ming Avenue Bake...

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 8882 entries, 0 to 8881
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Lng      8882 non-null   float64
 1   Lat      8882 non-null   float64
 2   City     8882 non-null   str
 3   Address  8882 non-null   str
dtypes: float64(2), str(2)
memory usage: 826.8 KB

Lng        0
Lat        0
City       0
Address    0
dtype: int64

In [4]:
# Drop duplicates
df = df.drop_duplicates()

# Fill missing values (simple approach)
df = df.fillna("Unknown")

df.head()

,Lng,Lat,City,Address
0,-81.56897,41.51592,USA-Cleveland Heights,Clifton Blvd. 11501 Clifton Boulevard Cleveland
1,-79.08474,33.49768,USA-Pawleys Island,Target Simpsonville T-1870 694 Fairview Road ...
2,-85.57426,38.28698,USA-Louisville,Oxmoor Center Kiosk 7900 Shelbyville Rd Louis...
3,-96.60873,33.01126,USA-Murphy,North St & West College 2021 North Street Nac...
4,-119.10229,35.33993,USA-Bakersfield,Bakersfield Marketplace 9000 Ming Avenue Bake...

In [6]:
df.head()

,Lng,Lat,City,Address
0,-81.56897,41.51592,USA-Cleveland Heights,Clifton Blvd. 11501 Clifton Boulevard Cleveland
1,-79.08474,33.49768,USA-Pawleys Island,Target Simpsonville T-1870 694 Fairview Road ...
2,-85.57426,38.28698,USA-Louisville,Oxmoor Center Kiosk 7900 Shelbyville Rd Louis...
3,-96.60873,33.01126,USA-Murphy,North St & West College 2021 North Street Nac...
4,-119.10229,35.33993,USA-Bakersfield,Bakersfield Marketplace 9000 Ming Avenue Bake...

In [7]:
df.columns

Index(['Lng', 'Lat', 'City', 'Address'], dtype='str')

In [9]:
print(df.head())
print(df.columns.tolist())

         Lng       Lat                    City  \
0  -81.56897  41.51592   USA-Cleveland Heights
1  -79.08474  33.49768      USA-Pawleys Island
2  -85.57426  38.28698          USA-Louisville
3  -96.60873  33.01126              USA-Murphy
4 -119.10229  35.33993         USA-Bakersfield

                                             Address
0    Clifton Blvd. 11501 Clifton Boulevard Cleveland
1   Target Simpsonville T-1870 694 Fairview Road ...
2   Oxmoor Center Kiosk 7900 Shelbyville Rd Louis...
3   North St & West College 2021 North Street Nac...
4   Bakersfield Marketplace 9000 Ming Avenue Bake...
['Lng', 'Lat', 'City', 'Address']

In [10]:
df.head()

,Lng,Lat,City,Address
0,-81.56897,41.51592,USA-Cleveland Heights,Clifton Blvd. 11501 Clifton Boulevard Cleveland
1,-79.08474,33.49768,USA-Pawleys Island,Target Simpsonville T-1870 694 Fairview Road ...
2,-85.57426,38.28698,USA-Louisville,Oxmoor Center Kiosk 7900 Shelbyville Rd Louis...
3,-96.60873,33.01126,USA-Murphy,North St & West College 2021 North Street Nac...
4,-119.10229,35.33993,USA-Bakersfield,Bakersfield Marketplace 9000 Ming Avenue Bake...