In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler

# Machine Learning
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load CSV file

df = pd.read_csv("Starbucks in California - County Stats.csv")

# Display first rows

df.head()

,County,Number of Starbucks,Starbucks per million inhabitants,Starbucks per 10 sq. mile,Median Age,Median Household Income,2010 Population,Percentage of white population,Land Area (Sq. miles),Number of Starbucks (Rank),Starbucks per million inhabitants (Rank),Starbucks per sq. mile (Rank),Median Age (Rank),Median Household Income (Rank),Percentage of white population (Rank)
0,Siskiyou County,1,22.0,0.002,47.0,"$37,865","44,900",85.0,6287.0,1,4.0,1.0,47.0,3.0,45.0
1,Inyo County,2,108.0,0.002,45.6,"$49,571",18546,74.0,10203.0,8,49.0,2.0,46.0,20.0,34.0
2,Trinity County,1,73.0,0.003,49.3,"$37,672",13786,87.0,3179.0,1,35.0,3.0,52.0,2.0,50.0
3,Mono County,2,141.0,0.007,37.2,"$60,469",14202,82.0,3044.0,8,52.0,4.0,30.0,35.0,42.0
4,Lassen County,3,86.0,0.007,37.1,"$52,484",34895,73.0,4557.0,12,43.0,5.0,28.0,23.0,32.0

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   County                                    53 non-null     str
 1   Number of Starbucks                       53 non-null     int64
 2   Starbucks per million inhabitants         52 non-null     float64
 3   Starbucks per 10 sq. mile                 52 non-null     float64
 4   Median Age                                52 non-null     float64
 5   Median Household Income                   52 non-null     str
 6   2010 Population                           52 non-null     str
 7   Percentage of white population            52 non-null     float64
 8   Land Area (Sq. miles)                     52 non-null     float64
 9   Number of Starbucks (Rank)                53 non-null     int64
 10  Starbucks per million inhabitants (Rank)  52 non-null     float64
 11  Starbucks per sq. mile (Rank)             52 non-null     float64
 12  Median Age (Rank)                         52 non-null     float64
 13  Median Household Income (Rank)            52 non-null     float64
 14  Percentage of white population (Rank)     52 non-null     float64
dtypes: float64(10), int64(2), str(3)
memory usage: 7.8 KB

In [5]:


df.head()

,County,Number of Starbucks,Starbucks per million inhabitants,Starbucks per 10 sq. mile,Median Age,Median Household Income,2010 Population,Percentage of white population,Land Area (Sq. miles),Number of Starbucks (Rank),Starbucks per million inhabitants (Rank),Starbucks per sq. mile (Rank),Median Age (Rank),Median Household Income (Rank),Percentage of white population (Rank)
0,Siskiyou County,1,22.0,0.002,47.0,"$37,865","44,900",85.0,6287.0,1,4.0,1.0,47.0,3.0,45.0
1,Inyo County,2,108.0,0.002,45.6,"$49,571",18546,74.0,10203.0,8,49.0,2.0,46.0,20.0,34.0
2,Trinity County,1,73.0,0.003,49.3,"$37,672",13786,87.0,3179.0,1,35.0,3.0,52.0,2.0,50.0
3,Mono County,2,141.0,0.007,37.2,"$60,469",14202,82.0,3044.0,8,52.0,4.0,30.0,35.0,42.0
4,Lassen County,3,86.0,0.007,37.1,"$52,484",34895,73.0,4557.0,12,43.0,5.0,28.0,23.0,32.0

In [8]:
df.columns

Index(['County', 'Number of Starbucks', 'Starbucks per million inhabitants',
       'Starbucks per 10 sq. mile', 'Median Age', 'Median Household Income',
       '2010 Population', 'Percentage of white population',
       'Land Area (Sq. miles)', 'Number of Starbucks (Rank)',
       'Starbucks per million inhabitants (Rank)',
       'Starbucks per sq. mile (Rank)', 'Median Age (Rank)',
       'Median Household Income (Rank)',
       'Percentage of white population (Rank)'],
      dtype='str')

In [11]:
df.columns

Index(['County', 'Number of Starbucks', 'Starbucks per million inhabitants',
       'Starbucks per 10 sq. mile', 'Median Age', 'Median Household Income',
       '2010 Population', 'Percentage of white population',
       'Land Area (Sq. miles)', 'Number of Starbucks (Rank)',
       'Starbucks per million inhabitants (Rank)',
       'Starbucks per sq. mile (Rank)', 'Median Age (Rank)',
       'Median Household Income (Rank)',
       'Percentage of white population (Rank)'],
      dtype='str')

In [14]:
from sklearn.metrics import silhouette_score

score = silhouette_score(
    X,
    df["Cluster"]
)

print("Silhouette Score:", score)

NameError: name 'X' is not defined