In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# K-means clustering
from sklearn.cluster import KMeans

# Visualisation
import matplotlib.pyplot as plt

# Download NLP resources
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("starlog.csv")

# View first rows
df.head()

,starDate,logType,crewId,crewName,log,starfleetDateTime,earthDate
0,41153.7,CaptainsLog,1,Jean-Luc Picard,The Enterprise's has entered a new star system...,2364-01-03T10:00:00,2364-01-03
1,41254.2,FirstOfficerLog,2,William Riker,We are investigating a distress signal...,2364-02-15T14:30:00,2364-02-15
2,41456.8,ChiefMedicalOfficerLog,3,Beverly Crusher,Several crew members are experiencing...,2364-04-20T08:15:00,2364-04-20
3,41765.3,PersonalLog,4,Data,I am attempting to understand...,2364-07-10T18:00:00,2364-07-10
4,1312.4,CaptainsLog,5,Christopher Pike,Sensors have detected unusual energy readings,2254-05-12T09:00:00,2254-05-12

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   starDate           7 non-null      float64
 1   logType            7 non-null      str
 2   crewId             7 non-null      int64
 3   crewName           7 non-null      str
 4   log                7 non-null      str
 5   starfleetDateTime  7 non-null      str
 6   earthDate          7 non-null      str
dtypes: float64(1), int64(1), str(5)
memory usage: 1.2 KB

In [4]:

df.head()

,starDate,logType,crewId,crewName,log,starfleetDateTime,earthDate
0,41153.7,CaptainsLog,1,Jean-Luc Picard,The Enterprise's has entered a new star system...,2364-01-03T10:00:00,2364-01-03
1,41254.2,FirstOfficerLog,2,William Riker,We are investigating a distress signal...,2364-02-15T14:30:00,2364-02-15
2,41456.8,ChiefMedicalOfficerLog,3,Beverly Crusher,Several crew members are experiencing...,2364-04-20T08:15:00,2364-04-20
3,41765.3,PersonalLog,4,Data,I am attempting to understand...,2364-07-10T18:00:00,2364-07-10
4,1312.4,CaptainsLog,5,Christopher Pike,Sensors have detected unusual energy readings,2254-05-12T09:00:00,2254-05-12

In [6]:
print(df.columns)

Index(['starDate', 'logType', 'crewId', 'crewName', 'log', 'starfleetDateTime',
       'earthDate'],
      dtype='str')

In [7]:
df.head()

,starDate,logType,crewId,crewName,log,starfleetDateTime,earthDate
0,41153.7,CaptainsLog,1,Jean-Luc Picard,The Enterprise's has entered a new star system...,2364-01-03T10:00:00,2364-01-03
1,41254.2,FirstOfficerLog,2,William Riker,We are investigating a distress signal...,2364-02-15T14:30:00,2364-02-15
2,41456.8,ChiefMedicalOfficerLog,3,Beverly Crusher,Several crew members are experiencing...,2364-04-20T08:15:00,2364-04-20
3,41765.3,PersonalLog,4,Data,I am attempting to understand...,2364-07-10T18:00:00,2364-07-10
4,1312.4,CaptainsLog,5,Christopher Pike,Sensors have detected unusual energy readings,2254-05-12T09:00:00,2254-05-12

In [8]:
df.to_csv(
    "starlog_clustered.csv",
    index=False
)

print("Saved as starlog_clustered.csv")

Saved as starlog_clustered.csv