In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load CSV file

df = pd.read_csv("state-population.csv")

# Display first rows

df.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state/region  2544 non-null   str
 1   ages          2544 non-null   str
 2   year          2544 non-null   int64
 3   population    2524 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 99.6 KB

In [4]:
# Remove rows with missing population values

df = df.dropna()

# Reset index

df.reset_index(drop=True, inplace=True)

df.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [5]:
# Find text column

df.columns

Index(['state/region', 'ages', 'year', 'population'], dtype='str')

In [6]:
text_column = "state/region"

# Convert text to lowercase

df[text_column] = df[text_column].astype(str).str.lower()

df[text_column].head()

0    al
1    al
2    al
3    al
4    al
Name: state/region, dtype: str

In [7]:
tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=100
)

text_features = tfidf.fit_transform(
    df[text_column]
)

text_features.shape

(2524, 48)

In [8]:
df.columns

Index(['state/region', 'ages', 'year', 'population'], dtype='str')

In [10]:
df.to_csv(
    "state-population-kmeans-clusters.csv",
    index=False
)