In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
import re
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Download NLP resources
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("store-space-sales.csv")

# Display first rows
df.head()

  store  space  sales
0     A     26     65
1     B     28     65
2     C     25     62
3     D     26     59
4     E     28     69

In [3]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   store   15 non-null     str
 1   space   15 non-null     int64
 2   sales   15 non-null     int64
dtypes: int64(2), str(1)
memory usage: 507.0 bytes

In [4]:
# Check missing values
df.isnull().sum()

store    0
space    0
sales    0
dtype: int64

In [7]:
df.head()

  store  space  sales
0     A     26     65
1     B     28     65
2     C     25     62
3     D     26     59
4     E     28     69

In [8]:
df.to_csv(
    "store-space-sales_clustered.csv",
    index=False
)

print("File saved successfully")

File saved successfully