In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, classification_report

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("grades_km_input.csv")

df.head()

   Student  English  Math  Science
0        1       99    96       97
1        2       99    96       97
2        3       98    97       97
3        4       95   100       95
4        5       95    96       96

In [3]:
print(df.shape)
print(df.info())
print(df.describe(include='all'))

(620, 4)
<class 'pandas.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  620 non-null    int64
 1   English  620 non-null    int64
 2   Math     620 non-null    int64
 3   Science  620 non-null    int64
dtypes: int64(4)
memory usage: 19.5 KB
None
          Student     English        Math     Science
count  620.000000  620.000000  620.000000  620.000000
mean   310.475806   84.303226   77.877419   79.404839
std    179.082001   11.577860   12.310908   12.536047
min      1.000000   56.000000   55.000000   55.000000
25%    155.750000   78.000000   69.000000   70.000000
50%    310.500000   85.000000   78.000000   80.000000
75%    465.250000   95.000000   85.250000   90.000000
max    619.000000  100.000000  100.000000  100.000000

In [4]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [5]:
le = LabelEncoder()
y = le.fit_transform(y)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [7]:
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [9]:
import pandas as pd

print("y_train distribution:")
print(pd.Series(y_train).value_counts())

print("\ny_test distribution:")
print(pd.Series(y_test).value_counts())

print("\nPredictions distribution:")
print(pd.Series(dt_pred).value_counts())

y_train distribution:
42    22
41    21
21    20
25    19
28    18
26    18
23    16
43    16
27    15
24    14
20    14
22    13
4     13
3     12
8     12
19    11
44    11
12    11
11    10
38    10
33    10
40    10
29    10
36    10
37    10
18    10
13     9
35     9
6      9
5      8
15     8
31     8
39     8
16     8
32     8
10     7
2      7
34     7
30     7
1      6
17     6
14     6
7      6
9      5
45     4
0      4
Name: count, dtype: int64

y_test distribution:
40    7
25    7
21    7
16    6
44    6
28    6
24    5
42    5
26    5
22    5
43    5
14    4
23    3
4     3
34    3
11    3
15    3
0     3
31    3
37    3
13    2
29    2
18    2
33    2
8     2
1     2
30    2
19    2
27    2
38    2
7     2
20    2
36    1
41    1
12    1
39    1
6     1
5     1
10    1
35    1
Name: count, dtype: int64

Predictions distribution:
21    8
42    7
23    7
41    6
25    5
28    5
31    5
6     4
24    4
40    4
27    4
20    4
22    4
43    3
18    3
7     3
44    3
19    3
16    3
30    3
29    3
3     3
1     3
33    2
26    2
12    2
11    2
4     2
0     2
39    2
32    2
13    2
14    1
34    1
10    1
37    1
2     1
35    1
8     1
5     1
36    1
Name: count, dtype: int64

In [13]:
import pandas as pd

print(pd.Series(y_train).value_counts())
print(pd.Series(y_test).value_counts())
print(pd.Series(rf_pred).value_counts())

42    22
41    21
21    20
25    19
28    18
26    18
23    16
43    16
27    15
24    14
20    14
22    13
4     13
3     12
8     12
19    11
44    11
12    11
11    10
38    10
33    10
40    10
29    10
36    10
37    10
18    10
13     9
35     9
6      9
5      8
15     8
31     8
39     8
16     8
32     8
10     7
2      7
34     7
30     7
1      6
17     6
14     6
7      6
9      5
45     4
0      4
Name: count, dtype: int64
40    7
25    7
21    7
16    6
44    6
28    6
24    5
42    5
26    5
22    5
43    5
14    4
23    3
4     3
34    3
11    3
15    3
0     3
31    3
37    3
13    2
29    2
18    2
33    2
8     2
1     2
30    2
19    2
27    2
38    2
7     2
20    2
36    1
41    1
12    1
39    1
6     1
5     1
10    1
35    1
Name: count, dtype: int64
41    12
25     8
21     8
35     5
22     5
29     5
6      5
42     4
26     4
24     4
37     4
28     4
18     4
11     3
7      3
2      3
20     3
16     3
8      3
5      3
23     3
39     2
34     2
19     2
30     2
13     2
44     2
43     2
27     2
33     2
4      2
36     1
14     1
40     1
17     1
15     1
3      1
32     1
31     1
Name: count, dtype: int64

In [14]:
rf_classifier = rf_model.named_steps["classifier"]

importances = rf_classifier.feature_importances_

feature_names = X.columns

feature_importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

feature_importance_df

   Feature  Importance
0  Student    0.454815
2     Math    0.283601
1  English    0.261584