In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
df = pd.read_csv("Subbiah.csv")
df.head()

     Project  Actual des  ...  TotalLaborCost  TotalUFP
0  Project 1      106688  ...            5576       205
1  Project 2      896688  ...           29326       396
2  Project 3       77125  ...            3110       262
3  Project 4      954363  ...           27447       839
4  Project 5      171213  ...            4321       179

[5 rows x 12 columns]

In [4]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Project               72 non-null     str
 1   Actual des            72 non-null     int64
 2   Adjustment            72 non-null     float64
 3   CostPerFP             72 non-null     int64
 4   ExternalInterface     72 non-null     int64
 5   ExternalInputs        72 non-null     int64
 6   ExternalOutputs       72 non-null     int64
 7   ExternalQueries       72 non-null     int64
 8   HoursToCount          51 non-null     float64
 9   InternalLogicalFiles  72 non-null     int64
 10  TotalLaborCost        72 non-null     int64
 11  TotalUFP              72 non-null     int64
dtypes: float64(2), int64(9), str(1)
memory usage: 7.6 KB

Project                  0
Actual des               0
Adjustment               0
CostPerFP                0
ExternalInterface        0
ExternalInputs           0
ExternalOutputs          0
ExternalQueries          0
HoursToCount            21
InternalLogicalFiles     0
TotalLaborCost           0
TotalUFP                 0
dtype: int64

In [6]:
print([col for col in df.columns if "text" in col.lower()])

[]

In [7]:
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

In [10]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

# ---- Create sample data (replace this with your own dataset if needed) ----
X, _ = make_blobs(n_samples=300, centers=4, random_state=42)

# ---- Elbow method ----
wcss = []

for k in range(2, 11):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

print(wcss)

[9416.214004352274, 2110.412521895329, 564.9141808210253, 512.3903339109636, 460.3079031235534, 408.94738126415746, 360.8214343877638, 325.372688355219, 291.5608624106775]

In [13]:

df.head()

     Project  Actual des  ...  TotalLaborCost  TotalUFP
0  Project 1      106688  ...            5576       205
1  Project 2      896688  ...           29326       396
2  Project 3       77125  ...            3110       262
3  Project 4      954363  ...           27447       839
4  Project 5      171213  ...            4321       179

[5 rows x 12 columns]

In [16]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# ---- Use only numeric columns (important for KMeans) ----
X = df.select_dtypes(include="number").dropna()

# ---- Fit KMeans ----
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
labels = kmeans.fit_predict(X)

# ---- (optional) add labels back to df ----
df = df.loc[X.index].copy()
df["Cluster"] = labels

# ---- Silhouette score ----
score = silhouette_score(X, labels)

print("Silhouette Score:", score)

Silhouette Score: 0.5935402506666171

In [18]:
X_pca = pca.fit_transform(X.to_numpy())

In [19]:
X_pca = pca.fit_transform(X.values)

In [22]:
df["text"] = (
    df["Project"].astype(str) + " " +
    df["Actual des"].astype(str)
)

In [23]:
df.to_csv("Subbiah_clustered_output.csv", index=False)
print("Saved successfully!")

Saved successfully!