In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Download NLP resources
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file

df = pd.read_csv("super_bowls.csv")

# Display first rows

df.head()

,date,super_bowl,venue,city,state,attendance,team_winner,winning_pts,qb_winner_1,qb_winner_2,coach_winner,team_loser,losing_pts,qb_loser_1,qb_loser_2,coach_loser,combined_pts,difference_pts
0,2018-02-04,52,U.S. Bank Stadium,Minneapolis,Minnesota,67612,Philadelphia Eagles,41,Nick Foles,NaN,Doug Pederson,New England Patriots,33,Tom Brady,NaN,Bill Belichick,74,8
1,2017-02-05,51,NRG Stadium,Houston,Texas,70807,New England Patriots,34,Tom Brady,NaN,Bill Belichick,Atlanta Falcons,28,Matt Ryan,NaN,Dan Quinn,62,6
2,2016-02-07,50,Levi's Stadium,Santa Clara,California,71088,Denver Broncos,24,Peyton Manning,NaN,Gary Kubiak,Carolina Panthers,10,Cam Newton,NaN,Ron Rivera,34,14
3,2015-02-01,49,University of Phoenix Stadium,Glendale,Arizona,70288,New England Patriots,28,Tom Brady,NaN,Bill Belichick,Seattle Seahawks,24,Russell Wilson,NaN,Pete Carroll,52,4
4,2014-02-02,48,MetLife Stadium,East Rutherford,New Jersey,82529,Seattle Seahawks,43,Russell Wilson,NaN,Pete Carroll,Denver Broncos,8,Peyton Manning,NaN,John Fox,51,35

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            52 non-null     str
 1   super_bowl      52 non-null     int64
 2   venue           52 non-null     str
 3   city            52 non-null     str
 4   state           52 non-null     str
 5   attendance      52 non-null     int64
 6   team_winner     52 non-null     str
 7   winning_pts     52 non-null     int64
 8   qb_winner_1     52 non-null     str
 9   qb_winner_2     2 non-null      str
 10  coach_winner    52 non-null     str
 11  team_loser      52 non-null     str
 12  losing_pts      52 non-null     int64
 13  qb_loser_1      52 non-null     str
 14  qb_loser_2      3 non-null      str
 15  coach_loser     52 non-null     str
 16  combined_pts    52 non-null     int64
 17  difference_pts  52 non-null     int64
dtypes: int64(6), str(12)
memory usage: 13.7 KB

In [4]:
# Fill missing values

df = df.fillna("")

# Display columns

df.columns

Index(['date', 'super_bowl', 'venue', 'city', 'state', 'attendance',
       'team_winner', 'winning_pts', 'qb_winner_1', 'qb_winner_2',
       'coach_winner', 'team_loser', 'losing_pts', 'qb_loser_1', 'qb_loser_2',
       'coach_loser', 'combined_pts', 'difference_pts'],
      dtype='str')

In [5]:
# Select text columns

text_columns = df.select_dtypes(include=['object']).columns

text_columns

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_11178/357920368.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include=['object']).columns

Index(['date', 'venue', 'city', 'state', 'team_winner', 'qb_winner_1',
       'qb_winner_2', 'coach_winner', 'team_loser', 'qb_loser_1', 'qb_loser_2',
       'coach_loser'],
      dtype='str')

In [6]:
stop_words = set(stopwords.words("english"))

stemmer = PorterStemmer()


def clean_text(text):
    
    # Lowercase
    text = text.lower()
    
    # Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    # Tokenize
    words = text.split()
    
    # Remove stopwords and stem
    words = [
        stemmer.stem(word)
        for word in words
        if word not in stop_words
    ]
    
    return " ".join(words)

In [8]:
df.head()

,date,super_bowl,venue,city,state,attendance,team_winner,winning_pts,qb_winner_1,qb_winner_2,coach_winner,team_loser,losing_pts,qb_loser_1,qb_loser_2,coach_loser,combined_pts,difference_pts
0,2018-02-04,52,U.S. Bank Stadium,Minneapolis,Minnesota,67612,Philadelphia Eagles,41,Nick Foles,,Doug Pederson,New England Patriots,33,Tom Brady,,Bill Belichick,74,8
1,2017-02-05,51,NRG Stadium,Houston,Texas,70807,New England Patriots,34,Tom Brady,,Bill Belichick,Atlanta Falcons,28,Matt Ryan,,Dan Quinn,62,6
2,2016-02-07,50,Levi's Stadium,Santa Clara,California,71088,Denver Broncos,24,Peyton Manning,,Gary Kubiak,Carolina Panthers,10,Cam Newton,,Ron Rivera,34,14
3,2015-02-01,49,University of Phoenix Stadium,Glendale,Arizona,70288,New England Patriots,28,Tom Brady,,Bill Belichick,Seattle Seahawks,24,Russell Wilson,,Pete Carroll,52,4
4,2014-02-02,48,MetLife Stadium,East Rutherford,New Jersey,82529,Seattle Seahawks,43,Russell Wilson,,Pete Carroll,Denver Broncos,8,Peyton Manning,,John Fox,51,35

In [9]:
df.to_csv(
    "super_bowls_kmeans_clusters.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!