In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt

# Machine learning
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("timeseries.csv")

# View data
df.head()

         Date      A       B       C      D      E      F      G
0  2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
1  2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2  2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
3  2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
4  2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

In [3]:
df.info()

print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    11 non-null     str
 1   A       11 non-null     float64
 2   B       11 non-null     float64
 3   C       11 non-null     float64
 4   D       11 non-null     float64
 5   E       11 non-null     float64
 6   F       11 non-null     float64
 7   G       11 non-null     float64
dtypes: float64(7), str(1)
memory usage: 946.0 bytes
Date    0
A       0
B       0
C       0
D       0
E       0
F       0
G       0
dtype: int64

In [5]:
df.columns

Index(['Date', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='str')

In [7]:

df.head()

         Date      A       B       C      D      E      F      G
0  2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
1  2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2  2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
3  2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
4  2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

In [8]:
df.to_csv(
    "timeseries_cluster_results.csv",
    index=False
)

print("Finished")

Finished