In [1]:
# ===========================================
# NLP + K-Means Clustering on transcription.csv
# ===========================================

# Install packages (run once)
# !pip install pandas numpy matplotlib seaborn nltk scikit-learn wordcloud

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import re

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [2]:
# Load dataset
df = pd.read_csv("transcription.csv")

# Display first rows
df.head()

   start   end                                               text
0    0.0   9.0   Three men who previously served in the milita...
1    9.0  10.0                              All right, what more?
2   10.0  11.0                            Guy and the light team.
3   11.0  15.0   They have let in. Fifteen people from the pub...
4   15.0  24.0   There was David Grash, who's a former intelli...

In [4]:
print(df.info())

print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1572 entries, 0 to 1571
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   start   1572 non-null   float64
 1   end     1572 non-null   float64
 2   text    1572 non-null   str
dtypes: float64(2), str(1)
memory usage: 143.7 KB
None
start    0
end      0
text     0
dtype: int64

In [6]:

df.head()

   start   end                                               text
0    0.0   9.0   Three men who previously served in the milita...
1    9.0  10.0                              All right, what more?
2   10.0  11.0                            Guy and the light team.
3   11.0  15.0   They have let in. Fifteen people from the pub...
4   15.0  24.0   There was David Grash, who's a former intelli...

In [7]:
print(df.columns.tolist())

['start', 'end', 'text']

In [8]:
print(df.columns.tolist())

['start', 'end', 'text']

In [10]:
print(df.columns.tolist())
print(df.head())

['start', 'end', 'text']
   start   end                                               text
0    0.0   9.0   Three men who previously served in the milita...
1    9.0  10.0                              All right, what more?
2   10.0  11.0                            Guy and the light team.
3   11.0  15.0   They have let in. Fifteen people from the pub...
4   15.0  24.0   There was David Grash, who's a former intelli...

In [11]:
df.to_csv("clustered_transcription.csv", index=False)

print("Results saved successfully.")

Results saved successfully.