In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP libraries
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Visualisation
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Download NLP resources
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
# Load CSV file

df = pd.read_csv("tv_data.csv")

# Display first rows
df.head()

,Name,Teams,Start Datetime,Average Viewers (Millions)
0,2024 World Series Game 1,"Los Angeles Dodgers, New York Yankees",2024-10-25T17:11:00-07:00,14.163
1,2024 World Series Game 2,"Los Angeles Dodgers, New York Yankees",2024-10-26T17:15:00-07:00,13.713
2,2024 World Series Game 3,"Los Angeles Dodgers, New York Yankees",2024-10-28T17:17:00-07:00,13.208
3,2024 World Series Game 4,"Los Angeles Dodgers, New York Yankees",2024-10-29T17:08:00-07:00,16.275
4,2024 World Series Game 5,"Los Angeles Dodgers, New York Yankees",2024-10-30T17:08:00-07:00,18.152

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Name                        250 non-null    str
 1   Teams                       250 non-null    str
 2   Start Datetime              250 non-null    str
 3   Average Viewers (Millions)  250 non-null    float64
dtypes: float64(1), str(3)
memory usage: 28.6 KB

In [4]:
df.columns

Index(['Name', 'Teams', 'Start Datetime', 'Average Viewers (Millions)'], dtype='str')

In [6]:
df.head()

,Name,Teams,Start Datetime,Average Viewers (Millions)
0,2024 World Series Game 1,"Los Angeles Dodgers, New York Yankees",2024-10-25T17:11:00-07:00,14.163
1,2024 World Series Game 2,"Los Angeles Dodgers, New York Yankees",2024-10-26T17:15:00-07:00,13.713
2,2024 World Series Game 3,"Los Angeles Dodgers, New York Yankees",2024-10-28T17:17:00-07:00,13.208
3,2024 World Series Game 4,"Los Angeles Dodgers, New York Yankees",2024-10-29T17:08:00-07:00,16.275
4,2024 World Series Game 5,"Los Angeles Dodgers, New York Yankees",2024-10-30T17:08:00-07:00,18.152

In [8]:
print(df.columns.tolist())
print(df.head())

['Name', 'Teams', 'Start Datetime', 'Average Viewers (Millions)']
                       Name                                  Teams  \
0  2024 World Series Game 1  Los Angeles Dodgers, New York Yankees
1  2024 World Series Game 2  Los Angeles Dodgers, New York Yankees
2  2024 World Series Game 3  Los Angeles Dodgers, New York Yankees
3  2024 World Series Game 4  Los Angeles Dodgers, New York Yankees
4  2024 World Series Game 5  Los Angeles Dodgers, New York Yankees

              Start Datetime  Average Viewers (Millions)
0  2024-10-25T17:11:00-07:00                      14.163
1  2024-10-26T17:15:00-07:00                      13.713
2  2024-10-28T17:17:00-07:00                      13.208
3  2024-10-29T17:08:00-07:00                      16.275
4  2024-10-30T17:08:00-07:00                      18.152

In [9]:
df.to_csv(
    "tv_data_kmeans_clusters.csv",
    index=False
)