In [1]:
import pandas as pd
import numpy as np

import re
import string

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("uk-towns.csv")

df.head()

,id,place_name,county,country,grid_reference,easting,northing,latitude,longitude,postcode_area,type
0,1,A' Chill,Highland,Scotland,NG2605,126500,805500,57.05909,-6.51277,PH44 4,Other
1,2,Aaron's Hill,Surrey,England,SU9543,495500,143500,51.18276,-0.63503,GU7 2,Other
2,3,Ab Kettleby,Leicestershire,England,SK7223,472500,323500,52.80419,-0.92601,LE14 3,Other
3,4,Ab Lench,Worcestershire,England,SP0151,401500,251500,52.16177,-1.97949,WR11 4,Other
4,5,Abbas Combe,Somerset,England,ST7022,370500,122500,51.00113,-2.42178,BA8 0,Other

In [4]:
print(df.columns)

Index(['id', 'place_name', 'county', 'country', 'grid_reference', 'easting',
       'northing', 'latitude', 'longitude', 'postcode_area', 'type'],
      dtype='str')

In [7]:
def clean_text(text):
    ...

In [11]:
df.columns

Index(['id', 'place_name', 'county', 'country', 'grid_reference', 'easting',
       'northing', 'latitude', 'longitude', 'postcode_area', 'type'],
      dtype='str')

In [13]:
df.head()

,id,place_name,county,country,grid_reference,easting,northing,latitude,longitude,postcode_area,type
0,1,A' Chill,Highland,Scotland,NG2605,126500,805500,57.05909,-6.51277,PH44 4,Other
1,2,Aaron's Hill,Surrey,England,SU9543,495500,143500,51.18276,-0.63503,GU7 2,Other
2,3,Ab Kettleby,Leicestershire,England,SK7223,472500,323500,52.80419,-0.92601,LE14 3,Other
3,4,Ab Lench,Worcestershire,England,SP0151,401500,251500,52.16177,-1.97949,WR11 4,Other
4,5,Abbas Combe,Somerset,England,ST7022,370500,122500,51.00113,-2.42178,BA8 0,Other

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans

# 0. DEFINE YOUR DATA
text_data = [
    "I love machine learning and data science",
    "KMeans clustering is useful for grouping data",
    "Python is great for AI and machine learning",
    "Football and sports are popular worldwide",
    "The match was exciting and the team played well",
    "Data science involves statistics and programming",
    "AI and deep learning are parts of machine learning",
    "Sports events bring fans together"
]

# 1. Vectorize text
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(text_data)

# 2. KMeans
num_clusters = 2
kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init=10)
kmeans.fit(X)

# 3. Get words
terms = vectorizer.get_feature_names_out()

# 4. Sort cluster centers
order_centroids = kmeans.cluster_centers_.argsort()[:, ::-1]

# 5. Print clusters
for i in range(num_clusters):
    print(f"\nCluster {i}:")
    top_words = [terms[ind] for ind in order_centroids[i, :10]]
    print(", ".join(top_words))

Cluster 0:
the, played, was, and, team, well, match, exciting, worldwide, great

Cluster 1:
and, learning, machine, data, sports, is, for, science, ai, are

In [19]:
print("df:", df.shape)
print("X:", X.shape)
print("reduced:", reduced.shape)

df: (43143, 11)
X: (8, 37)
reduced: (8, 2)

In [22]:
df.index

RangeIndex(start=0, stop=43143, step=1)

In [23]:
df.reset_index()

,index,id,place_name,county,country,grid_reference,easting,northing,latitude,longitude,postcode_area,type
0,0,1,A' Chill,Highland,Scotland,NG2605,126500,805500,57.05909,-6.51277,PH44 4,Other
1,1,2,Aaron's Hill,Surrey,England,SU9543,495500,143500,51.18276,-0.63503,GU7 2,Other
2,2,3,Ab Kettleby,Leicestershire,England,SK7223,472500,323500,52.80419,-0.92601,LE14 3,Other
3,3,4,Ab Lench,Worcestershire,England,SP0151,401500,251500,52.16177,-1.97949,WR11 4,Other
4,4,5,Abbas Combe,Somerset,England,ST7022,370500,122500,51.00113,-2.42178,BA8 0,Other
...,...,...,...,...,...,...,...,...,...,...,...,...
43138,43138,43139,Zeals,Wiltshire,England,ST7831,378500,131500,51.08241,-2.30831,BA12 6,Other
43139,43139,43140,Zelah,Cornwall,England,SW8151,181500,51500,50.32283,-5.07095,TR4 9,Other
43140,43140,43141,Zennor,Cornwall,England,SW4538,145500,38500,50.19170,-5.56700,TR26 3,Other
43141,43141,43142,Zoar,Cornwall,England,SW7619,176500,19500,50.03360,-5.12228,TR12 6,Other
43142,43142,43143,Zouch,Nottinghamshire,England,SK5023,450500,323500,52.80670,-1.25231,LE12 5,Other