In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import silhouette_score

import nltk
from nltk.corpus import stopwords

import warnings
warnings.filterwarnings("ignore")

nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
file_path = "us-cities-top-1k-multi-year.csv"

df = pd.read_csv(file_path)

df.head()

         City           State  Population        lat         lon  year
0  Marysville      Washington       63269  48.051764 -122.177082  2014
1      Perris      California       72326  33.782519 -117.228648  2014
2   Cleveland            Ohio      390113  41.499320  -81.694361  2014
3   Worcester   Massachusetts      182544  42.262593  -71.802293  2014
4    Columbia  South Carolina      133358  34.000710  -81.034814  2014

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        4000 non-null   str
 1   State       4000 non-null   str
 2   Population  4000 non-null   int64
 3   lat         4000 non-null   float64
 4   lon         4000 non-null   float64
 5   year        4000 non-null   int64
dtypes: float64(2), int64(2), str(2)
memory usage: 255.8 KB

In [4]:
text_columns = df.select_dtypes(include=["object"]).columns

text_columns

Index(['City', 'State'], dtype='str')

In [6]:

df.head()

         City           State  Population        lat         lon  year
0  Marysville      Washington       63269  48.051764 -122.177082  2014
1      Perris      California       72326  33.782519 -117.228648  2014
2   Cleveland            Ohio      390113  41.499320  -81.694361  2014
3   Worcester   Massachusetts      182544  42.262593  -71.802293  2014
4    Columbia  South Carolina      133358  34.000710  -81.034814  2014

In [7]:
numeric_columns = df.select_dtypes(
    include=["int64","float64"]
).columns

numeric_columns

Index(['Population', 'lat', 'lon', 'year'], dtype='str')

In [8]:
df.to_csv(
    "us_cities_kmeans_clusters.csv",
    index=False
)