In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluation
from sklearn.metrics import silhouette_score

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load CSV file
df = pd.read_csv("USA_cars_datasets.csv")

# Display first rows
df.head()

,Unnamed: 0,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [3]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    2499 non-null   int64
 1   price         2499 non-null   int64
 2   brand         2499 non-null   str
 3   model         2499 non-null   str
 4   year          2499 non-null   int64
 5   title_status  2499 non-null   str
 6   mileage       2499 non-null   int64
 7   color         2499 non-null   str
 8   vin           2499 non-null   str
 9   lot           2499 non-null   int64
 10  state         2499 non-null   str
 11  country       2499 non-null   str
 12  condition     2499 non-null   str
dtypes: int64(5), str(8)
memory usage: 430.9 KB

In [4]:
# Remove duplicate rows
df = df.drop_duplicates()

# Fill missing text values
text_columns = ['brand', 'model', 'title_status', 'color', 'state']

for col in text_columns:
    if col in df.columns:
        df[col] = df[col].fillna("unknown")

df.head()

,Unnamed: 0,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [5]:
# Combine text columns for NLP

df['car_text'] = (
    df['brand'].astype(str) + " " +
    df['model'].astype(str) + " " +
    df['color'].astype(str) + " " +
    df['title_status'].astype(str)
)

df[['car_text']].head()

                             car_text
0  toyota cruiser black clean vehicle
1        ford se silver clean vehicle
2      dodge mpv silver clean vehicle
3        ford door blue clean vehicle
4    chevrolet 1500 red clean vehicle

In [6]:
numeric_features = df[['year','price','mileage']]

numeric_features.head()

   year  price  mileage
0  2008   6300   274117
1  2011   2899   190552
2  2018   5350    39590
3  2014  25000    64146
4  2018  27700     6654

In [7]:
scaler = StandardScaler()

scaled_numeric = scaler.fit_transform(numeric_features)

In [9]:
df.head()

,Unnamed: 0,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,car_text
0,0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left,toyota cruiser black clean vehicle
1,1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,ford se silver clean vehicle
2,2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left,dodge mpv silver clean vehicle
3,3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,ford door blue clean vehicle
4,4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,chevrolet 1500 red clean vehicle

In [10]:
df.to_csv(
    "USA_cars_clustered.csv",
    index=False
)

print("File saved successfully")

File saved successfully