In [2]:
import pandas as pd
import numpy as np

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

# Clustering
from sklearn.cluster import KMeans

# Visualization
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Preprocessing
import re

In [3]:
df = pd.read_csv("vendor_booth_inventory.csv")

df.head()

  market_date;"quantity";"vendor_id";"product_id";"original_price"
0                           2019-07-03;7.38;7;1;6.99
1                          2019-07-06;10.96;7;1;6.99
2                          2019-07-10;13.08;7;1;6.99
3                          2019-07-13;10.22;7;1;6.99
4                          2019-07-17;10.59;7;1;6.99

In [4]:
print(df.columns)

Index(['market_date;"quantity";"vendor_id";"product_id";"original_price"'], dtype='str')

In [6]:
df.head()

  market_date;"quantity";"vendor_id";"product_id";"original_price"
0                           2019-07-03;7.38;7;1;6.99
1                          2019-07-06;10.96;7;1;6.99
2                          2019-07-10;13.08;7;1;6.99
3                          2019-07-13;10.22;7;1;6.99
4                          2019-07-17;10.59;7;1;6.99

In [8]:
df.head()

  market_date;"quantity";"vendor_id";"product_id";"original_price"
0                           2019-07-03;7.38;7;1;6.99
1                          2019-07-06;10.96;7;1;6.99
2                          2019-07-10;13.08;7;1;6.99
3                          2019-07-13;10.22;7;1;6.99
4                          2019-07-17;10.59;7;1;6.99

In [10]:
print(df.columns.tolist())
print(df.head())

['market_date;"quantity";"vendor_id";"product_id";"original_price"']
  market_date;"quantity";"vendor_id";"product_id";"original_price"
0                           2019-07-03;7.38;7;1;6.99
1                          2019-07-06;10.96;7;1;6.99
2                          2019-07-10;13.08;7;1;6.99
3                          2019-07-13;10.22;7;1;6.99
4                          2019-07-17;10.59;7;1;6.99

In [12]:
print(df.columns.tolist())

['market_date;"quantity";"vendor_id";"product_id";"original_price"']

In [13]:
df.to_csv("vendor_booth_clustered.csv", index=False)