In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# NLP
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

import re

# Download NLP resources
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("Wage Rigidity Dataset.csv")

# Display first rows
df.head()

,Date,All workers (hourly and non-hourly),Hourly workers,Non-hourly workers,Less than high school,High school,Some college,College,Construction,Finance,Manufacturing
0,01/01/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/02/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/03/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01/04/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/05/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Date                                 435 non-null    str
 1   All workers (hourly and non-hourly)  355 non-null    float64
 2   Hourly workers                       355 non-null    float64
 3   Non-hourly workers                   355 non-null    float64
 4   Less than high school                355 non-null    float64
 5   High school                          355 non-null    float64
 6   Some college                         355 non-null    float64
 7   College                              355 non-null    float64
 8   Construction                         319 non-null    float64
 9   Finance                              319 non-null    float64
 10  Manufacturing                        319 non-null    float64
dtypes: float64(10), str(1)
memory usage: 41.8 KB

In [5]:
df.columns

Index(['Date', 'All workers (hourly and non-hourly)', 'Hourly workers',
       'Non-hourly workers', 'Less than high school', 'High school',
       'Some college', 'College', 'Construction', 'Finance', 'Manufacturing'],
      dtype='str')

In [8]:
df.columns

Index(['Date', 'All workers (hourly and non-hourly)', 'Hourly workers',
       'Non-hourly workers', 'Less than high school', 'High school',
       'Some college', 'College', 'Construction', 'Finance', 'Manufacturing'],
      dtype='str')

In [9]:
df.select_dtypes(include=np.number).columns

Index(['All workers (hourly and non-hourly)', 'Hourly workers',
       'Non-hourly workers', 'Less than high school', 'High school',
       'Some college', 'College', 'Construction', 'Finance', 'Manufacturing'],
      dtype='str')

In [11]:
df.head()
df.columns

Index(['Date', 'All workers (hourly and non-hourly)', 'Hourly workers',
       'Non-hourly workers', 'Less than high school', 'High school',
       'Some college', 'College', 'Construction', 'Finance', 'Manufacturing'],
      dtype='str')

In [12]:
df.head()

,Date,All workers (hourly and non-hourly),Hourly workers,Non-hourly workers,Less than high school,High school,Some college,College,Construction,Finance,Manufacturing
0,01/01/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/02/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/03/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01/04/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/05/1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.to_csv(
    "Wage_Rigidity_KMeans_NLP_Results.csv",
    index=False
)