In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Web Series.csv")

# Preview data
df.head()

      Series Title  Year Released  ... No of Seasons          Streaming Platform
0     Breaking Bad           2008  ...      5Seasons                     Netflix
1  Game of Thrones           2011  ...      8Seasons                 HBO MAX,HBO
2   Rick and Morty           2013  ...      4Seasons  Free Services,HBO MAX,Hulu
3  Stranger Things           2016  ...      3Seasons                     Netflix
4         The Boys           2019  ...      2Seasons                 Prime Video

[5 rows x 9 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(12353, 9)
<class 'pandas.DataFrame'>
RangeIndex: 12353 entries, 0 to 12352
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Series Title        12353 non-null  str
 1   Year Released       12353 non-null  int64
 2   Content Rating      7232 non-null   str
 3   IMDB Rating         10207 non-null  float64
 4   R Rating            12353 non-null  int64
 5   Genre               12353 non-null  str
 6   Description         12353 non-null  str
 7   No of Seasons       12353 non-null  str
 8   Streaming Platform  10370 non-null  str
dtypes: float64(1), int64(2), str(6)
memory usage: 9.2 MB
None
Series Title             0
Year Released            0
Content Rating        5121
IMDB Rating           2146
R Rating                 0
Genre                    0
Description              0
No of Seasons            0
Streaming Platform    1983
dtype: int64

In [5]:
# numeric
df = df.fillna(df.median(numeric_only=True))

# categorical
cat_cols = df.select_dtypes(include=['object', 'string']).columns
df[cat_cols] = df[cat_cols].apply(lambda x: x.fillna(x.mode()[0]))

In [7]:
df = pd.get_dummies(df, columns=cat_cols)

In [9]:
for col in df.columns:
    print(f"'{col}'")

'Year Released'
'IMDB Rating'
'R Rating'
'Series Title_0'
'Series Title_1'
'Series Title_2'
'Series Title_3'
'Series Title_4'
'Series Title_5'
'Series Title_6'
'Series Title_7'
'Series Title_8'
'Series Title_9'
'Series Title_10'
'Series Title_11'
'Series Title_12'
'Series Title_13'
'Series Title_14'
'Series Title_15'
'Series Title_16'
'Series Title_17'
'Series Title_18'
'Series Title_19'
'Series Title_20'
'Series Title_21'
'Series Title_22'
'Series Title_23'
'Series Title_24'
'Series Title_25'
'Series Title_26'
'Series Title_27'
'Series Title_28'
'Series Title_29'
'Series Title_30'
'Series Title_31'
'Series Title_32'
'Series Title_33'
'Series Title_34'
'Series Title_35'
'Series Title_36'
'Series Title_37'
'Series Title_38'
'Series Title_39'
'Series Title_40'
'Series Title_41'
'Series Title_42'
'Series Title_43'
'Series Title_44'
'Series Title_45'
'Series Title_46'
'Series Title_47'
'Series Title_48'
'Series Title_49'
'Series Title_50'
'Series Title_51'
'Series Title_52'
'Series Title_53'
'Series Title_54'
'Series Title_55'
'Series Title_56'
'Series Title_57'
'Series Title_58'
'Series Title_59'
'Series Title_60'
'Series Title_61'
'Series Title_62'
'Series Title_63'
'Series Title_64'
'Series Title_65'
'Series Title_66'
'Series Title_67'
'Series Title_68'
'Series Title_69'
'Series Title_70'
'Series Title_71'
'Series Title_72'
'Series Title_73'
'Series Title_74'
'Series Title_75'
'Series Title_76'
'Series Title_77'
'Series Title_78'
'Series Title_79'
'Series Title_80'
'Series Title_81'
'Series Title_82'
'Series Title_83'
'Series Title_84'
'Series Title_85'
'Series Title_86'
'Series Title_87'
'Series Title_88'
'Series Title_89'
'Series Title_90'
'Series Title_91'
'Series Title_92'
'Series Title_93'
'Series Title_94'
'Series Title_95'
'Series Title_96'
'Series Title_97'
'Series Title_98'
'Series Title_99'
'Series Title_100'
'Series Title_101'
'Series Title_102'
'Series Title_103'
'Series Title_104'
'Series Title_105'
'Series Title_106'
'Series Title_107'
'Series Title_108'
'Series Title_109'
'Series Title_110'
'Series Title_111'
'Series Title_112'
'Series Title_113'
'Series Title_114'
'Series Title_115'
'Series Title_116'
'Series Title_117'
'Series Title_118'
'Series Title_119'
'Series Title_120'
'Series Title_121'
'Series Title_122'
'Series Title_123'
'Series Title_124'
'Series Title_125'
'Series Title_126'
'Series Title_127'
'Series Title_128'
'Series Title_129'
'Series Title_130'
'Series Title_131'
'Series Title_132'
'Series Title_133'
'Series Title_134'
'Series Title_135'
'Series Title_136'
'Series Title_137'
'Series Title_138'
'Series Title_139'
'Series Title_140'
'Series Title_141'
'Series Title_142'
'Series Title_143'
'Series Title_144'
'Series Title_145'
'Series Title_146'
'Series Title_147'
'Series Title_148'
'Series Title_149'
'Series Title_150'
'Series Title_151'
'Series Title_152'
'Series Title_153'
'Series Title_154'
'Series Title_155'
'Series Title_156'
'Series Title_157'
'Series Title_158'
'Series Title_159'
'Series Title_160'
'Series Title_161'
'Series Title_162'
'Series Title_163'
'Series Title_164'
'Series Title_165'
'Series Title_166'
'Series Title_167'
'Series Title_168'
'Series Title_169'
'Series Title_170'
'Series Title_171'
'Series Title_172'
'Series Title_173'
'Series Title_174'
'Series Title_175'
'Series Title_176'
'Series Title_177'
'Series Title_178'
'Series Title_179'
'Series Title_180'
'Series Title_181'
'Series Title_182'
'Series Title_183'
'Series Title_184'
'Series Title_185'
'Series Title_186'
'Series Title_187'
'Series Title_188'
'Series Title_189'
'Series Title_190'
'Series Title_191'
'Series Title_192'
'Series Title_193'
'Series Title_194'
'Series Title_195'
'Series Title_196'
'Series Title_197'
'Series Title_198'
'Series Title_199'
'Series Title_200'
'Series Title_201'
'Series Title_202'
'Series Title_203'
'Series Title_204'
'Series Title_205'
'Series Title_206'
'Series Title_207'
'Series Title_208'
'Series Title_209'
'Series Title_210'
'Series Title_211'
'Series Title_212'
'Series Title_213'
'Series Title_214'
'Series Title_215'
'Series Title_216'
'Series Title_217'
'Series Title_218'
'Series Title_219'
'Series Title_220'
'Series Title_221'
'Series Title_222'
'Series Title_223'
'Series Title_224'
'Series Title_225'
'Series Title_226'
'Series Title_227'
'Series Title_228'
'Series Title_229'
'Series Title_230'
'Series Title_231'
'Series Title_232'
'Series Title_233'
'Series Title_234'
'Series Title_235'
'Series Title_236'
'Series Title_237'
'Series Title_238'
'Series Title_239'
'Series Title_240'
'Series Title_241'
'Series Title_242'
'Series Title_243'
'Series Title_244'
'Series Title_245'
'Series Title_246'
'Series Title_247'
'Series Title_248'
'Series Title_249'
'Series Title_250'
'Series Title_251'
'Series Title_252'
'Series Title_253'
'Series Title_254'
'Series Title_255'
'Series Title_256'
'Series Title_257'
'Series Title_258'
'Series Title_259'
'Series Title_260'
'Series Title_261'
'Series Title_262'
'Series Title_263'
'Series Title_264'
'Series Title_265'
'Series Title_266'
'Series Title_267'
'Series Title_268'
'Series Title_269'
'Series Title_270'
'Series Title_271'
'Series Title_272'
'Series Title_273'
'Series Title_274'
'Series Title_275'
'Series Title_276'
'Series Title_277'
'Series Title_278'
'Series Title_279'
'Series Title_280'
'Series Title_281'
'Series Title_282'
'Series Title_283'
'Series Title_284'
'Series Title_285'
'Series Title_286'
'Series Title_287'
'Series Title_288'
'Series Title_289'
'Series Title_290'
'Series Title_291'
'Series Title_292'
'Series Title_293'
'Series Title_294'
'Series Title_295'
'Series Title_296'
'Series Title_297'
'Series Title_298'
'Series Title_299'
'Series Title_300'
'Series Title_301'
'Series Title_302'
'Series Title_303'
'Series Title_304'
'Series Title_305'
'Series Title_306'
'Series Title_307'
'Series Title_308'
'Series Title_309'
'Series Title_310'
'Series Title_311'
'Series Title_312'
'Series Title_313'
'Series Title_314'
'Series Title_315'
'Series Title_316'
'Series Title_317'
'Series Title_318'
'Series Title_319'
'Series Title_320'
'Series Title_321'
'Series Title_322'
'Series Title_323'
'Series Title_324'
'Series Title_325'
'Series Title_326'
'Series Title_327'
'Series Title_328'
'Series Title_329'
'Series Title_330'
'Series Title_331'
'Series Title_332'
'Series Title_333'
'Series Title_334'
'Series Title_335'
'Series Title_336'
'Series Title_337'
'Series Title_338'
'Series Title_339'
'Series Title_340'
'Series Title_341'
'Series Title_342'
'Series Title_343'
'Series Title_344'
'Series Title_345'
'Series Title_346'
'Series Title_347'
'Series Title_348'
'Series Title_349'
'Series Title_350'
'Series Title_351'
'Series Title_352'
'Series Title_353'
'Series Title_354'
'Series Title_355'
'Series Title_356'
'Series Title_357'
'Series Title_358'
'Series Title_359'
'Series Title_360'
'Series Title_361'
'Series Title_362'
'Series Title_363'
'Series Title_364'
'Series Title_365'
'Series Title_366'
'Series Title_367'
'Series Title_368'
'Series Title_369'
'Series Title_370'
'Series Title_371'
'Series Title_372'
'Series Title_373'
'Series Title_374'
'Series Title_375'
'Series Title_376'
'Series Title_377'
'Series Title_378'
'Series Title_379'
'Series Title_380'
'Series Title_381'
'Series Title_382'
'Series Title_383'
'Series Title_384'
'Series Title_385'
'Series Title_386'
'Series Title_387'
'Series Title_388'
'Series Title_389'
'Series Title_390'
'Series Title_391'
'Series Title_392'
'Series Title_393'
'Series Title_394'
'Series Title_395'
'Series Title_396'
'Series Title_397'
'Series Title_398'
'Series Title_399'
'Series Title_400'
'Series Title_401'
'Series Title_402'
'Series Title_403'
'Series Title_404'
'Series Title_405'
'Series Title_406'
'Series Title_407'
'Series Title_408'
'Series Title_409'
'Series Title_410'
'Series Title_411'
'Series Title_412'
'Series Title_413'
'Series Title_414'
'Series Title_415'
'Series Title_416'
'Series Title_417'
'Series Title_418'
'Series Title_419'
'Series Title_420'
'Series Title_421'
'Series Title_422'
'Series Title_423'
'Series Title_424'
'Series Title_425'
'Series Title_426'
'Series Title_427'
'Series Title_428'
'Series Title_429'
'Series Title_430'
'Series Title_431'
'Series Title_432'
'Series Title_433'
'Series Title_434'
'Series Title_435'
'Series Title_436'
'Series Title_437'
'Series Title_438'
'Series Title_439'
'Series Title_440'
'Series Title_441'
'Series Title_442'
'Series Title_443'
'Series Title_444'
'Series Title_445'
'Series Title_446'
'Series Title_447'
'Series Title_448'
'Series Title_449'
'Series Title_450'
'Series Title_451'
'Series Title_452'
'Series Title_453'
'Series Title_454'
'Series Title_455'
'Series Title_456'
'Series Title_457'
'Series Title_458'
'Series Title_459'
'Series Title_460'
'Series Title_461'
'Series Title_462'
'Series Title_463'
'Series Title_464'
'Series Title_465'
'Series Title_466'
'Series Title_467'
'Series Title_468'
'Series Title_469'
'Series Title_470'
'Series Title_471'
'Series Title_472'
'Series Title_473'
'Series Title_474'
'Series Title_475'
'Series Title_476'
'Series Title_477'
'Series Title_478'
'Series Title_479'
'Series Title_480'
'Series Title_481'
'Series Title_482'
'Series Title_483'
'Series Title_484'
'Series Title_485'
'Series Title_486'
'Series Title_487'
'Series Title_488'
'Series Title_489'
'Series Title_490'
'Series Title_491'
'Series Title_492'
'Series Title_493'
'Series Title_494'
'Series Title_495'
'Series Title_496'
'Series Title_497'
'Series Title_498'
'Series Title_499'
'Series Title_500'
'Series Title_501'
'Series Title_502'
'Series Title_503'
'Series Title_504'
'Series Title_505'
'Series Title_506'
'Series Title_507'
'Series Title_508'
'Series Title_509'
'Series Title_510'
'Series Title_511'
'Series Title_512'
'Series Title_513'
'Series Title_514'
'Series Title_515'
'Series Title_516'
'Series Title_517'
'Series Title_518'
'Series Title_519'
'Series Title_520'
'Series Title_521'
'Series Title_522'
'Series Title_523'
'Series Title_524'
'Series Title_525'
'Series Title_526'
'Series Title_527'
'Series Title_528'
'Series Title_529'
'Series Title_530'
'Series Title_531'
'Series Title_532'
'Series Title_533'
'Series Title_534'
'Series Title_535'
'Series Title_536'
'Series Title_537'
'Series Title_538'
'Series Title_539'
'Series Title_540'
'Series Title_541'
'Series Title_542'
'Series Title_543'
'Series Title_544'
'Series Title_545'
'Series Title_546'
'Series Title_547'
'Series Title_548'
'Series Title_549'
'Series Title_550'
'Series Title_551'
'Series Title_552'
'Series Title_553'
'Series Title_554'
'Series Title_555'
'Series Title_556'
'Series Title_557'
'Series Title_558'
'Series Title_559'
'Series Title_560'
'Series Title_561'
'Series Title_562'
'Series Title_563'
'Series Title_564'
'Series Title_565'
'Series Title_566'
'Series Title_567'
'Series Title_568'
'Series Title_569'
'Series Title_570'
'Series Title_571'
'Series Title_572'
'Series Title_573'
'Series Title_574'
'Series Title_575'
'Series Title_576'
'Series Title_577'
'Series Title_578'
'Series Title_579'
'Series Title_580'
'Series Title_581'
'Series Title_582'
'Series Title_583'
'Series Title_584'
'Series Title_585'
'Series Title_586'
'Series Title_587'
'Series Title_588'
'Series Title_589'
'Series Title_590'
'Series Title_591'
'Series Title_592'
'Series Title_593'
'Series Title_594'
'Series Title_595'
'Series Title_596'
'Series Title_597'
'Series Title_598'
'Series Title_599'
'Series Title_600'
'Series Title_601'
'Series Title_602'
'Series Title_603'
'Series Title_604'
'Series Title_605'
'Series Title_606'
'Series Title_607'
'Series Title_608'
'Series Title_609'
'Series Title_610'
'Series Title_611'
'Series Title_612'
'Series Title_613'
'Series Title_614'
'Series Title_615'
'Series Title_616'
'Series Title_617'
'Series Title_618'
'Series Title_619'
'Series Title_620'
'Series Title_621'
'Series Title_622'
'Series Title_623'
'Series Title_624'
'Series Title_625'
'Series Title_626'
'Series Title_627'
'Series Title_628'
'Series Title_629'
'Series Title_630'
'Series Title_631'
'Series Title_632'
'Series Title_633'
'Series Title_634'
'Series Title_635'
'Series Title_636'
'Series Title_637'
'Series Title_638'
'Series Title_639'
'Series Title_640'
'Series Title_641'
'Series Title_642'
'Series Title_643'
'Series Title_644'
'Series Title_645'
'Series Title_646'
'Series Title_647'
'Series Title_648'
'Series Title_649'
'Series Title_650'
'Series Title_651'
'Series Title_652'
'Series Title_653'
'Series Title_654'
'Series Title_655'
'Series Title_656'
'Series Title_657'
'Series Title_658'
'Series Title_659'
'Series Title_660'
'Series Title_661'
'Series Title_662'
'Series Title_663'
'Series Title_664'
'Series Title_665'
'Series Title_666'
'Series Title_667'
'Series Title_668'
'Series Title_669'
'Series Title_670'
'Series Title_671'
'Series Title_672'
'Series Title_673'
'Series Title_674'
'Series Title_675'
'Series Title_676'
'Series Title_677'
'Series Title_678'
'Series Title_679'
'Series Title_680'
'Series Title_681'
'Series Title_682'
'Series Title_683'
'Series Title_684'
'Series Title_685'
'Series Title_686'
'Series Title_687'
'Series Title_688'
'Series Title_689'
'Series Title_690'
'Series Title_691'
'Series Title_692'
'Series Title_693'
'Series Title_694'
'Series Title_695'
'Series Title_696'
'Series Title_697'
'Series Title_698'
'Series Title_699'
'Series Title_700'
'Series Title_701'
'Series Title_702'
'Series Title_703'
'Series Title_704'
'Series Title_705'
'Series Title_706'
'Series Title_707'
'Series Title_708'
'Series Title_709'
'Series Title_710'
'Series Title_711'
'Series Title_712'
'Series Title_713'
'Series Title_714'
'Series Title_715'
'Series Title_716'
'Series Title_717'
'Series Title_718'
'Series Title_719'
'Series Title_720'
'Series Title_721'
'Series Title_722'
'Series Title_723'
'Series Title_724'
'Series Title_725'
'Series Title_726'
'Series Title_727'
'Series Title_728'
'Series Title_729'
'Series Title_730'
'Series Title_731'
'Series Title_732'
'Series Title_733'
'Series Title_734'
'Series Title_735'
'Series Title_736'
'Series Title_737'
'Series Title_738'
'Series Title_739'
'Series Title_740'
'Series Title_741'
'Series Title_742'
'Series Title_743'
'Series Title_744'
'Series Title_745'
'Series Title_746'
'Series Title_747'
'Series Title_748'
'Series Title_749'
'Series Title_750'
'Series Title_751'
'Series Title_752'
'Series Title_753'
'Series Title_754'
'Series Title_755'
'Series Title_756'
'Series Title_757'
'Series Title_758'
'Series Title_759'
'Series Title_760'
'Series Title_761'
'Series Title_762'
'Series Title_763'
'Series Title_764'
'Series Title_765'
'Series Title_766'
'Series Title_767'
'Series Title_768'
'Series Title_769'
'Series Title_770'
'Series Title_771'
'Series Title_772'
'Series Title_773'
'Series Title_774'
'Series Title_775'
'Series Title_776'
'Series Title_777'
'Series Title_778'
'Series Title_779'
'Series Title_780'
'Series Title_781'
'Series Title_782'
'Series Title_783'
'Series Title_784'
'Series Title_785'
'Series Title_786'
'Series Title_787'
'Series Title_788'
'Series Title_789'
'Series Title_790'
'Series Title_791'
'Series Title_792'
'Series Title_793'
'Series Title_794'
'Series Title_795'
'Series Title_796'
'Series Title_797'
'Series Title_798'
'Series Title_799'
'Series Title_800'
'Series Title_801'
'Series Title_802'
'Series Title_803'
'Series Title_804'
'Series Title_805'
'Series Title_806'
'Series Title_807'
'Series Title_808'
'Series Title_809'
'Series Title_810'
'Series Title_811'
'Series Title_812'
'Series Title_813'
'Series Title_814'
'Series Title_815'
'Series Title_816'
'Series Title_817'
'Series Title_818'
'Series Title_819'
'Series Title_820'
'Series Title_821'
'Series Title_822'
'Series Title_823'
'Series Title_824'
'Series Title_825'
'Series Title_826'
'Series Title_827'
'Series Title_828'
'Series Title_829'
'Series Title_830'
'Series Title_831'
'Series Title_832'
'Series Title_833'
'Series Title_834'
'Series Title_835'
'Series Title_836'
'Series Title_837'
'Series Title_838'
'Series Title_839'
'Series Title_840'
'Series Title_841'
'Series Title_842'
'Series Title_843'
'Series Title_844'
'Series Title_845'
'Series Title_846'
'Series Title_847'
'Series Title_848'
'Series Title_849'
'Series Title_850'
'Series Title_851'
'Series Title_852'
'Series Title_853'
'Series Title_854'
'Series Title_855'
'Series Title_856'
'Series Title_857'
'Series Title_858'
'Series Title_859'
'Series Title_860'
'Series Title_861'
'Series Title_862'
'Series Title_863'
'Series Title_864'
'Series Title_865'
'Series Title_866'
'Series Title_867'
'Series Title_868'
'Series Title_869'
'Series Title_870'
'Series Title_871'
'Series Title_872'
'Series Title_873'
'Series Title_874'
'Series Title_875'
'Series Title_876'
'Series Title_877'
'Series Title_878'
'Series Title_879'
'Series Title_880'
'Series Title_881'
'Series Title_882'
'Series Title_883'
'Series Title_884'
'Series Title_885'
'Series Title_886'
'Series Title_887'
'Series Title_888'
'Series Title_889'
'Series Title_890'
'Series Title_891'
'Series Title_892'
'Series Title_893'
'Series Title_894'
'Series Title_895'
'Series Title_896'
'Series Title_897'
'Series Title_898'
'Series Title_899'
'Series Title_900'
'Series Title_901'
'Series Title_902'
'Series Title_903'
'Series Title_904'
'Series Title_905'
'Series Title_906'
'Series Title_907'
'Series Title_908'
'Series Title_909'
'Series Title_910'
'Series Title_911'
'Series Title_912'
'Series Title_913'
'Series Title_914'
'Series Title_915'
'Series Title_916'
'Series Title_917'
'Series Title_918'
'Series Title_919'
'Series Title_920'
'Series Title_921'
'Series Title_922'
'Series Title_923'
'Series Title_924'
'Series Title_925'
'Series Title_926'
'Series Title_927'
'Series Title_928'
'Series Title_929'
'Series Title_930'
'Series Title_931'
'Series Title_932'
'Series Title_933'
'Series Title_934'
'Series Title_935'
'Series Title_936'
'Series Title_937'
'Series Title_938'
'Series Title_939'
'Series Title_940'
'Series Title_941'
'Series Title_942'
'Series Title_943'
'Series Title_944'
'Series Title_945'
'Series Title_946'
'Series Title_947'
'Series Title_948'
'Series Title_949'
'Series Title_950'
'Series Title_951'
'Series Title_952'
'Series Title_953'
'Series Title_954'
'Series Title_955'
'Series Title_956'
'Series Title_957'
'Series Title_958'
'Series Title_959'
'Series Title_960'
'Series Title_961'
'Series Title_962'
'Series Title_963'
'Series Title_964'
'Series Title_965'
'Series Title_966'
'Series Title_967'
'Series Title_968'
'Series Title_969'
'Series Title_970'
'Series Title_971'
'Series Title_972'
'Series Title_973'
'Series Title_974'
'Series Title_975'
'Series Title_976'
'Series Title_977'
'Series Title_978'
'Series Title_979'
'Series Title_980'
'Series Title_981'
'Series Title_982'
'Series Title_983'
'Series Title_984'
'Series Title_985'
'Series Title_986'
'Series Title_987'
'Series Title_988'
'Series Title_989'
'Series Title_990'
'Series Title_991'
'Series Title_992'
'Series Title_993'
'Series Title_994'
'Series Title_995'
'Series Title_996'
'Series Title_997'
'Series Title_998'
'Series Title_999'
'Series Title_1000'
'Series Title_1001'
'Series Title_1002'
'Series Title_1003'
'Series Title_1004'
'Series Title_1005'
'Series Title_1006'
'Series Title_1007'
'Series Title_1008'
'Series Title_1009'
'Series Title_1010'
'Series Title_1011'
'Series Title_1012'
'Series Title_1013'
'Series Title_1014'
'Series Title_1015'
'Series Title_1016'
'Series Title_1017'
'Series Title_1018'
'Series Title_1019'
'Series Title_1020'
'Series Title_1021'
'Series Title_1022'
'Series Title_1023'
'Series Title_1024'
'Series Title_1025'
'Series Title_1026'
'Series Title_1027'
'Series Title_1028'
'Series Title_1029'
'Series Title_1030'
'Series Title_1031'
'Series Title_1032'
'Series Title_1033'
'Series Title_1034'
'Series Title_1035'
'Series Title_1036'
'Series Title_1037'
'Series Title_1038'
'Series Title_1039'
'Series Title_1040'
'Series Title_1041'
'Series Title_1042'
'Series Title_1043'
'Series Title_1044'
'Series Title_1045'
'Series Title_1046'
'Series Title_1047'
'Series Title_1048'
'Series Title_1049'
'Series Title_1050'
'Series Title_1051'
'Series Title_1052'

In [12]:
print(df.head())
print(df.columns.tolist())

   Year Released  IMDB Rating  ...  Streaming Platform_528  Streaming Platform_529
0           2008          9.5  ...                   False                   False
1           2011          9.3  ...                   False                   False
2           2013          9.2  ...                   False                   False
3           2016          8.8  ...                   False                   False
4           2019          8.7  ...                   False                   False

[5 rows x 25474 columns]

In [15]:
df.head()

   Year Released  IMDB Rating  ...  Streaming Platform_528  Streaming Platform_529
0           2008          9.5  ...                   False                   False
1           2011          9.3  ...                   False                   False
2           2013          9.2  ...                   False                   False
3           2016          8.8  ...                   False                   False
4           2019          8.7  ...                   False                   False

[5 rows x 25474 columns]

In [21]:
print(df.columns)

Index(['Year Released', 'IMDB Rating', 'R Rating', 'Series Title_0',
       'Series Title_1', 'Series Title_2', 'Series Title_3', 'Series Title_4',
       'Series Title_5', 'Series Title_6',
       ...
       'Streaming Platform_520', 'Streaming Platform_521',
       'Streaming Platform_522', 'Streaming Platform_523',
       'Streaming Platform_524', 'Streaming Platform_525',
       'Streaming Platform_526', 'Streaming Platform_527',
       'Streaming Platform_528', 'Streaming Platform_529'],
      dtype='str', length=25474)