In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("wii_u.csv")

df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,007 Legends,2012-12-11,3.33,NaN,Action,007 Legends is a first-person shooter video ga...,https://images.launchbox-app.com/e4eef476-2759...
1,1001 Spikes,2014-06-03,3.90,NaN,Platformer,Prepare to die. A lot. This brutally challengi...,https://images.launchbox-app.com/61c5ff49-428b...
2,140,2016-11-29,NaN,NaN,Rhythm Platformer,140 is a mesmerizing rhythm-action platformer ...,https://images.launchbox-app.com/809e7a03-bc43...
3,153 Hand Video Poker,2016-06-02,2.90,NaN,Card / Casino,Play 153 hands of video poker simultaneously i...,https://images.launchbox-app.com/103fd0de-16c2...
4,360 Breakout,NaN,3.69,NaN,NaN,NaN,https://images.launchbox-app.com/7f74da53-5b2f...

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(675, 7)
<class 'pandas.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          675 non-null    str
 1   released       512 non-null    str
 2   gf_score       558 non-null    float64
 3   metascore      108 non-null    float64
 4   genre          518 non-null    str
 5   description    522 non-null    str
 6   cover_art_url  668 non-null    str
dtypes: float64(2), str(5)
memory usage: 415.2 KB
None
title              0
released         163
gf_score         117
metascore        567
genre            157
description      153
cover_art_url      7
dtype: int64

In [4]:
df = df.dropna()   # or you can use fillna() depending on dataset

In [7]:
df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
22,Affordable Space Adventures,2015-04-09,3.96,81.0,Action,Affordable Space Adventures is a puzzle advent...,https://images.launchbox-app.com/fb24f2c3-d33f...
31,Animal Crossing: amiibo Festival,2015-11-13,2.92,46.0,Miscellaneous,Animal Crossing: Amiibo Festival is a party vi...,https://images.launchbox-app.com/eda6613e-e8fd...
42,Art Academy: SketchPad,2013-08-09,3.77,70.0,Miscellaneous,"Art Academy, also known as Art Academy: Learn ...",https://images.launchbox-app.com/24a6e675-48fd...
43,Art of Balance,2014-10-09,4.03,82.0,Puzzle,Art of Balance is a physics-based puzzle video...,https://images.launchbox-app.com/daea58ab-4467...
46,Assassin's Creed III,2012-11-18,3.69,85.0,Action Adventure,Assassin's Creed III is a 2012 action-adventur...,https://images.launchbox-app.com/7bce7856-4547...

In [10]:
df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
22,Affordable Space Adventures,2015-04-09,3.96,81.0,Action,Affordable Space Adventures is a puzzle advent...,https://images.launchbox-app.com/fb24f2c3-d33f...
31,Animal Crossing: amiibo Festival,2015-11-13,2.92,46.0,Miscellaneous,Animal Crossing: Amiibo Festival is a party vi...,https://images.launchbox-app.com/eda6613e-e8fd...
42,Art Academy: SketchPad,2013-08-09,3.77,70.0,Miscellaneous,"Art Academy, also known as Art Academy: Learn ...",https://images.launchbox-app.com/24a6e675-48fd...
43,Art of Balance,2014-10-09,4.03,82.0,Puzzle,Art of Balance is a physics-based puzzle video...,https://images.launchbox-app.com/daea58ab-4467...
46,Assassin's Creed III,2012-11-18,3.69,85.0,Action Adventure,Assassin's Creed III is a 2012 action-adventur...,https://images.launchbox-app.com/7bce7856-4547...

In [12]:
df.head()
df.columns

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')