In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("wii.csv")

df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,Metroid Prime Trilogy,2009-08-24,4.60,91.0,Miscellaneous,Metroid Prime: Trilogy is a compilation of act...,https://i.postimg.cc/QCjk1W5v/15d51c0c-3891-48...
1,Xenoblade Chronicles,2012-04-06,4.58,92.0,Role-Playing,Xenoblade Chronicles is an open world action r...,https://i.postimg.cc/rmL6DqhH/09a2a3dc-e331-49...
2,Resident Evil 4: Wii Edition,2007-06-19,4.49,91.0,Action Adventure,Resident Evil 4 is a third-person shooter surv...,https://i.postimg.cc/xTB6ftpx/d1e64ea3-c642-4c...
3,Super Mario Galaxy 2,2010-05-23,4.45,97.0,Action,Super Mario Galaxy 2 is a platform video game ...,https://i.postimg.cc/TwHSvmyn/1419fddc-81a0-4c...
4,Super Smash Bros. Brawl,2008-03-09,4.40,93.0,Action,Super Smash Bros. Brawl is a crossover fightin...,https://i.postimg.cc/1zYhsb2g/1dc7b262-5be9-4a...

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(396, 7)
<class 'pandas.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          396 non-null    str
 1   released       396 non-null    str
 2   gf_score       396 non-null    float64
 3   metascore      370 non-null    float64
 4   genre          396 non-null    str
 5   description    396 non-null    str
 6   cover_art_url  396 non-null    str
dtypes: float64(2), str(5)
memory usage: 248.2 KB
None
         gf_score   metascore
count  396.000000  370.000000
mean     3.706111   70.518919
std      0.435864   12.657503
min      1.170000   19.000000
25%      3.490000   65.000000
50%      3.790000   72.000000
75%      4.000000   79.000000
max      4.600000   97.000000
title             0
released          0
gf_score          0
metascore        26
genre             0
description       0
cover_art_url     0
dtype: int64

In [6]:
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

df[cat_cols] = df[cat_cols].fillna(
    df[cat_cols].mode().iloc[0]
)

In [7]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for col in df.select_dtypes(include=["object", "string"]).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))  # extra safety
    label_encoders[col] = le

In [8]:
df.head()

   title  released  gf_score  metascore  genre  description  cover_art_url
0    192       167      4.60       91.0      3          196            334
1    388       271      4.58       92.0      6          388            362
2    265        22      4.49       91.0      1          264            370
3    319       218      4.45       97.0      0          315            343
4    322        68      4.40       93.0      0          319            306

In [11]:
print(df.head())
print(df.columns)

   title  released  gf_score  metascore  genre  description  cover_art_url
0    192       167      4.60       91.0      3          196            334
1    388       271      4.58       92.0      6          388            362
2    265        22      4.49       91.0      1          264            370
3    319       218      4.45       97.0      0          315            343
4    322        68      4.40       93.0      0          319            306
Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')

In [14]:
df.columns

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')