In [1]:
# NLP + Data Analysis Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import re

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load World Series dataset

df = pd.read_csv("World_Series.csv")

# Display first rows

df.head()

,Name,Year,Teams,Total Posts,Total Comments,Total Scores,Avg Sentiment (TextBlob),Avg Sentiment (Vader),Viewers (Millions)
0,2024 World Series Game 1,2024,"Los Angeles Dodgers, New York Yankees",120,1961,7604,0.045565,0.321271,14.163
1,2024 World Series Game 2,2024,"Los Angeles Dodgers, New York Yankees",133,199,568,0.033256,0.273351,13.713
2,2024 World Series Game 3,2024,"Los Angeles Dodgers, New York Yankees",125,109,601,0.039038,0.269532,13.208
3,2024 World Series Game 4,2024,"Los Angeles Dodgers, New York Yankees",112,447,1399,0.018830,0.262246,16.275
4,2024 World Series Game 5,2024,"Los Angeles Dodgers, New York Yankees",137,2344,11510,0.006948,0.252765,18.152

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      76 non-null     str
 1   Year                      76 non-null     int64
 2   Teams                     76 non-null     str
 3   Total Posts               76 non-null     int64
 4   Total Comments            76 non-null     int64
 5   Total Scores              76 non-null     int64
 6   Avg Sentiment (TextBlob)  76 non-null     float64
 7   Avg Sentiment (Vader)     76 non-null     float64
 8   Viewers (Millions)        76 non-null     float64
dtypes: float64(3), int64(4), str(2)
memory usage: 9.9 KB

In [4]:
# Select text columns

text_columns = df.select_dtypes(include=['object']).columns

text_columns

Index(['Name', 'Teams'], dtype='str')

In [6]:

df.head()

,Name,Year,Teams,Total Posts,Total Comments,Total Scores,Avg Sentiment (TextBlob),Avg Sentiment (Vader),Viewers (Millions)
0,2024 World Series Game 1,2024,"Los Angeles Dodgers, New York Yankees",120,1961,7604,0.045565,0.321271,14.163
1,2024 World Series Game 2,2024,"Los Angeles Dodgers, New York Yankees",133,199,568,0.033256,0.273351,13.713
2,2024 World Series Game 3,2024,"Los Angeles Dodgers, New York Yankees",125,109,601,0.039038,0.269532,13.208
3,2024 World Series Game 4,2024,"Los Angeles Dodgers, New York Yankees",112,447,1399,0.018830,0.262246,16.275
4,2024 World Series Game 5,2024,"Los Angeles Dodgers, New York Yankees",137,2344,11510,0.006948,0.252765,18.152

In [8]:
# Export results

df.to_csv(
    "World_Series_KMeans_NLP_results.csv",
    index=False
)